// Every "save a copy" in the app, through one door.
//
// In a browser, and on the desktop, this is the a[download] click the app has
// always made — moved here from seven call sites that each spelled it out.
//
// Inside the phone app that click has nowhere to go: a blob: URL lives in the
// page's memory, and neither WKDownload nor Android's DownloadListener can
// read it. So the phone gets the file through `murageNative.saveFile`
// (spec §3.2):
//   - a file the server already serves is passed as its URL, and native
//     downloads it with the WebView's own cookie — large files never cross
//     the channel;
//   - generated bytes go in 1 MB base64 pieces, and never more than 25 MB,
//     because each piece is a string held in two processes at once;
//   - a file on another site is never a native download: it opens in the
//     system browser (`saveSource`).
import { callNative, nativeAvailable } from "./native-shell";

export const NATIVE_SAVE_CHUNK_BYTES = 1024 * 1024;
export const NATIVE_SAVE_MAX_BYTES = 25 * 1024 * 1024;

/** The shape `murageNative.saveFile` accepts. Plan 2's native code implements
 * exactly this; change both together. */
export type NativeSaveRequest =
  | { kind: "url"; url: string; filename: string }
  | { kind: "begin"; id: string; filename: string; mime: string; size: number }
  | { kind: "chunk"; id: string; index: number; base64: string }
  | { kind: "end"; id: string }
  | { kind: "abort"; id: string };

const save = (request: NativeSaveRequest) => callNative("saveFile", request);

/** The browser half: a temporary anchor, always removed. */
export function clickDownload(url: string, filename: string): void {
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.rel = "noopener";
  link.referrerPolicy = "no-referrer";
  try {
    document.body.appendChild(link);
    link.click();
  } finally {
    link.remove();
  }
}

function base64(bytes: Uint8Array): string {
  let binary = "";
  // String.fromCharCode with a spread overflows the stack past ~100k args.
  for (let at = 0; at < bytes.length; at += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(at, at + 0x8000));
  }
  return btoa(binary);
}

function transferId(): string {
  return globalThis.crypto?.randomUUID?.() ?? `save-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

/** A refusal this module words for the person, marked by `code` so
 * `saveFailureMessage` shows it as written. */
function saveError(message: string, code: "too-large" | "damaged" | "elsewhere"): Error {
  return Object.assign(new Error(message), { code });
}

async function saveBlobNatively(blob: Blob, filename: string): Promise<void> {
  if (blob.size > NATIVE_SAVE_MAX_BYTES) {
    throw saveError("This file is bigger than 25 MB, too big to save on this phone. Save it from Murage on your computer.", "too-large");
  }
  const id = transferId();
  await save({ kind: "begin", id, filename, mime: blob.type || "application/octet-stream", size: blob.size });
  try {
    for (let index = 0, offset = 0; offset < blob.size; index += 1, offset += NATIVE_SAVE_CHUNK_BYTES) {
      const piece = new Uint8Array(await blob.slice(offset, offset + NATIVE_SAVE_CHUNK_BYTES).arrayBuffer());
      await save({ kind: "chunk", id, index, base64: base64(piece) });
    }
    await save({ kind: "end", id });
  } catch (error) {
    // Native holds a half-written file until told otherwise.
    await save({ kind: "abort", id }).catch(() => {});
    throw error;
  }
}

/** Bytes this page made or already fetched. */
export async function saveBlob(blob: Blob, filename: string, revokeAfterMs = 60_000): Promise<void> {
  if (await nativeAvailable("saveFile")) return saveBlobNatively(blob, filename);
  const url = URL.createObjectURL(blob);
  try {
    clickDownload(url, filename);
  } finally {
    // Chromium may read the URL after the click task; 60 s is what every
    // call site used before this existed.
    setTimeout(() => URL.revokeObjectURL(url), revokeAfterMs);
  }
}

/** Where the bytes behind a save link live, as far as the phone app is
 * concerned. One rule for every caller (D3/D10 kept two copies of it):
 *   page      blob: or data: — bytes only this page holds; native gets nothing
 *   server    this origin's own route — native downloads it by URL
 *   external  anywhere else — never a native download of an arbitrary URL
 *             (M2); it opens in the system browser instead */
export type SaveSource = "page" | "server" | "external";

function currentOrigin(): string {
  const location = globalThis.location;
  if (location?.origin) return location.origin;
  try {
    return location?.href ? new URL(location.href).origin : "";
  } catch {
    return "";
  }
}

export function saveSource(url: string, pageOrigin: string = currentOrigin()): SaveSource {
  if (/^(?:blob|data):/i.test(url.trim())) return "page";
  try {
    return new URL(url, pageOrigin || undefined).origin === pageOrigin ? "server" : "external";
  } catch {
    return "external";
  }
}

/** `%XX` as the byte it names; everything else as its own UTF-8. */
function percentDecodedBytes(text: string): Uint8Array<ArrayBuffer> {
  const encoder = new TextEncoder();
  const out: number[] = [];
  for (let at = 0; at < text.length; ) {
    if (text[at] === "%" && /^[0-9a-f]{2}$/i.test(text.slice(at + 1, at + 3))) {
      out.push(parseInt(text.slice(at + 1, at + 3), 16));
      at += 3;
      continue;
    }
    const char = String.fromCodePoint(text.codePointAt(at)!);
    out.push(...encoder.encode(char));
    at += char.length;
  }
  return Uint8Array.from(out);
}

/** A data: URL's bytes, read here rather than through fetch(): the browser
 * door's CSP limits connect-src to 'self', and a data: URL's origin is
 * opaque, so fetching one there is refused (final review I1). */
export function dataUrlBlob(url: string): Blob {
  const damaged = () => saveError("That file link is damaged and can't be saved.", "damaged");
  const comma = url.indexOf(",");
  const header = url.slice(0, comma < 0 ? url.length : comma);
  if (comma < 0 || !/^data:/i.test(header)) throw damaged();
  const params = header.slice(5).split(";").map((part) => part.trim());
  const base64 = params.length > 1 && params[params.length - 1]!.toLowerCase() === "base64";
  if (base64) params.pop();
  const type = params[0] ? params.join(";") : "text/plain;charset=US-ASCII";
  const payload = url.slice(comma + 1);
  if (!base64) return new Blob([percentDecodedBytes(payload)], { type });
  let binary: string;
  try {
    // Base64 is ASCII, so an escaped "+" or "/" is the only escape it needs.
    binary = atob(payload.replace(/%([0-9a-f]{2})/gi, (_, hex: string) => String.fromCharCode(parseInt(hex, 16))).replace(/\s/g, ""));
  } catch {
    throw damaged();
  }
  const bytes = new Uint8Array(binary.length);
  for (let at = 0; at < binary.length; at += 1) bytes[at] = binary.charCodeAt(at);
  return new Blob([bytes], { type });
}

/** A file behind a URL: a server route, or a blob:/data: link in the page. */
export async function saveUrl(url: string, filename: string): Promise<void> {
  if (!(await nativeAvailable("saveFile"))) {
    clickDownload(url, filename);
    return;
  }
  const source = saveSource(url);
  if (source === "page") {
    // Only this page can read these; native would get nothing. A data: URL
    // is decoded here. A blob: URL has no other way back to its bytes than
    // fetch; no phone path hands one to this function today (every blob the
    // app makes goes through saveBlob first).
    if (/^data:/i.test(url.trim())) return saveBlobNatively(dataUrlBlob(url.trim()), filename);
    const response = await fetch(url);
    return saveBlobNatively(await response.blob(), filename);
  }
  const href = new URL(url, globalThis.location?.href).href;
  if (source === "external") {
    if (!(await nativeAvailable("openExternal"))) throw saveError("This file is on another site and can't be saved from here.", "elsewhere");
    await callNative("openExternal", href);
    return;
  }
  await save({ kind: "url", url: href, filename });
}

/** Raised when a save the person asked for did not happen. The store shows
 * it as the ordinary error toast (`reportSaveFailure` → StoreProvider). */
export const SAVE_FAILED_EVENT = "murage:save-failed";

export function saveFailureMessage(error: unknown): string {
  const code = (error as { code?: unknown } | null)?.code;
  if (error instanceof Error && (code === "too-large" || code === "damaged" || code === "elsewhere")) return error.message;
  return "Couldn't save that file. Try again.";
}

/** Say a failed save out loud instead of swallowing it (final review D4). */
export function reportSaveFailure(error: unknown): void {
  console.warn("murage: a save did not finish", error);
  globalThis.dispatchEvent?.(new CustomEvent(SAVE_FAILED_EVENT, { detail: { message: saveFailureMessage(error) } }));
}

export function onSaveFailed(listener: (message: string) => void): () => void {
  const handle = (event: Event) => {
    const message = (event as CustomEvent<{ message?: unknown }>).detail?.message;
    if (typeof message === "string" && message) listener(message);
  };
  globalThis.addEventListener?.(SAVE_FAILED_EVENT, handle);
  return () => globalThis.removeEventListener?.(SAVE_FAILED_EVENT, handle);
}
