// Every "save a copy" in the app, through one door.
//
// In a browser, and on the desktop, this is the a[download] click the app has
// always made — moved here from seven call sites that each spelled it out.
//
// Inside the phone app that click has nowhere to go: a blob: URL lives in the
// page's memory, and neither WKDownload nor Android's DownloadListener can
// read it. So the phone gets the file through `murageNative.saveFile`
// (spec §3.2):
//   - a file the server already serves is passed as its URL, and native
//     downloads it with the WebView's own cookie — large files never cross
//     the channel;
//   - generated bytes go in 1 MB base64 pieces, and never more than 25 MB,
//     because each piece is a string held in two processes at once.
import { callNative, nativeAvailable } from "./native-shell";

export const NATIVE_SAVE_CHUNK_BYTES = 1024 * 1024;
export const NATIVE_SAVE_MAX_BYTES = 25 * 1024 * 1024;

/** The shape `murageNative.saveFile` accepts. Plan 2's native code implements
 * exactly this; change both together. */
export type NativeSaveRequest =
  | { kind: "url"; url: string; filename: string }
  | { kind: "begin"; id: string; filename: string; mime: string; size: number }
  | { kind: "chunk"; id: string; index: number; base64: string }
  | { kind: "end"; id: string }
  | { kind: "abort"; id: string };

const save = (request: NativeSaveRequest) => callNative("saveFile", request);

/** The browser half: a temporary anchor, always removed. */
export function clickDownload(url: string, filename: string): void {
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.rel = "noopener";
  link.referrerPolicy = "no-referrer";
  try {
    document.body.appendChild(link);
    link.click();
  } finally {
    link.remove();
  }
}

function base64(bytes: Uint8Array): string {
  let binary = "";
  // String.fromCharCode with a spread overflows the stack past ~100k args.
  for (let at = 0; at < bytes.length; at += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(at, at + 0x8000));
  }
  return btoa(binary);
}

function transferId(): string {
  return globalThis.crypto?.randomUUID?.() ?? `save-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

async function saveBlobNatively(blob: Blob, filename: string): Promise<void> {
  if (blob.size > NATIVE_SAVE_MAX_BYTES) {
    throw Object.assign(
      new Error("This file is bigger than 25 MB, too big to save on this phone. Save it from Murage on your computer."),
      { code: "too-large" },
    );
  }
  const id = transferId();
  await save({ kind: "begin", id, filename, mime: blob.type || "application/octet-stream", size: blob.size });
  try {
    for (let index = 0, offset = 0; offset < blob.size; index += 1, offset += NATIVE_SAVE_CHUNK_BYTES) {
      const piece = new Uint8Array(await blob.slice(offset, offset + NATIVE_SAVE_CHUNK_BYTES).arrayBuffer());
      await save({ kind: "chunk", id, index, base64: base64(piece) });
    }
    await save({ kind: "end", id });
  } catch (error) {
    // Native holds a half-written file until told otherwise.
    await save({ kind: "abort", id }).catch(() => {});
    throw error;
  }
}

/** Bytes this page made or already fetched. */
export async function saveBlob(blob: Blob, filename: string, revokeAfterMs = 60_000): Promise<void> {
  if (await nativeAvailable("saveFile")) return saveBlobNatively(blob, filename);
  const url = URL.createObjectURL(blob);
  try {
    clickDownload(url, filename);
  } finally {
    // Chromium may read the URL after the click task; 60 s is what every
    // call site used before this existed.
    setTimeout(() => URL.revokeObjectURL(url), revokeAfterMs);
  }
}

/** A file behind a URL: a server route, or a blob:/data: link in the page. */
export async function saveUrl(url: string, filename: string): Promise<void> {
  if (!(await nativeAvailable("saveFile"))) {
    clickDownload(url, filename);
    return;
  }
  if (/^(?:blob|data):/i.test(url)) {
    // Only this page can read these; native would get nothing.
    const response = await fetch(url);
    return saveBlobNatively(await response.blob(), filename);
  }
  await save({ kind: "url", url: new URL(url, globalThis.location?.href).href, filename });
}
