// Private actual packaged-main/preload/native-dialog Q12 driver. No model sends.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,writeFileSync,realpathSync,readdirSync,lstatSync,createReadStream} from 'node:fs';
import {verifyHostdeps} from './hostdeps.mjs';
import {saveResourceSnapshot} from './resources.mjs';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {userInfo} from 'node:os';
import {executionProfile,memoryReading,assertPrestart,belowStop,privateDirectory,ownedPath,assertManifestIdentity,safeEncryptedResponse,sourceSeams} from './runtime.mjs';
import {DatabaseSync} from 'node:sqlite';
const packet=dirname(fileURLToPath(import.meta.url));
const json=file=>JSON.parse(readFileSync(file,'utf8'));
export async function sha(file){const h=createHash('sha256');for await(const b of createReadStream(file))h.update(b);return h.digest('hex');}
const plainSha=b=>createHash('sha256').update(b).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ps=()=>execFileSync('/bin/ps',['-axo','pid=,ppid=,comm='],{encoding:'utf8'}).split('\n').flatMap(line=>{const m=line.match(/^\s*(\d+)\s+(\d+)\s+(.+)$/);return m?[{pid:+m[1],parent:+m[2],command:m[3]}]:[];});
const reserve=()=>memoryReading(execFileSync('/usr/bin/vm_stat',[],{encoding:'utf8'}),execFileSync('/usr/sbin/sysctl',['-n','hw.memsize'],{encoding:'utf8'}).trim());
const frontmost=()=>JSON.parse(execFileSync('/usr/bin/osascript',['-l','JavaScript','-e','ObjC.import("AppKit");var a=$.NSWorkspace.sharedWorkspace.frontmostApplication;JSON.stringify({pid:Number(a.processIdentifier),bundle:String(ObjC.unwrap(a.bundleIdentifier)||"")});'],{encoding:'utf8'}));
async function restoreFrontmost(original){execFileSync('/usr/bin/osascript',['-l','JavaScript','-e',`ObjC.import("AppKit");var a=$.NSRunningApplication.runningApplicationWithProcessIdentifier(${original.pid});if(Number(a.processIdentifier)!==${original.pid}||String(ObjC.unwrap(a.bundleIdentifier)||"")!==${JSON.stringify(original.bundle)})throw Error("Original foreground identity unavailable");a.activateWithOptions(2);`]);const end=Date.now()+10000;while(Date.now()<end){if(JSON.stringify(frontmost())===JSON.stringify(original))return;await sleep(200);}throw Error('Foreground restoration failed');}
export function assertPaused(snapshot){assert.equal(snapshot.meta.mode,'paused');assert.equal(snapshot.delivered,0);assert.equal(snapshot.leased,0);assert(snapshot.engines.every(e=>e.enabled===false));assert(snapshot.routines.every(r=>r.enabled===false));assert(snapshot.runs.every(r=>!['queued','running','waiting'].includes(r.status)));assert(snapshot.webhooks.every(w=>w.enabled===false));assert.equal(snapshot.optimizerRunning,0);for(const bot of snapshot.bots){assert.equal(bot.busy,false);assert.equal(bot.autoApprove,false);assert.deepEqual(bot.resumeCursors,{});for(const task of bot.tasks??[]){assert.equal(task.autoApprove,false);assert.deepEqual(task.alwaysAllow,[]);assert.deepEqual(task.resumeCursors,{});}}for(const group of snapshot.groups){assert.equal(group.working,false);assert.equal(group.busyBotId,null);}}
export function snapshot(data,ids){const db=new DatabaseSync(join(data,'messages.db'),{readOnly:true});try{return{meta:db.prepare('SELECT * FROM memory_meta').get(),source:db.prepare('SELECT id,revision,state,content_hash FROM memory_sources WHERE id=?').get(ids.source),records:db.prepare('SELECT id,version,state,owner_pinned,text FROM memory_records WHERE id IN (?,?) ORDER BY id,version').all(ids.record,ids.derived),tombstones:db.prepare('SELECT * FROM memory_tombstones ORDER BY id').all(),delivered:db.prepare("SELECT count(*) AS n FROM memory_disclosures WHERE state='delivered'").get().n,leased:db.prepare("SELECT count(*) AS n FROM memory_jobs WHERE status='leased'").get().n,optimizerRunning:db.prepare("SELECT count(*) AS n FROM memory_scope_bindings WHERE subject_type='system' AND subject_id='procedure-review-pending' AND json_extract(intent,'$.status')='running'").get().n,bots:json(join(data,'bots.json')),groups:json(join(data,'groups.json')),engines:Object.values(json(join(data,'config.json')).instances??{}),routines:existsSync(join(data,'routines.json'))?(json(join(data,'routines.json')).routines??[]):[],runs:existsSync(join(data,'routines.json'))?(json(join(data,'routines.json')).runs??[]):[],webhooks:existsSync(join(data,'webhooks.json'))?(json(join(data,'webhooks.json')).webhooks??[]):[]};}finally{db.close();}}
export function assertProfileRoute(requestedRoot,expectedRoot,selection){
 assert.equal(selection.dataDirectory,expectedRoot,'Selected installation does not match this phase');
 if(expectedRoot===requestedRoot)assert.equal(selection.selected,false,'Original phase must not silently use a restored selection');
 else {assert.equal(selection.selected,true,'Restored phase requires the actual published selection');assert.equal(selection.originalRoot,requestedRoot,'Restored selection belongs to another original');}
 return {requestedRoot,activeRoot:selection.dataDirectory,selected:selection.selected};
}
function memoryIdentity(data){const db=new DatabaseSync(join(data,'messages.db'),{readOnly:true});try{return db.prepare('SELECT installation_id,mode,policy_revision,deletion_epoch FROM memory_meta').get();}finally{db.close();}}
export async function main(manifestFile){
 const m=json(manifestFile);assert.equal(m.rootApproved,true,'Root admission required before native launch');assert.equal(process.platform,'darwin');assert.equal(process.arch,'arm64');
 assertManifestIdentity(m,{sourceCommit:process.env.ARTIFACT_SOURCE_SHA,fixtureCommit:process.env.FIXTURE_SOURCE_SHA,fuigoVersion:process.env.FUIGO_VERSION});
 const operator=userInfo(),profile=executionProfile(m.executionProfile,{platform:process.platform,arch:process.arch,username:operator.username,home:operator.homedir,env:process.env,manager:execFileSync('/bin/launchctl',['managername'],{encoding:'utf8'}).trim()});
 const repo=realpathSync(resolve(packet,'../..')),sourceRoot=realpathSync(m.sourceRoot),taskRoot=privateDirectory(m.taskRoot);
 if(profile.name==='DISPOSABLE_GITHUB_MAC'){assert.equal(repo,realpathSync(process.env.GITHUB_WORKSPACE));assert.equal(sourceRoot,join(repo,'.q12-source'));assert.equal(taskRoot,join(realpathSync(process.env.RUNNER_TEMP),'murage-q12'));}
 assert.equal(execFileSync('/usr/bin/git',['-C',repo,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),m.fixtureCommit);
 assert.equal(execFileSync('/usr/bin/git',['-C',sourceRoot,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),m.sourceCommit);
 assert.deepEqual(Object.keys(m.sourcePins).sort(),[...sourceSeams].sort());
 const {require}=verifyHostdeps(join(taskRoot,'hostdeps')),{resolveInstallationSelection}=await import(pathToFileURL(join(sourceRoot,'electron/installation-selection.mjs')).href);
 const app=ownedPath(taskRoot,m.app),exe=join(app,'Contents/MacOS/Murage'),out=ownedPath(taskRoot,m.out,{absent:true});
 ownedPath(taskRoot,m.keygen.path);assert.equal(await sha(fileURLToPath(import.meta.url)),m.driverSha256,'Prepared driver changed');
 for(const [file,hash] of Object.entries(m.appHashes))assert.equal(await sha(join(app,file)),hash);
 for(const [file,hash] of Object.entries(m.sourcePins))assert.equal(await sha(join(sourceRoot,file)),hash,'Prepared public seam source changed');
 assert.equal(await sha(m.keygen.path),m.keygen.sha256);assert.equal(await sha(join(packet,'native-picker.jxa')),m.pickerSha256);
 execFileSync('/usr/bin/codesign',['--verify','--deep','--strict',app],{stdio:'pipe'});assert(!ps().some(p=>p.command.startsWith(app+'/')),'Task app already running');const admittedMemory=profile.name==='DISPOSABLE_GITHUB_MAC'?saveResourceSnapshot(taskRoot,'before-app-launch').reading:reserve();assertPrestart(profile,admittedMemory);
 const trusted=execFileSync('/usr/bin/osascript',['-l','JavaScript','-e','ObjC.import("ApplicationServices");String(Boolean($.AXIsProcessTrusted()));'],{encoding:'utf8'}).trim();assert.equal(trusted,'true','Native AX client must already be trusted');
 const {_electron}=require('@playwright/test'),beforeProcesses=ps(),originalFront=frontmost();const protectedRoot=join(operator.homedir,'.murage');
 const protectedHashes=async()=>Object.fromEntries(await Promise.all(['config.json','bots.json','groups.json'].filter(n=>existsSync(join(protectedRoot,n))).map(async n=>[n,await sha(join(protectedRoot,n))])));const protectedBefore=await protectedHashes();
 mkdirSync(out,{mode:0o700});const data=join(out,'original'),home=join(out,'home'),userData=join(out,'userData'),tmp=join(out,'tmp'),archives=join(out,'archives'),keys=join(out,'keys');for(const d of [data,home,userData,tmp,archives,keys])mkdirSync(d,{mode:0o700});
 const env={PATH:'/usr/bin:/bin:/usr/sbin:/sbin',HOME:home,USERPROFILE:home,TMPDIR:tmp,TMP:tmp,TEMP:tmp,XDG_CONFIG_HOME:join(home,'config'),XDG_CACHE_HOME:join(home,'cache'),XDG_DATA_HOME:join(home,'data'),MURAGE_DATA_DIR:data,MURAGE_USER_DATA:userData,HF_HUB_OFFLINE:'1',TRANSFORMERS_OFFLINE:'1',LANG:'en_US.UTF-8'};
 writeFileSync(join(data,'config.json'),JSON.stringify({engineDiscovery:'explicit',instances:{},profile:{name:'Q12 synthetic owner'}}),{mode:0o600});writeFileSync(join(data,'bots.json'),'[]',{mode:0o600});writeFileSync(join(data,'groups.json'),'[]',{mode:0o600});writeFileSync(join(userData,'companion-settings.json'),JSON.stringify({enabled:false,remoteAccess:false,keepAwake:false}),{mode:0o600});
 const key=execFileSync(m.keygen.path,[],{env,cwd:keys,encoding:'utf8',maxBuffer:4096,timeout:10000});assert(/^# public key: age1/m.test(key));const keyFile=join(keys,'independent-age-key');writeFileSync(keyFile,key,{mode:0o600,flag:'wx'});
 const receipt={status:'RUNNING',sourceCommit:m.sourceCommit,fixtureCommit:m.fixtureCommit,fuigoVersion:m.fuigoVersion,resourceProfile:profile,admittedMemory,minimumReserveBytes:admittedMemory.reserveBytes,app,checks:[],providerMessagesSent:0,fullQ12Accepted:false};const save=()=>writeFileSync(join(out,'RESULT.json'),JSON.stringify(receipt,null,2)+'\n',{mode:0o600});const record=(phase,value)=>{receipt.checks.push({phase,at:Date.now(),...value});save();};save();
 let session,stopReason;const owned=new Map(),deadline=Date.now()+profile.windowMs;
 const inventory=()=>{const rows=ps();for(const p of rows)if(p.command.startsWith(app+'/'))owned.set(p.pid,p);return rows.filter(p=>p.command.startsWith(app+'/'));};
 const until=async(fn,ms,label)=>{const end=Math.min(deadline,Date.now()+ms);while(Date.now()<end){if(stopReason)throw Error(stopReason);const value=await fn();if(value)return value;await sleep(200);}throw Error(label+' deadline; no retry');};
 const ax=command=>{const text=execFileSync('/usr/bin/osascript',['-l','JavaScript',join(packet,'native-picker.jxa'),JSON.stringify(command)],{encoding:'utf8',timeout:20000});return JSON.parse(text);};
 const nativePress=async(pid,label,sheet=true)=>{await until(()=>{const r=ax({op:'count',pid,roles:['AXButton'],label,sheet});return r.ok&&r.count===1;},30000,'native confirmation '+label);const r=ax({op:'press',pid,roles:['AXButton'],label,sheet,requireEnabled:true});record('native-confirmation',{pid,label,result:r});assert(r.ok);};
 const choose=(pid,path,actionButton='Open')=>{assert(path.startsWith(out+'/'));const r=ax({op:'pickPath',pid,path,actionButton});record('native-picker',{pid,path,actionButton,result:r});assert(r.ok);};
 const close=async()=>{if(session){const current=session;session=null;let timer;try{await Promise.race([current.application.close(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('App close deadline')),20000);})]);}finally{clearTimeout(timer);}}await until(()=>inventory().length===0,60000,'owned app close');};
 const stop=()=>{stopReason??='Supervisor stop';if(session)void session.application.close().catch(()=>{});};process.once('SIGTERM',stop);process.once('SIGINT',stop);
 const monitor=setInterval(()=>{try{const reading=reserve();receipt.minimumReserveBytes=Math.min(receipt.minimumReserveBytes,reading.reserveBytes);if(belowStop(profile,reading)){receipt.stopMemory=reading;stopReason='Host reserve below '+profile.name+' stop threshold';}if(Date.now()>=deadline)stopReason='30-minute window exhausted';if(stopReason)stop();inventory();}catch{stopReason='Memory/ownership measurement failed';stop();}},profile.monitorMs);
 const launch=async(mode,expectedData=data)=>{
  const route=assertProfileRoute(data,expectedData,resolveInstallationSelection(userData,data));const launchMemory=reserve();assertPrestart(profile,launchMemory);record('launch-resource-admission',{profile:profile.name,...launchMemory});
  // Keep the original requested root: main resolves its published selection and sends the selected root to its utility server.
  const application=await _electron.launch({executablePath:exe,args:[`--user-data-dir=${userData}`,...(mode==='backup'?['--murage-backup-mode']:[])],cwd:out,env,timeout:60000});const pid=application.process().pid;session={application,pid,expectedData};inventory();
  const identity=await application.evaluate(({app})=>({packaged:app.isPackaged,appPath:app.getAppPath(),userData:app.getPath('userData'),requestedData:process.env.MURAGE_DATA_DIR,pid:process.pid,lock:app.hasSingleInstanceLock(),logs:app.getPath('logs'),sessionData:app.getPath('sessionData'),publicArguments:process.argv.filter(a=>a==='--murage-backup-mode'||a.startsWith('--user-data-dir='))}));
  assert(identity.packaged&&identity.lock);assert.equal(identity.appPath,join(app,'Contents/Resources/app.asar'));assert.equal(identity.userData,userData);assert.equal(identity.requestedData,data);assert.equal(identity.pid,pid);assert(identity.logs.startsWith(out+'/')&&identity.sessionData.startsWith(out+'/'));assert(identity.publicArguments.includes(`--user-data-dir=${userData}`));
  const page=await application.firstWindow();session.page=page;await page.waitForFunction(()=>Boolean(window.muragebox?.desktopSurfaceSecret||window.murageRecovery),undefined,{timeout:60000});const normal=await page.evaluate(()=>Boolean(window.muragebox?.desktopSurfaceSecret));
  if(normal){
   await page.waitForFunction(()=>document.body.textContent.includes('Murage hit an error and stopped drawing')||Boolean(document.querySelector('[aria-label="Bots and navigation"]')&&document.querySelector('main')),undefined,{timeout:10000});assert.equal(await page.getByText('Murage hit an error and stopped drawing',{exact:true}).isVisible(),false);assert(await page.getByRole('complementary',{name:'Bots and navigation',exact:true}).isVisible());assert(await page.getByRole('main').isVisible());
   const served=await page.evaluate(async()=>{const r=await fetch('/api/memory/status',{headers:{'x-murage-surface':'desktop','x-murage-surface-secret':window.muragebox.desktopSurfaceSecret}});if(!r.ok)throw Error('Owner identity read refused');return r.json();}),expected=memoryIdentity(expectedData);
   assert.equal(served.installationId,expected.installation_id);assert.equal(served.mode,expected.mode);assert.equal(served.deletionEpoch,expected.deletion_epoch);identity.servedMemory={installationId:served.installationId,mode:served.mode,deletionEpoch:served.deletionEpoch};
  }else{const state=await page.evaluate(()=>window.murageRecovery.action('state'));assert.equal(state.context.dataDirectory,expectedData,'Actual recovery window owns wrong installation');identity.recoveryData=state.context.dataDirectory;}
  assertProfileRoute(data,expectedData,resolveInstallationSelection(userData,data));record('actual-packaged-main-preload',{mode,identity,route,normalRendererHealthy:normal});return session;
 };
 const api=async(path,method='GET',body)=>session.page.evaluate(async({path,method,body})=>{const proof=window.muragebox?.desktopSurfaceSecret;if(!proof)throw Error('Actual owner preload absent');const r=await fetch(path,{method,headers:{'content-type':'application/json','x-murage-surface':'desktop','x-murage-surface-secret':proof},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error('Owner API '+path+' HTTP '+r.status);return r.json();},{path,method,body});
 const beginRecovery=(action,id)=>session.page.evaluate(({action,id})=>window.murageRecovery.action(action,id),{action,id}).then(value=>({value}),error=>({connectionClosed:true,errorName:error.name}));
 const recoveryState=()=>session.page.evaluate(()=>window.murageRecovery.action('state'));
 const reconnectAfterActualRestart=async(old,reason,mode,expectedData=data)=>{await until(()=>!ps().some(p=>p.pid===old.pid&&p.command===exe),60000,'old app restart exit');const next=await until(()=>inventory().find(p=>p.command===exe&&p.pid!==old.pid),60000,'actual app relaunch');const observed=await until(()=>{const r=ax({op:'texts',pid:next.pid,pattern:reason});return r.ok&&r.texts.length?r:null;},60000,'relaunch surface');assertProfileRoute(data,expectedData,resolveInstallationSelection(userData,data));record('actual-public-restart',{oldPid:old.pid,newPid:next.pid,reason,observed,requestedRoot:data,expectedActiveRoot:expectedData});session=null;await old.application.close().catch(()=>{});assert(ax({op:'quit',pid:next.pid}).ok);await until(()=>inventory().length===0,60000,'observed restart closed for Playwright reattachment');return launch(mode,expectedData);};
 const backupMode=async()=>{const old=session;const ready=await old.page.evaluate(()=>window.muragebox.backup.status());assert(ready.supported);const promise=old.page.evaluate(()=>window.muragebox.backup.restart()).then(value=>({value}),error=>({connectionClosed:true,errorName:error.name}));await nativePress(old.pid,'Restart into Backup mode');await reconnectAfterActualRestart(old,'Backup mode was opened deliberately','backup');record('backup-entry-bridge',{result:await promise});const state=await recoveryState();assert(state.context.backupMode&&state.context.dataDirectory===data&&state.encryptedAvailable);};
 let ids,archiveSha,originalAfterForget,target;
 try{
  await launch('normal');const status=await api('/api/memory/status');const configured=await api('/api/memory/action','POST',{action:'configure',learning:{callsPerMinute:0},learningRevision:status.learning.revision});assert.equal(configured.learning.callsPerMinute,0);assert.equal(configured.cost.callsThisMinute,0);assert.equal(configured.configuration.extractorInstanceId,null);
  const bot=(await api('/api/bots','POST',{name:'Q12 owner bot'})).bot,other=(await api('/api/bots','POST',{name:'Q12 other bot'})).bot;const room=(await api('/api/groups','POST',{name:'Q12 shared audience',memberIds:[bot.id,other.id],setup:{bulletin:'Synthetic fixture only',defaultResponder:{kind:'mentions'}}})).group;
  ids={source:'q12-synthetic-source',record:'q12-synthetic-pin',derived:'pending'};const text='Q12_CORAL synthetic launch note: reviewed handover on Thursday.';const db=new DatabaseSync(join(data,'messages.db'));try{db.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);assert.equal(db.prepare('SELECT count(*) AS n FROM memory_sources WHERE id=?').get(ids.source).n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM memory_records WHERE id=?').get(ids.record).n,0);db.exec('BEGIN IMMEDIATE');const scope=db.prepare("SELECT id FROM memory_scopes WHERE kind='bot' AND owner_key=?").get(bot.id).id,payload=JSON.stringify({text,kind:'text',speaker:'owner',outcome:'recorded'});db.prepare("INSERT INTO memory_sources(id,scope_id,thread_id,message_id,revision,content_hash,kind,speaker,outcome,state) VALUES(?,?,?,?,1,?,'text','owner','recorded','active')").run(ids.source,scope,bot.threadId,'q12-fixture-message',plainSha(payload));db.prepare('INSERT INTO memory_source_versions VALUES(?,1,?,?,1)').run(ids.source,plainSha(payload),payload);db.prepare("INSERT INTO memory_records VALUES(?,1,?,'fact',?,'owner-statement','active',1,1,NULL,NULL,1)").run(ids.record,scope,text);db.prepare('INSERT INTO memory_evidence VALUES(?,1,?,1,0,?)').run(ids.record,ids.source,Buffer.byteLength(text));db.exec('UPDATE memory_meta SET data_revision=data_revision+1; COMMIT');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{db.close();}
  const inspect=await api('/api/memory/action','POST',{action:'inspect',id:ids.record,version:1});assert.equal(inspect.record.text,text);
  const ro=new DatabaseSync(join(data,'messages.db'),{readOnly:true});let roomScope;try{roomScope=ro.prepare("SELECT id FROM memory_scopes WHERE kind='room' AND owner_key=?").get(room.id).id;}finally{ro.close();}
  const promoted=await api('/api/memory/action','POST',{action:'promote',id:ids.record,version:1,scopeId:roomScope});ids.derived=promoted.record?.id;assert(typeof ids.derived==='string'&&ids.derived!==ids.record);const seeded=snapshot(data,ids);assert.equal(seeded.records.length,2);assert(seeded.records.every(r=>r.state==='active'));record('source-pin-owner-shared-derivative',{ids,seeded});
  // Canonical Store load supplies explicit idle booleans required by backupActivityBusy.
  await close();await launch('normal');const activity=await api('/api/bots?messages=0');assert(activity.bots.every(b=>b.busy===false)&&activity.groups.every(g=>g.working===false));
  await backupMode();const archive=join(archives,'murage-application-backup.age');assert(!existsSync(archive),'Never overwrite an archive');const pending=beginRecovery('backup-encrypted');choose(session.pid,archives,'Save');choose(session.pid,keyFile);await nativePress(session.pid,'Create encrypted backup');const reply=await pending,created=reply.value;record('actual-encrypted-backup-response',safeEncryptedResponse(reply));assert(created&&!created.error&&created.result?.operation==='backup-encrypted');assert.equal(created.result.path,archive);archiveSha=await sha(archive);assert.equal(created.result.sha256,archiveSha);record('actual-encrypted-backup-before-forget',{result:created.result,archiveSha});
  await close();await launch('normal');const beforeForget=snapshot(data,ids);assert.equal(beforeForget.source.state,'active');assert(beforeForget.records.length===2&&beforeForget.records.every(r=>r.state==='active'));assert.equal(await sha(archive),archiveSha);await api('/api/memory/action','POST',{action:'forget',kind:'source',id:ids.source});const forgotten=snapshot(data,ids);assert.equal(forgotten.source.state,'deleted');assert(forgotten.records.every(r=>r.state==='deleted'));assert(forgotten.tombstones.some(t=>t.target_type==='source'&&t.target_id===ids.source));record('actual-owner-forget',{forgotten});
  await backupMode();originalAfterForget=snapshot(data,ids);const inspectPending=beginRecovery('choose-encrypted-backup');choose(session.pid,archive);choose(session.pid,keyFile);const selected=(await inspectPending).value;assert(selected&&!selected.error&&selected.selection.encrypted&&selected.selection.sha256===archiveSha);target=selected.selection.destination;assert(target.startsWith(userData+'/recovered-installations/')&&!existsSync(target));record('actual-encrypted-inspection',{selection:selected.selection});
  const currentSelection=await recoveryState();assert.equal(currentSelection.context.dataDirectory,data);assert.equal(currentSelection.selection.id,selected.selection.id);assert.equal(currentSelection.selection.destination,target);assert.equal(currentSelection.selection.sha256,archiveSha);assert(!existsSync(target));const beforeRestore=session,restoring=beginRecovery('restore-encrypted-new',selected.selection.id);await nativePress(beforeRestore.pid,'Restore separately and restart for review');await reconnectAfterActualRestart(beforeRestore,'This restored installation is paused for recovery review','normal',target);await restoring;const reviewState=await recoveryState();assert.equal(reviewState.context.dataDirectory,target);const beforeReview=snapshot(target,ids);assertPaused(beforeReview);assert.equal(json(join(target,'restore-review.json')).status,'review-required');assert.deepEqual(snapshot(data,ids),originalAfterForget);assert.equal(await sha(archive),archiveSha);await session.page.screenshot({path:join(out,'restored-review-required.png'),fullPage:true});record('actual-restored-startup-fence',{target,state:reviewState.context,snapshot:beforeReview,originalDeletionPreserved:true});
  const review=(await beginRecovery('review-installation')).value;assert(review&&!review.error&&review.review?.id);const currentReview=await recoveryState();assert.equal(currentReview.context.dataDirectory,target);assert.equal(currentReview.review.id,review.review.id);assertPaused(snapshot(target,ids));const beforeActivation=session,activating=beginRecovery('activate',review.review.id);await nativePress(beforeActivation.pid,'Open reviewed installation');await reconnectAfterActualRestart(beforeActivation,'Q12 owner bot','normal',target);await activating;const afterStatus=await api('/api/memory/status');assert.equal(afterStatus.mode,'paused');const afterReview=snapshot(target,ids);assertPaused(afterReview);assert.equal(json(join(target,'restore-review.json')).status,'reviewed');
  const ownerReview=await api('/api/memory/action','POST',{action:'list',query:'Q12_CORAL',state:'active'});await sleep(5000);assertPaused(snapshot(target,ids));assert.deepEqual(snapshot(data,ids),originalAfterForget);assert.equal(await sha(archive),archiveSha);await session.page.screenshot({path:join(out,'reviewed-paused.png'),fullPage:true});record('reviewed-still-paused',{status:afterStatus,snapshot:afterReview,ownerVisibleOldRecordCount:ownerReview.records?.length??null,limitation:'Paused fences do not prove post-backup tombstones migrated into separate restore or absence after explicit memory re-enable. No re-enable performed.'});
  receipt.status='SCOPED_ENCRYPTED_RESTORE_FENCES_VERIFIED_Q12_GRADING_REQUIRED';receipt.fullQ12Accepted=false;
 }catch(error){receipt.status='FAIL';receipt.error=String(error);try{if(session?.page)await session.page.screenshot({path:join(out,'failure.png'),fullPage:true});}catch{}throw error;}
 finally{
  clearInterval(monitor);process.removeListener('SIGTERM',stop);process.removeListener('SIGINT',stop);
  try{await close();}catch(error){receipt.closeError=String(error);}
  for(const row of inventory()){const current=ps().find(p=>p.pid===row.pid&&p.command===row.command);if(current)try{process.kill(row.pid,'SIGTERM');}catch{}}
  const end=Date.now()+20000;while(inventory().length&&Date.now()<end)await sleep(200);for(const row of inventory()){const current=ps().find(p=>p.pid===row.pid&&p.command===row.command);if(current&&owned.get(row.pid)?.command===current.command)try{process.kill(row.pid,'SIGKILL');}catch{}}await sleep(200);const left=inventory();receipt.ownedProcessesGone=left.length===0;
  receipt.protectedProfileUnchanged=JSON.stringify(await protectedHashes())===JSON.stringify(protectedBefore);const now=ps();receipt.originalMurageProcessesPreserved=beforeProcesses.filter(p=>/\/Contents\/MacOS\/Murage$/.test(p.command)).every(p=>now.some(q=>q.pid===p.pid&&q.command===p.command));
  try{await restoreFrontmost(originalFront);receipt.foregroundRestored=true;}catch(error){receipt.foregroundRestored=false;receipt.foregroundError=String(error);}
  if(!receipt.ownedProcessesGone||!receipt.protectedProfileUnchanged||!receipt.originalMurageProcessesPreserved||!receipt.foregroundRestored)receipt.status='FAIL_CLEANUP';receipt.retained={out,data,userData,keyFile,target};save();assert.notEqual(receipt.status,'FAIL_CLEANUP');
 }
 return receipt;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){assert.equal(process.argv[2],'--manifest');main(process.argv[3]).then(r=>console.log(JSON.stringify({status:r.status,fullQ12Accepted:r.fullQ12Accepted}))).catch(e=>{console.error(String(e));process.exitCode=1;});}
