// SPDX-License-Identifier: AGPL-3.0-or-later
// English copy used by the T30A mocks. Real strings will come from T09's locale pack; this is the
// spec section 4 and 9 wording behind clear key names. No em dashes, no price talk, no safety words.
export const COPY = {
  working: 'Dax is working',
  workingOnPage: 'Dax is working on this page',
  step: 'Filling in the booking form',
  pause: 'Pause',
  stop: 'Stop',
  yourTurn: 'Your turn',
  yourTurnPill: 'Your turn: Dax is waiting for you',
  yourTurnBody: 'Sign in to shop.example.com, then press Continue. Dax does not do this step for you.',
  continue: 'Continue',
  stopTask: 'Stop task',
  done: 'Dax is done',
  doneBody: 'Finished 6 steps on shop.example.com.',
  dismiss: 'Dismiss',
  full: 'Full permissive',
  idle: 'Dax is ready',
  idleBody: 'Start a browser task in Murage and it shows up here.',
  title: 'Murage',
  titleSuffix: 'for Chrome',
  connected: 'Connected',
  connectedLine: 'Connected to Murage',
  approvalMode: 'Approval mode',
  modes: ['Ask each step', 'Ask once per task', 'Full permissive'],
  modeHints: [
    'Dax asks before each action that changes a site.',
    'One card per site, then Dax works through the task.',
    'No cards for ordinary actions. Anything only you can do still comes back to you.',
  ],
  taskAccess: 'Task access',
  revoke: 'Revoke',
  noAccess: 'No access granted yet.',
  accessEnded: 'Access ended with the task.',
  levelRead: 'Read and click',
  levelFill: 'Fill in forms',
  activity: 'Activity',
  allowAlways: 'Allow shop.example.com always?',
  allowAlwaysYes: 'Allow always',
  notNow: 'Not now',
  profile: 'Chrome profile: Sean',
  activityItems: {
    working: [['12:06', 'Typing the guest name'], ['12:05', 'Opened the booking form'], ['12:05', 'Read the product list'], ['12:04', 'Started the task']],
    waiting: [['12:08', 'Stopped at the sign-in form'], ['12:07', 'Opened shop.example.com'], ['12:07', 'Started the task']],
    done: [['12:11', 'Finished the task'], ['12:10', 'Submitted the booking after your approval'], ['12:09', 'Typed the guest name'], ['12:08', 'Opened the booking form']],
    idle: [['11:52', 'Finished the last task']],
  },
};
