import { mkdirSync,rmSync } from "node:fs";
import { beforeEach,expect,it,vi } from "vitest";
import { DATA_DIR } from "./config.ts";
import { closeDatabase } from "./database.ts";
import { Store } from "./store.ts";
import { accessOwnerView,assertConnectedAppCall,requestBotAccess,reviewBotAccess,restrictedConnectorTools } from "./bot-access.ts";
import { botAccessPolicy } from "./bot-access-role.ts";
import { permissionStatus } from "./permission-status.ts";
beforeEach(()=>{closeDatabase();rmSync(DATA_DIR,{recursive:true,force:true});mkdirSync(DATA_DIR,{recursive:true});});
const account={toolkit:"gmail",accountId:"ca_fixture_owned"};
const grant={...account,tools:["GMAIL_SEND_EMAIL","GMAIL_FETCH_EMAILS"]};
function setup(){const store=new Store(()=>({instanceId:"fixture",model:"fixture"}));const chief=store.createBot({name:"Chief",section:"Leadership"});const lead=store.createBot({name:"Lead",section:"Studio"});const bot=store.createBot({name:"Specialist",section:"Studio"});const other=store.createBot({name:"Other",section:"Elsewhere"});store.setChiefOfStaff(chief.id,undefined,"workspace");store.setChiefOfStaff(lead.id,undefined,"section");store.patchBot(bot.id,{composio:false});return{store,chief,lead,bot,other};}
function call(tool="GMAIL_SEND_EMAIL",selected="ca_fixture_owned",args:object={to:"fake@example.invalid",body:"fixture"}){return{jsonrpc:"2.0",id:1,method:"tools/call",params:{name:"COMPOSIO_MULTI_EXECUTE_TOOL",arguments:{tools:[{tool_slug:tool,account:selected,arguments:args}],sync_response_to_workbench:false}}};}
function enable(f:ReturnType<typeof setup>,writes=true){const request=requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:botAccessPolicy(f.bot).revision,grants:[grant],allowWrites:writes});return reviewBotAccess(f.store,f.bot.id,{action:"approve",requestId:request.requestId,revision:request.revision},[account]);}
it("queues a durable bundle without self-granting or enabling apps",()=>{const f=setup();const response=requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:0,grants:[grant],allowWrites:true});expect(response.status).toBe("Waiting for owner review");expect(f.bot.composio).toBe(false);expect(()=>assertConnectedAppCall(f.bot,call())).toThrow("disabled");const restored=new Store(()=>f.bot.modelSelection);expect(botAccessPolicy(restored.bot(f.bot.id)!).requests).toHaveLength(1);});
it("rejects spoofed grants and cross-team manager requests",()=>{const f=setup();expect(()=>requestBotAccess(f.store,f.bot,{botId:f.bot.id,revision:0,grants:[grant]})).toThrow("responsible manager");expect(()=>requestBotAccess(f.store,f.lead,{botId:f.other.id,revision:0,grants:[grant]})).toThrow("responsible manager");expect(()=>requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:0,grants:[grant],approve:true})).toThrow("Invalid");});
it("rejects stale owner decisions and non-owned accounts",()=>{const f=setup();const request=requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:0,grants:[grant]});expect(()=>reviewBotAccess(f.store,f.bot.id,{action:"approve",requestId:request.requestId,revision:0},[account])).toThrow("changed");expect(()=>reviewBotAccess(f.store,f.bot.id,{action:"approve",requestId:request.requestId,revision:request.revision},[])).toThrow("no longer connected");expect(f.bot.composio).toBe(false);});
it("allows an explicitly owner-approved fake write only after the policy gate",async()=>{const f=setup();enable(f);const relay=vi.fn(async(_request:unknown)=>({ok:true}));assertConnectedAppCall(f.bot,call());await relay(call());expect(relay).toHaveBeenCalledOnce();expect(f.bot.composio).toBe(true);expect(botAccessPolicy(f.bot).mode).toBe("restricted");});
it("applies write restrictions even with autoapproval enabled",()=>{const f=setup();enable(f,false);f.store.patchBot(f.bot.id,{autoApprove:true,alwaysAllow:["COMPOSIO_MULTI_EXECUTE_TOOL"]});expect(()=>assertConnectedAppCall(f.bot,call())).toThrow("blocked connected-app writes");expect(()=>assertConnectedAppCall(f.bot,call("GMAIL_FETCH_EMAILS","ca_fixture_owned",{user_id:"me"}))).not.toThrow();});
it("rejects another account, missing account, alias and credential overrides",()=>{const f=setup();enable(f);for(const id of ["ca_other","Work",""])expect(()=>assertConnectedAppCall(f.bot,call("GMAIL_SEND_EMAIL",id))).toThrow("not been approved");expect(()=>assertConnectedAppCall(f.bot,call("GMAIL_FETCH_EMAILS","ca_fixture_owned",{user_id:"other@example.invalid"}))).toThrow("override");expect(()=>assertConnectedAppCall(f.bot,call("GMAIL_SEND_EMAIL","ca_fixture_owned",{nested:{custom_auth_params:{key:"fake"}}}))).toThrow("override");});
it("fails closed for unknown and dynamic execution, batch smuggling and workbench",()=>{const f=setup();enable(f);expect(()=>assertConnectedAppCall(f.bot,call("GMAIL_UNKNOWN"))).toThrow("not supported");for(const name of ["COMPOSIO_REMOTE_WORKBENCH","COMPOSIO_SEARCH_TOOLS","COMPOSIO_PROXY_EXECUTE"])expect(()=>assertConnectedAppCall(f.bot,{method:"tools/call",params:{name,arguments:{}}})).toThrow("Dynamic");expect(()=>assertConnectedAppCall(f.bot,[call()])).toThrow("one explicit");const batch=call();batch.params.arguments.tools.push({tool_slug:"GMAIL_SEND_EMAIL",account:"ca_other",arguments:{}} as any);expect(()=>assertConnectedAppCall(f.bot,batch)).toThrow("not been approved");const offload=call();offload.params.arguments.sync_response_to_workbench=true;expect(()=>assertConnectedAppCall(f.bot,offload)).toThrow("Workbench");});
it("revokes grants durably on role change even when the original role returns",()=>{const f=setup();enable(f);f.store.patchBot(f.bot.id,{title:"Different role"});f.store.patchBot(f.bot.id,{title:""});expect(botAccessPolicy(f.bot).grants).toEqual([]);const restored=new Store(()=>f.bot.modelSelection);expect(()=>assertConnectedAppCall(restored.bot(f.bot.id)!,call())).toThrow("blocked connected-app writes");});
it("revokes grants on team moves and disabling apps",()=>{const f=setup();enable(f);f.store.setBotsSection([f.bot.id],"Other");f.store.setBotsSection([f.bot.id],"Studio");expect(botAccessPolicy(f.bot).grants).toEqual([]);enable(f);f.store.patchBot(f.bot.id,{composio:false});f.store.patchBot(f.bot.id,{composio:true});expect(()=>assertConnectedAppCall(f.bot,call())).toThrow("blocked connected-app writes");});
it("rejects pending approvals after manager role changes",()=>{const f=setup();const request=requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:0,grants:[grant]});f.store.setChiefOfStaff(null,"Studio");expect(()=>reviewBotAccess(f.store,f.bot.id,{action:"approve",requestId:request.requestId,revision:request.revision},[account])).toThrow("stale");expect(permissionStatus(f.store,f.chief,f.bot.id,[]).pending[0]?.blockedReason).toBe("Access request is stale");});
it("owner revocation changes revision and immediately fences the next dispatch",()=>{const f=setup();enable(f);const before=accessOwnerView(f.bot);reviewBotAccess(f.store,f.bot.id,{action:"configure",revision:before.policy.revision,mode:"restricted",allowWrites:false,grants:[]},[]);expect(()=>assertConnectedAppCall(f.bot,call())).toThrow("blocked connected-app writes");expect(()=>reviewBotAccess(f.store,f.bot.id,{action:"configure",revision:before.policy.revision,mode:"unrestricted",allowWrites:true,grants:[]},[])).toThrow("changed");});
it("manager status strips commands, secrets, IDs and approval rights",()=>{const f=setup();const pending=[{kind:"tool" as const,createdAt:1000,command:"SECRET COMMAND",requestId:"SECRET_ID",token:"SECRET_TOKEN"}];const result=permissionStatus(f.store,f.lead,f.bot.id,pending,61000);expect(result.pending).toEqual([{kind:"tool",ageSeconds:60,blockedReason:"Waiting for owner review"}]);expect(result.canApprove).toBe(false);expect(JSON.stringify(result)).not.toContain("SECRET");expect(()=>permissionStatus(f.store,f.lead,f.other.id,pending)).toThrow("not visible");});
it("preserves unconfigured existing access and fails closed on corrupted policy",()=>{const f=setup();expect(()=>assertConnectedAppCall(f.other,{method:"arbitrary-legacy-method"})).not.toThrow();f.other.connectedAppAccess={invalid:true} as any;expect(()=>assertConnectedAppCall(f.other,call())).toThrow("blocked connected-app writes");});
it("restricted tool listing exposes only approved concrete accounts and actions",()=>{const f=setup();enable(f,false);const result=restrictedConnectorTools(f.bot,7)!;expect(result.id).toBe(7);const schema=JSON.stringify(result);expect(schema).toContain("ca_fixture_owned");expect(schema).not.toContain("COMPOSIO_SEARCH_TOOLS");expect(result.result.tools[0]?.inputSchema.properties.tools.items.properties.tool_slug.enum).toEqual(["GMAIL_FETCH_EMAILS"]);});

it("does not revive a queued request when its manager returns to the old role",()=>{const f=setup();const request=requestBotAccess(f.store,f.lead,{botId:f.bot.id,revision:0,grants:[grant]});f.store.setChiefOfStaff(null,"Studio");f.store.setChiefOfStaff(f.lead.id,undefined,"section");expect(()=>reviewBotAccess(f.store,f.bot.id,{action:"approve",requestId:request.requestId,revision:request.revision},[account])).toThrow("stale");const restored=new Store(()=>f.bot.modelSelection);expect(()=>reviewBotAccess(restored,f.bot.id,{action:"approve",requestId:request.requestId,revision:request.revision},[account])).toThrow("stale");});
