// SPDX-License-Identifier: AGPL-3.0-or-later
import { describe, it, expect } from "vitest";
import { BrowserExtensionPolicy, type BrowserAction } from "./browser-extension-policy.ts";
function fixture() {
  let now=1000; const policy=new BrowserExtensionPolicy({now:()=>now,protectedOrigins:["http://127.0.0.1:23456"]});
  const context=policy.bind({bindingId:"binding",workspaceId:"workspace",botId:"bot",threadId:"thread",clientId:"client",profileId:"profile"});
  const document={profileId:"profile",tabId:1,frameId:0,navigationEpoch:1,origin:"https://example.com"};
  policy.share(context,document,"https://example.com/"); policy.setSiteAccess(context,document.origin,"allow");
  const action:BrowserAction={operation:"click",document,targetDigest:"a".repeat(64),params:{ref:"b1"}};
  return {policy,context,document,action,advance:()=>now+=60001};
}
describe("browser extension authority",()=>{
  it("allows consented reads but site access never authorizes writes",()=>{const f=fixture();expect(f.policy.check(f.context,{...f.action,operation:"read"}).requiresApproval).toBe(false);expect(()=>f.policy.authorizeDispatch(f.context,f.action)).toThrow("action_approval_required");});
  it("consumes approval exactly once",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);f.policy.authorizeDispatch(f.context,f.action,grant)();expect(()=>f.policy.authorizeDispatch(f.context,f.action,grant)).toThrow("invalid_approval");});
  it.each(["clientId","threadId","workspaceId","botId","profileId"] as const)("rejects cross %s identity",key=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);expect(()=>f.policy.consumeApproval({...f.context,[key]:"other"},f.action,grant)).toThrow("stale_binding");});
  it("binds approval to observed content and arguments",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);expect(()=>f.policy.consumeApproval(f.context,{...f.action,targetDigest:"b".repeat(64)},grant)).toThrow("invalid_approval");expect(()=>f.policy.consumeApproval(f.context,{...f.action,params:{ref:"b2"}},grant)).toThrow("invalid_approval");});
  it("expires unanswered grants",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);f.advance();expect(()=>f.policy.consumeApproval(f.context,f.action,grant)).toThrow("invalid_approval");});
  it("navigation invalidates old epochs and grants including same-origin history",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);const document={...f.document,navigationEpoch:2};f.policy.navigate(f.context,document,"https://example.com/#new");expect(()=>f.policy.check(f.context,f.action)).toThrow("stale_document");expect(()=>f.policy.consumeApproval(f.context,{...f.action,document},grant)).toThrow("invalid_approval");});
  it("protected redirects still invalidate prior authority",()=>{const f=fixture();f.policy.navigate(f.context,{...f.document,navigationEpoch:2,origin:"https://bitwarden.com"},"https://bitwarden.com/");expect(()=>f.policy.check(f.context,f.action)).toThrow("stale_document");expect(()=>f.policy.check(f.context,{...f.action,document:{...f.document,navigationEpoch:2,origin:"https://bitwarden.com"}})).toThrow("handover_required");});
  it("stop fences old responses and resume requires owner document reconciliation",()=>{const f=fixture();const stopped=f.policy.stop(f.context);expect(()=>f.policy.check(f.context,f.action)).toThrow("stale_binding");expect(()=>f.policy.check(stopped,f.action)).toThrow("stopped");expect(()=>f.policy.resume(stopped,[])).toThrow("document_reconciliation_required");const resumed=f.policy.resume(stopped,[f.document]);expect(f.policy.check(resumed,f.action)).toBeTruthy();});
  it("pause blocks reads and cannot downgrade stopped state",()=>{const f=fixture();const paused=f.policy.pause(f.context);expect(()=>f.policy.check(paused,{...f.action,operation:"read"})).toThrow("paused");const stopped=f.policy.stop(paused);expect(()=>f.policy.pause(stopped)).toThrow("stopped");});
  it("unshare revokes grants and tab ownership",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);const next=f.policy.unshare(f.context,1);expect(()=>f.policy.consumeApproval(next,f.action,grant)).toThrow("tab_not_shared");});
  it("two bindings cannot claim the same tab",()=>{const f=fixture();const other=f.policy.bind({bindingId:"other",botId:"other",workspaceId:f.context.workspaceId,threadId:f.context.threadId,clientId:f.context.clientId,profileId:f.context.profileId});expect(()=>f.policy.share(other,f.document,"https://example.com/")).toThrow("tab_already_shared");expect(()=>f.policy.check(other,f.action)).toThrow("tab_not_shared");});
  it("serializes profile writes but permits reads on separately owned tabs",()=>{const f=fixture();const other=f.policy.bind({bindingId:"other",botId:"other",workspaceId:f.context.workspaceId,threadId:f.context.threadId,clientId:f.context.clientId,profileId:f.context.profileId});const document={...f.document,tabId:2};f.policy.share(other,document,"https://example.com/");f.policy.setSiteAccess(other,document.origin,"allow");const action={...f.action,document};const a=f.policy.issueApproval(f.context,f.action),b=f.policy.issueApproval(other,action);const release=f.policy.authorizeDispatch(f.context,f.action,a);expect(()=>f.policy.authorizeDispatch(other,action,b)).toThrow("profile_busy");f.policy.authorizeDispatch(other,{...action,operation:"read"})();release();f.policy.authorizeDispatch(other,action,b)();});
  it.each(["file:///x","about:blank","javascript:alert(1)","https://u:p@example.com/","https://vault.bitwarden.com/","https://1password.com/","https://chromewebstore.google.com/","http://127.0.0.1:23456/"])("hands over protected destination %s",destination=>{const f=fixture();expect(()=>f.policy.check(f.context,{...f.action,operation:"navigate",destination})).toThrow("handover_required");});
  it("bootstrap allows navigation only after destination consent",()=>{const f=fixture();const document={...f.document,tabId:2,navigationEpoch:0,origin:"null"};f.policy.share(f.context,document,"about:blank");expect(()=>f.policy.check(f.context,{...f.action,document,operation:"read"})).toThrow("bootstrap_only");expect(f.policy.check(f.context,{...f.action,document,operation:"navigate",destination:"https://example.com/"}).requiresApproval).toBe(false);});
  it("cross origin query disclosure needs separate one-use approval",()=>{const f=fixture();f.policy.setSiteAccess(f.context,"https://other.test","allow");const action={...f.action,operation:"navigate",destination:"https://other.test/?data=private"};expect(()=>f.policy.authorizeDispatch(f.context,action)).toThrow("action_approval_required");});
  it("site revocation invalidates grants",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);f.policy.setSiteAccess(f.context,f.document.origin,"never");expect(()=>f.policy.consumeApproval(f.context,f.action,grant)).toThrow("site_denied");});
  it("unknown actions require approval and protected document input is refused",()=>{const f=fixture();expect(f.policy.check(f.context,{...f.action,operation:"unknown"}).requiresApproval).toBe(true);expect(()=>f.policy.check(f.context,{...f.action,protectedDocument:true})).toThrow("handover_required");});
  it("cross-origin frames are refused",()=>{const f=fixture();expect(()=>f.policy.check(f.context,{...f.action,document:{...f.document,frameId:2}})).toThrow("invalid_document");});
});

describe("authenticated runtime reconciliation",()=>{
  it("mirrors offline stopped generations without allowing reconnect resume",()=>{const f=fixture();const current=f.policy.reconcile(f.context,{generation:8,state:"stopped",documents:[{document:f.document,url:"https://example.com/"}],reason:"observe"});expect(current.generation).toBe(8);expect(()=>f.policy.reconcile(current,{generation:9,state:"active",documents:[{document:f.document,url:"https://example.com/"}],reason:"observe"})).toThrow("owner_resume_required");expect(f.policy.reconcile(current,{generation:9,state:"active",documents:[{document:f.document,url:"https://example.com/"}],reason:"owner-resume"}).generation).toBe(9);});
  it("atomically rejects new ownership and stale documents",()=>{const f=fixture();expect(()=>f.policy.reconcile(f.context,{generation:2,state:"paused",reason:"observe",documents:[{document:f.document,url:"https://example.com/"},{document:{...f.document,tabId:9},url:"https://example.com/"}]})).toThrow("tab_not_shared");expect(f.policy.status("binding").context.generation).toBe(1);expect(()=>f.policy.reconcile(f.context,{generation:2,state:"paused",reason:"observe",documents:[{document:{...f.document,navigationEpoch:0},url:"https://example.com/"}]})).toThrow("stale_document");});
  it("removals release ownership and invalidate approvals while preserving site consent",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);const current=f.policy.reconcile(f.context,{generation:2,state:"active",documents:[],reason:"observe"});f.policy.share(current,f.document,"https://example.com/");expect(f.policy.check(current,{...f.action,operation:"read"}).requiresApproval).toBe(false);expect(()=>f.policy.consumeApproval(current,f.action,grant)).toThrow("invalid_approval");});
  it("same-generation document transitions fence old grants",()=>{const f=fixture();const grant=f.policy.issueApproval(f.context,f.action);const document={...f.document,navigationEpoch:2};f.policy.reconcile(f.context,{generation:1,state:"active",reason:"observe",documents:[{document,url:"https://example.com/#new"}]});expect(()=>f.policy.consumeApproval(f.context,{...f.action,document},grant)).toThrow("invalid_approval");});
  it("refuses protected owner resume and unbounded generation jumps",()=>{const f=fixture();const stopped=f.policy.stop(f.context);expect(()=>f.policy.reconcile(stopped,{generation:3,state:"active",reason:"owner-resume",documents:[{document:{...f.document,navigationEpoch:2,origin:"https://bitwarden.com"},url:"https://bitwarden.com/"}]})).toThrow("handover_required");expect(()=>f.policy.reconcile(stopped,{generation:1000003,state:"stopped",reason:"observe",documents:[]})).toThrow("invalid_reconciliation");});
});
