// The team library, local first.
//
// Everything here used to begin with a request to raw.githubusercontent.com,
// and GET /api/team-library/catalog turned any failure into a 502 — so with no
// network the library panel was an error box and every "Set this up" button was
// dead. Murage runs headless, air-gapped, and driven by local models. No runtime
// network call may be REQUIRED for the library to work.
//
// So the direction is inverted: the shipped tree is the source of truth and the
// network is an optional upgrade.
//
//   library/catalog.json      generated by scripts/build-local-catalog.mjs,
//                             committed, packaged. 122 entries.
//   library/assistants/       28 profile packages   ─┐ the document the importer
//   bot-library/builtins/     29 profile packages    ├ consumes, one file per
//   library/packages/         65 team packages      ─┘ slug, filename === id.
//
// A remote catalog still refreshes over the top, but it can only ADD slugs the
// local tree does not have, it is written to a cache only after surviving
// parseTeamCatalog, and it can never make the library empty — which is the
// failure the old MAX_CATALOG_ENTRIES ceiling caused once already.
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { DATA_DIR } from "./config.ts";
import { parseJson, type JsonValue } from "./schema.ts";
import { isBotPackage, parseBotPackage, type ParsedBotPackage } from "./bot-package.ts";
import { parseTeamManifest, type ParsedTeamManifest } from "./team-manifest.ts";

export const TEAM_LIBRARY_REPOSITORY = "https://github.com/FerroxLabs/murage-teams";
export const TEAM_LIBRARY_RAW_ROOT = "https://raw.githubusercontent.com/FerroxLabs/murage-teams/main";
export const TEAM_LIBRARY_CATALOG_URL = `${TEAM_LIBRARY_RAW_ROOT}/catalog.json`;

/** Wire ceiling for one catalog download. The live catalog is 85,500 bytes and
 *  the generated local one is 194,633; 256,000 left a released client one
 *  upstream edit away from throwing on a catalog it had to accept, and
 *  parseTeamCatalog throws before returning anything, so that failure used to
 *  lose every entry rather than the new ones. Local-first means it no longer
 *  empties the panel, but the headroom is still the point. */
const MAX_CATALOG_BYTES = 1_000_000;
/** Entry ceiling. 65 teams plus 57 single-agent profiles already exceed the
 *  original 100, and one catalog fetch is still bounded by MAX_CATALOG_BYTES. */
const MAX_CATALOG_ENTRIES = 400;
const MAX_MANIFEST_BYTES = 1_000_000;

/** Where the shipped library tree lives. Overridable so a packaged build can
 *  point at its own Resources directory without moving the repo layout — the
 *  desktop main process sets these in the forked server child's env from
 *  electron/harness-resources.mjs. In dev the cwd fallback finds the same tree.
 *  An unset variable in a packaged build reads as "this tree is empty", which is
 *  exactly how MURAGE_SKILL_LIBRARY shipped nothing through 0.1.44; the
 *  harness-resources sync test is what stops that happening here. */
export const LIBRARY_ROOT = process.env.MURAGE_LIBRARY_DIR || join(process.cwd(), "library");
export const BOT_LIBRARY_ROOT = process.env.MURAGE_BOT_LIBRARY_DIR || join(process.cwd(), "bot-library");
/** The generated, committed, packaged catalog. */
export const LOCAL_CATALOG_FILE = join(LIBRARY_ROOT, "catalog.json");
/** A downloaded catalog is cached beside the rest of the user's state, never
 *  back into the read-only shipped tree. */
export const REMOTE_CATALOG_CACHE_FILE = join(DATA_DIR, "team-library", "catalog.json");
/** How old a cached download may be before the next catalog read kicks off a
 *  background refresh. Time since download, not a tree fingerprint: the thing
 *  being judged stale is the copy of someone else's file. */
const CATALOG_REFRESH_INTERVAL_MS = 6 * 60 * 60 * 1000;

export interface TeamCatalogEntry {
  slug: string;
  name: string;
  summary: string;
  category: string;
  outcome?: string;
  setupMinutes?: number;
  featured?: boolean;
  package?: string;
  manifest: string;
  readme: string;
  members: number;
  skills: string[];
  requires: { apps: string[] };
}

export interface TeamCatalog {
  format: "murage.catalog";
  version: 1;
  repositoryUrl: typeof TEAM_LIBRARY_REPOSITORY;
  teams: TeamCatalogEntry[];
}

type Fetcher = typeof fetch;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === "object" && !Array.isArray(value);

function text(value: unknown, field: string, max: number): string {
  if (typeof value !== "string" || !value.trim()) throw new Error(`${field} is required`);
  const normalized = value.trim();
  if (normalized.length > max) throw new Error(`${field} is too long`);
  return normalized;
}

function relativeFile(value: unknown, field: string, suffix: string, prefix: string): string {
  const path = text(value, field, 300);
  if (
    path.startsWith("/") ||
    path.includes("\\") ||
    path.split("/").some((part) => !part || part === "." || part === "..") ||
    !path.startsWith(prefix) ||
    !path.endsWith(suffix)
  ) {
    throw new Error(`${field} is not a safe catalog path`);
  }
  return path;
}

function stringList(value: unknown, field: string, maxItems: number): string[] {
  if (!Array.isArray(value) || value.length > maxItems) throw new Error(`${field} is invalid`);
  return value.map((item, index) => text(item, `${field}[${index}]`, 100));
}

/** Validate the remotely maintained index before any of it reaches the renderer. */
export function parseTeamCatalog(value: unknown): TeamCatalog {
  if (!isRecord(value) || value.format !== "murage.catalog" || value.version !== 1) {
    throw new Error("The team library catalog is not supported");
  }
  if (!Array.isArray(value.teams) || value.teams.length > MAX_CATALOG_ENTRIES) {
    throw new Error("The team library catalog is invalid");
  }
  const slugs = new Set<string>();
  const teams = value.teams.map((raw, index): TeamCatalogEntry => {
    const field = `teams[${index}]`;
    if (!isRecord(raw)) throw new Error(`${field} is invalid`);
    const slug = text(raw.slug, `${field}.slug`, 80);
    if (!/^[a-z0-9][a-z0-9-]*$/.test(slug) || slugs.has(slug)) {
      throw new Error(`${field}.slug is invalid`);
    }
    slugs.add(slug);
    const prefix = `teams/${slug}/`;
    const requires = isRecord(raw.requires) ? raw.requires : {};
    return {
      slug,
      name: text(raw.name, `${field}.name`, 100),
      summary: text(raw.summary, `${field}.summary`, 300),
      category: text(raw.category, `${field}.category`, 80),
      ...(typeof raw.outcome === "string" ? { outcome: text(raw.outcome, `${field}.outcome`, 300) } : {}),
      ...(typeof raw.setupMinutes === "number" && Number.isSafeInteger(raw.setupMinutes) && raw.setupMinutes > 0 && raw.setupMinutes <= 240
        ? { setupMinutes: raw.setupMinutes }
        : {}),
      ...(typeof raw.featured === "boolean" ? { featured: raw.featured } : {}),
      ...(raw.package !== undefined
        ? { package: relativeFile(raw.package, `${field}.package`, ".md", "packages/") }
        : {}),
      manifest: relativeFile(raw.manifest, `${field}.manifest`, ".emberteam.json", prefix),
      readme: relativeFile(raw.readme, `${field}.readme`, "README.md", prefix),
      members:
        typeof raw.members === "number" && Number.isSafeInteger(raw.members) && raw.members > 0 && raw.members <= 200
          ? raw.members
          : (() => { throw new Error(`${field}.members is invalid`); })(),
      skills: Array.isArray(raw.skills)
        ? raw.skills.map((skill, skillIndex) =>
            relativeFile(skill, `${field}.skills[${skillIndex}]`, "SKILL.md", `${prefix}skills/`),
          )
        : (() => { throw new Error(`${field}.skills is invalid`); })(),
      requires: { apps: stringList(requires.apps ?? [], `${field}.requires.apps`, 30) },
    };
  });
  return {
    format: "murage.catalog",
    version: 1,
    repositoryUrl: TEAM_LIBRARY_REPOSITORY,
    teams,
  };
}

async function fetchJson(url: string, maxBytes: number, fetcher: Fetcher): Promise<JsonValue> {
  const response = await fetcher(url, {
    headers: { accept: "application/json, text/plain;q=0.9" },
    redirect: "error",
    signal: AbortSignal.timeout(10_000),
  });
  if (!response.ok) {
    const error = Object.assign(new Error(`GitHub returned HTTP ${response.status}`), { status: response.status });
    throw error;
  }
  const announced = Number(response.headers.get("content-length") ?? 0);
  if (announced > maxBytes) throw new Error("The remote team file is too large");
  const raw = await response.text();
  if (Buffer.byteLength(raw) > maxBytes) throw new Error("The remote team file is too large");
  try {
    return parseJson(raw);
  } catch {
    throw new Error("GitHub did not return valid JSON");
  }
}

async function fetchText(url: string, maxBytes: number, fetcher: Fetcher): Promise<string> {
  const response = await fetcher(url, {
    headers: { accept: "text/markdown, text/plain;q=0.9" },
    redirect: "error",
    signal: AbortSignal.timeout(10_000),
  });
  if (!response.ok) throw Object.assign(new Error(`GitHub returned HTTP ${response.status}`), { status: response.status });
  const announced = Number(response.headers.get("content-length") ?? 0);
  if (announced > maxBytes) throw new Error("The remote team file is too large");
  const raw = await response.text();
  if (Buffer.byteLength(raw) > maxBytes) throw new Error("The remote team file is too large");
  return raw;
}

const SAFE_SLUG = /^[a-z0-9][a-z0-9-]*$/;

/** The two shipped trees a slug's document can live in. Passed rather than read
 *  from module state so a test can point at a fixture without re-importing. */
export interface LocalLibraryRoots {
  library: string;
  botLibrary: string;
}
export const DEFAULT_ROOTS: LocalLibraryRoots = { library: LIBRARY_ROOT, botLibrary: BOT_LIBRARY_ROOT };

export interface LocalCatalogOptions {
  catalogFile?: string;
  cacheFile?: string;
}

function report(message: string, error: unknown): void {
  console.error(JSON.stringify({ message, error: error instanceof Error ? error.message : String(error) }));
}

/** The shipped catalog, or null if this build has none. Read and re-parsed on
 *  every call rather than memoised: the file is 195 KB, parsing it is under a
 *  millisecond at the rate the panel asks, and any cache key cheap enough to be
 *  worth it (mtime, size) can miss an edit and then serve the stale copy
 *  forever. Null means "no local library", never "an empty library". */
export function loadLocalCatalog(file = LOCAL_CATALOG_FILE): TeamCatalog | null {
  if (!existsSync(file)) return null;
  try {
    // The local catalog goes through exactly the gate a remote one does. A
    // shipped file is more trusted than a download, not differently validated.
    return parseTeamCatalog(parseJson(readFileSync(file, "utf8")));
  } catch (error) {
    report("local team catalog could not be read", error);
    return null;
  }
}

/** Every place a slug's package document may be committed, in resolution order.
 *  `.md` first because the markdown playbook form takes precedence at install
 *  time exactly as `entry.package ?? entry.manifest` does on the remote. */
function localTeamCandidates(slug: string, roots: LocalLibraryRoots): string[] {
  return [
    join(roots.library, "packages", `${slug}.md`),
    join(roots.library, "packages", `${slug}.json`),
    join(roots.library, "assistants", `${slug}.json`),
    join(roots.botLibrary, "builtins", `${slug}.json`),
  ];
}

/** The importable document for a slug, read from the shipped tree. Null when
 *  this build does not carry it — the caller falls back to the network, and
 *  offline that becomes an honest error rather than a half-installed bot. */
export function loadLocalTeam(slug: string, roots: LocalLibraryRoots = DEFAULT_ROOTS): ParsedShareableTeam | null {
  // The same traversal gate the route applies, re-applied here so no caller can
  // hand this a slug that names a path instead of an entry.
  if (!SAFE_SLUG.test(slug)) return null;
  for (const file of localTeamCandidates(slug, roots)) {
    if (!existsSync(file)) continue;
    try {
      const raw = readFileSync(file, "utf8");
      const parsed = file.endsWith(".md") ? parseBotPackage(raw) : parseShareable(parseJson(raw));
      const id = parsed.format === "murage.package" ? parsed.package.id : slug;
      // A file that names a different package than its filename would let one
      // catalog entry install another entry's bots. Refuse rather than repair.
      if (id !== slug) throw new Error(`${file} declares ${JSON.stringify(id)}`);
      return parsed;
    } catch (error) {
      report("local library package could not be read", error);
      return null;
    }
  }
  return null;
}

interface CachedCatalog {
  fetchedAt: number;
  catalog: TeamCatalog;
}

function readCachedCatalog(file = REMOTE_CATALOG_CACHE_FILE): CachedCatalog | null {
  if (!existsSync(file)) return null;
  try {
    const raw = parseJson(readFileSync(file, "utf8"));
    if (!isRecord(raw) || typeof raw.fetchedAt !== "number" || !Number.isFinite(raw.fetchedAt)) {
      throw new Error("cache has no fetchedAt");
    }
    // Re-validated on read, not just on write: the cache lives in a directory
    // the user (and anything running as the user) can edit.
    return { fetchedAt: raw.fetchedAt, catalog: parseTeamCatalog(raw.catalog) };
  } catch (error) {
    report("cached team catalog was rejected", error);
    return null;
  }
}

function writeCachedCatalog(catalog: TeamCatalog, file = REMOTE_CATALOG_CACHE_FILE): void {
  const payload: CachedCatalog = { fetchedAt: Date.now(), catalog };
  mkdirSync(join(file, ".."), { recursive: true, mode: 0o700 });
  // Written whole then renamed, so a crash mid-write leaves the previous cache
  // rather than a truncated file the next read has to reject.
  const temporary = `${file}.${process.pid}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(payload)}\n`, { mode: 0o600 });
  renameSync(temporary, file);
}

/** Local wins for every slug it carries; the remote may only ADD. The local
 *  document is the one that will actually install, so a remote entry describing
 *  the same slug differently would put a label on the card that the import does
 *  not honour. Order is local-first, then remote-only in remote order, so the
 *  panel's ordering does not shuffle when the network comes and goes. */
export function mergeCatalogs(local: TeamCatalog, remote: TeamCatalog | null): TeamCatalog {
  if (!remote) return local;
  const known = new Set(local.teams.map((team) => team.slug));
  const added = remote.teams.filter((team) => !known.has(team.slug));
  return added.length ? { ...local, teams: [...local.teams, ...added] } : local;
}

let refreshInFlight: Promise<void> | null = null;

/** Download the remote catalog and cache it if it survives validation. Resolves
 *  either way — a refresh that throws would be an unhandled rejection on a path
 *  nothing awaits, and a library that works offline must not care that this
 *  failed. */
export async function refreshRemoteCatalog(
  fetcher: Fetcher = fetch,
  file = REMOTE_CATALOG_CACHE_FILE,
): Promise<TeamCatalog | null> {
  try {
    const catalog = await downloadCatalog(fetcher);
    writeCachedCatalog(catalog, file);
    return catalog;
  } catch (error) {
    report("team catalog refresh failed", error);
    return null;
  }
}

/** One validated download, no cache write. Reading a single entry must not have
 *  the side effect of replacing everyone's cached index. */
function downloadCatalog(fetcher: Fetcher): Promise<TeamCatalog> {
  return fetchJson(TEAM_LIBRARY_CATALOG_URL, MAX_CATALOG_BYTES, fetcher).then(parseTeamCatalog);
}

function scheduleCatalogRefresh(cached: CachedCatalog | null, file: string): void {
  if (cached && Date.now() - cached.fetchedAt < CATALOG_REFRESH_INTERVAL_MS) return;
  if (refreshInFlight) return;
  // Only ever with the real fetch: a caller that passed its own fetcher is
  // driving the network deliberately and must not also get a detached one.
  refreshInFlight = refreshRemoteCatalog(fetch, file)
    .then(() => undefined)
    .finally(() => {
      refreshInFlight = null;
    });
}

/** Local first. The catalog is served from the shipped tree, a cached download
 *  adds any slug the tree does not have, and a stale cache kicks off a refresh
 *  that nothing waits on. Only a build with no local catalog at all falls back
 *  to the old behaviour of requiring the network. */
export async function fetchTeamCatalog(
  fetcher: Fetcher = fetch,
  { catalogFile = LOCAL_CATALOG_FILE, cacheFile = REMOTE_CATALOG_CACHE_FILE }: LocalCatalogOptions = {},
): Promise<TeamCatalog> {
  const local = loadLocalCatalog(catalogFile);
  if (!local) return downloadCatalog(fetcher);
  const cached = readCachedCatalog(cacheFile);
  if (fetcher === fetch) scheduleCatalogRefresh(cached, cacheFile);
  return mergeCatalogs(local, cached?.catalog ?? null);
}

export type ParsedShareableTeam = ParsedTeamManifest | ParsedBotPackage;

function parseShareable(value: JsonValue | string): ParsedShareableTeam {
  if (typeof value === "string") return parseBotPackage(value);
  return isBotPackage(value) ? parseBotPackage(value) : parseTeamManifest(value);
}

async function fetchShareable(url: string, fetcher: Fetcher): Promise<ParsedShareableTeam> {
  return url.endsWith(".md")
    ? parseBotPackage(await fetchText(url, MAX_MANIFEST_BYTES, fetcher))
    : parseShareable(await fetchJson(url, MAX_MANIFEST_BYTES, fetcher));
}

/** Local first, for the same reason the catalog is: a catalog that loads offline
 *  in front of an install that does not is worse than the 502 it replaced — the
 *  panel would list 122 teams and every "Set this up" button would fail. Every
 *  slug in the shipped catalog has its document in the shipped tree, so the
 *  network is reached only for a slug that arrived from a remote refresh. */
export async function fetchLibraryTeam(
  slug: string,
  fetcher: Fetcher = fetch,
  options: LocalCatalogOptions & { roots?: LocalLibraryRoots } = {},
): Promise<ParsedShareableTeam> {
  if (!SAFE_SLUG.test(slug)) throw new Error("That team name is invalid");
  const local = loadLocalTeam(slug, options.roots ?? DEFAULT_ROOTS);
  if (local) return local;
  // Not in the shipped tree, so this slug can only have come from a refresh.
  // Look in what we already have, then — and only then — ask upstream directly,
  // so a team published since this build still resolves on its first click
  // instead of 404-ing until some background refresh happens to land. Offline
  // that request throws, which is the honest answer: the entry is not here and
  // the place it lives is unreachable.
  const merged = await fetchTeamCatalog(fetcher, options);
  const entry =
    merged.teams.find((team) => team.slug === slug) ??
    (await downloadCatalog(fetcher)).teams.find((team) => team.slug === slug);
  if (!entry) throw Object.assign(new Error("That library team was not found"), { status: 404 });
  return fetchShareable(`${TEAM_LIBRARY_RAW_ROOT}/${entry.package ?? entry.manifest}`, fetcher);
}

function safeSegment(value: string): boolean {
  return /^[A-Za-z0-9._-]+$/.test(value) && value !== "." && value !== "..";
}

/** Resolve only public GitHub Markdown playbooks and legacy JSON team files.
 * Other hosts never reach server fetch. */
export function githubManifestUrls(input: string): string[] {
  let url: URL;
  try {
    url = new URL(input.trim());
  } catch {
    throw new Error("Enter a valid GitHub URL");
  }
  if (url.protocol !== "https:" || url.username || url.password || url.port) {
    throw new Error("Only public HTTPS GitHub links are supported");
  }
  const parts = url.pathname.split("/").filter(Boolean).map((part) => decodeURIComponent(part));
  if (!parts.every(safeSegment)) throw new Error("That GitHub path is not supported");

  if (url.hostname === "github.com" || url.hostname === "www.github.com") {
    if (parts.length === 2) {
      const [owner, repo] = parts;
      return [
        `https://raw.githubusercontent.com/${owner}/${repo}/main/EmberBot.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/main/botmrr.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/main/team.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/main/team.emberteam.json`,
        `https://raw.githubusercontent.com/${owner}/${repo}/master/EmberBot.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/master/botmrr.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/master/team.md`,
        `https://raw.githubusercontent.com/${owner}/${repo}/master/team.emberteam.json`,
      ];
    }
    if (parts.length >= 5 && (parts[2] === "blob" || parts[2] === "raw")) {
      const [owner, repo, , ref, ...file] = parts;
      if (!file.at(-1)?.match(/\.(?:md|json)$/)) throw new Error("The GitHub link must point to a Markdown playbook or JSON team file");
      return [`https://raw.githubusercontent.com/${owner}/${repo}/${ref}/${file.join("/")}`];
    }
  }

  if (url.hostname === "raw.githubusercontent.com" && parts.length >= 4) {
    if (!parts.at(-1)?.match(/\.(?:md|json)$/)) throw new Error("The GitHub link must point to a Markdown playbook or JSON team file");
    return [`https://raw.githubusercontent.com/${parts.join("/")}`];
  }

  throw new Error("Paste a GitHub repository, Markdown playbook, or legacy JSON team link");
}

export async function fetchGithubTeam(input: string, fetcher: Fetcher = fetch): Promise<ParsedShareableTeam> {
  const urls = githubManifestUrls(input);
  let lastError: unknown;
  for (const url of urls) {
    try {
      return await fetchShareable(url, fetcher);
    } catch (error) {
      lastError = error;
      if ((error as { status?: number }).status !== 404) throw error;
    }
  }
  throw lastError ?? new Error("No EmberBot.md, compatible Markdown playbook, or legacy team file was found in that repository");
}
