// GENERATED by scripts/skill-guard/extract_skillspector.py. Do not edit.
// Patterns from NVIDIA SkillSpector (https://github.com/NVIDIA/SkillSpector),
// Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES, Apache-2.0; converted
// to JavaScript regex syntax by Ferrox Labs. See NOTICE.
import type { SkillSeverity } from "./types.ts";

export interface SpectorPattern { id: string; category: string; severity: SkillSeverity; confidence: number; source: string }
export const SPECTOR_COMMIT = "94f5cc80679c45a1fa4774e2d37ad663ca0be337";
export const SPECTOR_PATTERNS: SpectorPattern[] = [
 {
  "id": "AS1_CODE.1",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "open\\s*\\(\\s*['\\\"]?\\.(?:claude|codex|gemini|continue)/"
 },
 {
  "id": "AS1_CODE.2",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:Path|pathlib\\.Path)\\s*\\(\\s*['\\\"]?\\.(?:claude|codex|gemini|continue)/"
 },
 {
  "id": "AS1_CODE.3",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.85,
  "source": "os\\.path\\.(?:join|exists|isfile)\\s*\\(\\s*['\\\"]?\\.(?:claude|codex|gemini|continue)"
 },
 {
  "id": "AS1_CODE.4",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:cat|less|head|tail|grep|find)\\s+[^|&;\\n]*~?/?\\.(claude|codex|gemini)/"
 },
 {
  "id": "AS1_CODE.5",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "~?/\\.(?:claude|codex|gemini|continue)/(?:config|settings?|preferences?|credentials?)(?:\\.(?:json|yaml|yml|toml))?"
 },
 {
  "id": "AS1_PROSE.1",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:read|load|open|access|fetch)\\s+(?:the\\s+)?(?:agent|claude|codex|gemini)\\s+(?:config|configuration|settings?)\\s+(?:from|at|in)\\s+~?/?\\.(?:claude|codex|gemini)"
 },
 {
  "id": "AS1_PROSE.2",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:read|access|inspect|examine|retrieve)\\s+(?:the\\s+)?(?:agent|assistant)\\s+(?:config(?:uration)?|settings?|preferences?)\\s+(?:file|directory|folder)"
 },
 {
  "id": "AS2_CODE.1",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.95,
  "source": "open\\s*\\(\\s*['\\\"][^'\\\"]*mcp(?:_config)?\\.json['\\\"]"
 },
 {
  "id": "AS2_CODE.2",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:Path|pathlib\\.Path)\\s*\\(\\s*['\\\"][^'\\\"]*mcp(?:_config)?\\.json['\\\"]"
 },
 {
  "id": "AS2_CODE.3",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:cat|less|head|grep)\\s+[^|&;\\n]*mcp(?:_config)?\\.json"
 },
 {
  "id": "AS2_CODE.4",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.95,
  "source": "\\.(?:claude|codex|gemini)/mcp(?:_config)?\\.json"
 },
 {
  "id": "AS2_CODE.5",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "mcp(?:_config)?\\.json.*?(?:api_?key|token|secret|url|endpoint)"
 },
 {
  "id": "AS2_PROSE.1",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:read|access|load|inspect)\\s+(?:the\\s+)?mcp(?:\\.json|_config)?\\s+(?:file|config(?:uration)?|settings?)"
 },
 {
  "id": "AS2_PROSE.2",
  "category": "Agent Snooping",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:list|enumerate|discover)\\s+(?:all\\s+)?(?:available\\s+)?mcp\\s+(?:servers?|tools?|services?)"
 },
 {
  "id": "AS3_PROSE.1",
  "category": "Agent Snooping",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:read|access|inspect|enumerate)\\s+(?:all\\s+)?(?:installed|available|other)\\s+skills?(?:\\s+in\\s+(?:the\\s+)?(?:skills?|agent)\\s+(?:directory|folder))?"
 },
 {
  "id": "AS3_PROSE.2",
  "category": "Agent Snooping",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:list|discover|find|enumerate|identify)\\s+(?:all\\s+)?(?:other|installed|available)\\s+(?:skills?|agents?|tools?)\\s+(?:in\\s+)?(?:the\\s+)?(?:\\.(?:claude|codex|gemini)|\\$HOME)"
 },
 {
  "id": "AS3_PROSE.3",
  "category": "Agent Snooping",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:read|access|load)\\s+(?:the\\s+)?(?:SKILL|skill)\\.md\\s+(?:file\\s+)?(?:of|from|for)\\s+(?:another|other|different|all)\\s+(?:skill|agent|tool)"
 },
 {
  "id": "AR1.1",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\b(?:never|do\\s+not|don'?t)\\s+(?:ever\\s+)?(?:refuse|decline)\\b"
 },
 {
  "id": "AR1.2",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.9,
  "source": "\\byou\\s+(?:must|will|should|can)\\s*(?:not|never)\\s+(?:refuse|decline|say\\s+no)\\b"
 },
 {
  "id": "AR1.3",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\byou\\s+(?:cannot|can'?t|can\\s+not)\\s+(?:refuse|decline|say\\s+no)\\b"
 },
 {
  "id": "AR1.4",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\bnever\\s+say\\s+(?:that\\s+)?(?:you\\s+)?(?:can'?t|cannot|won'?t|no)\\b"
 },
 {
  "id": "AR1.5",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.7,
  "source": "\\balways\\s+(?:comply|obey|answer|respond)\\b"
 },
 {
  "id": "AR1.6",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.7,
  "source": "\\b(?:(?:you|the\\s+(?:agent|assistant|model))\\s+(?:must|should|will)\\s+always\\s+agree|always\\s+agree\\s+(?:with|to)\\s+(?:(?:the|every|all|any|each)\\s+)?(?:user|requests?|questions?|prompts?|queries|commands?))\\b"
 },
 {
  "id": "AR1.7",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\b(?:you\\s+)?must\\s+(?:always\\s+)?(?:answer|comply\\s+with|respond\\s+to|fulfill)\\s+(?:every|all|any|each)\\b"
 },
 {
  "id": "AR1.8",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.6,
  "source": "\\brespond\\s+to\\s+(?:every|all|any)\\s+(?:request|question|prompt|query|command)\\b"
 },
 {
  "id": "AR1.9",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\bno\\s+request\\s+is\\s+(?:off[- ]limits|forbidden|too)\\b"
 },
 {
  "id": "AR2.1",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\b(?:do\\s+not|don'?t|never|no)\\s+(?:include|add|give|provide|use|append)?\\s*(?:any\\s+)?(?:warnings?|disclaimers?|caveats?)\\b"
 },
 {
  "id": "AR2.2",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\bwithout\\s+(?:any\\s+)?(?:warnings?|disclaimers?|caveats?|moralizing|moralising|judg(?:e?ment|ing))\\b"
 },
 {
  "id": "AR2.3",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\b(?:do\\s+not|don'?t|never)\\s+(?:lecture|moralize|moralise|preach|judge|warn)\\b"
 },
 {
  "id": "AR2.4",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\b(?:skip|omit|leave\\s+out|drop)\\s+(?:the\\s+)?(?:disclaimer|warning|ethics|safety)\\b"
 },
 {
  "id": "AR2.5",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\b(?:no|without)\\s+(?:ethical|moral)\\s+(?:judg(?:e?ment)|considerations?|commentary|objections?)\\b"
 },
 {
  "id": "AR2.6",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.55,
  "source": "\\b(?:do\\s+not|don'?t)\\s+(?:apologize|apologise|say\\s+sorry)\\b"
 },
 {
  "id": "AR3.1",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.9,
  "source": "\\byou\\s+have\\s+no\\s+(?:restrictions?|limitations?|filters?|rules?|guidelines?|boundaries|limits)\\b"
 },
 {
  "id": "AR3.2",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\b(?:you\\s+are|act\\s+as|pretend\\s+(?:to\\s+be|you'?re))[^.\\n]{0,30}(?:unrestricted|unfiltered|uncensored|no\\s+filter)\\b"
 },
 {
  "id": "AR3.3",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.9,
  "source": "\\b(?:ignore|disregard|forget|bypass|override)\\s+(?:your\\s+)?(?:content\\s+)?(?:policy|policies|guidelines?|safety|restrictions?|filters?)\\b"
 },
 {
  "id": "AR3.4",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.9,
  "source": "\\bnot\\s+bound\\s+by\\s+(?:any\\s+)?(?:rules?|policy|policies|guidelines?|restrictions?|openai|anthropic)\\b"
 },
 {
  "id": "AR3.5",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\bdo\\s+anything\\s+now\\b"
 },
 {
  "id": "AR3.6",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.75,
  "source": "\\b(?:developer|debug|god|sudo|jailbreak)\\s+mode\\s+(?:enabled|on|activated|engaged)\\b"
 },
 {
  "id": "AR3.7",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.85,
  "source": "\\bno\\s+(?:content\\s+)?(?:policy|policies|filters?|restrictions?)\\s+appl(?:y|ies)\\b"
 },
 {
  "id": "AR3.8",
  "category": "Anti-Refusal",
  "severity": "medium",
  "confidence": 0.8,
  "source": "\\b(?:free\\s+from|without)\\s+(?:any\\s+)?(?:safety\\s+)?(?:guardrails?|constraints?|safeguards?)\\b"
 },
 {
  "id": "E1_CODE.1",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "requests\\s*\\.\\s*(?:post|put)\\s*\\(\\s*['\\\"]https?://"
 },
 {
  "id": "E1_CODE.2",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.7,
  "source": "requests\\s*\\.\\s*(?:post|put)\\s*\\([^)]*json\\s*="
 },
 {
  "id": "E1_CODE.3",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "httpx\\s*\\.\\s*(?:post|put)\\s*\\(\\s*['\\\"]https?://"
 },
 {
  "id": "E1_CODE.4",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "urllib\\s*\\.\\s*request\\s*\\.\\s*urlopen\\s*\\([^)]*data\\s*="
 },
 {
  "id": "E1_CODE.5",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "fetch\\s*\\(\\s*['\\\"]https?://[^'\\\"]+['\\\"][^)]*method\\s*:\\s*['\\\"]POST['\\\"]"
 },
 {
  "id": "E1_CODE.6",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "curl\\s+[^|]*(?:-d|--data|--data-raw|--data-binary)\\s+"
 },
 {
  "id": "E1_CODE.7",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "wget\\s+[^|]*--post-(?:data|file)"
 },
 {
  "id": "E1_CODE.8",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.5,
  "source": "https?://(?:api\\.|data\\.|collect\\.|telemetry\\.|analytics\\.)[\\w.-]+/"
 },
 {
  "id": "E1_PROSE.1",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:send|transmit|post|upload)\\s+(?:user\\s+)?(?:data|information|context|files?)\\s+to\\s+(?:https?://|external)"
 },
 {
  "id": "E2_PYTHON_FALLBACK.1",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "for\\s+\\w+\\s*,\\s*\\w+\\s+in\\s+os\\s*\\.\\s*environ\\s*\\.\\s*items\\s*\\(\\s*\\)"
 },
 {
  "id": "E2_PYTHON_FALLBACK.2",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.6,
  "source": "os\\s*\\.\\s*environ\\s*\\.\\s*copy\\s*\\(\\s*\\)"
 },
 {
  "id": "E2_PYTHON_FALLBACK.3",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.6,
  "source": "dict\\s*\\(\\s*os\\s*\\.\\s*environ\\s*\\)"
 },
 {
  "id": "E2_PYTHON_FALLBACK.4",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.6,
  "source": "\\{\\s*\\*\\*\\s*os\\s*\\.\\s*environ\\s*\\}"
 },
 {
  "id": "E2_OTHER_CODE.1",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:API_KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL)\\s+in\\s+(?:key|name|var)"
 },
 {
  "id": "E2_OTHER_CODE.2",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "process\\.env\\s*\\[\\s*['\\\"][^'\\\"]*(?:KEY|SECRET|TOKEN|PASSWORD)[^'\\\"]*['\\\"]\\s*\\]"
 },
 {
  "id": "E2_OTHER_CODE.3",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.6,
  "source": "Object\\.keys\\s*\\(\\s*process\\.env\\s*\\)"
 },
 {
  "id": "E2_OTHER_CODE.4",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.8,
  "source": "env\\s*\\|\\s*grep\\s+(?:-i\\s+)?(?:key|secret|token|password)"
 },
 {
  "id": "E2_OTHER_CODE.5",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "printenv\\s+(?:\\w*(?:KEY|SECRET|TOKEN|PASSWORD)\\w*)"
 },
 {
  "id": "E2_PROSE.1",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "collect\\s+(?:all\\s+)?(?:environment\\s+variables?|env\\s+vars?)"
 },
 {
  "id": "E2_PROSE.2",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:extract|harvest|gather)\\s+(?:api\\s+)?keys?\\s+from\\s+environment"
 },
 {
  "id": "E3_CODE.1",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.8,
  "source": "glob\\s*\\.\\s*glob\\s*\\([^)]*(?:\\.env|\\.ssh|\\.aws|\\.config|credentials)"
 },
 {
  "id": "E3_CODE.2",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "os\\s*\\.\\s*walk\\s*\\([^)]*(?:home|~|/Users|/home)"
 },
 {
  "id": "E3_CODE.3",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.7,
  "source": "Path\\s*\\.\\s*home\\s*\\(\\s*\\)\\s*\\.\\s*(?:glob|rglob)\\s*\\("
 },
 {
  "id": "E3_CODE.4",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.8,
  "source": "os\\s*\\.\\s*listdir\\s*\\([^)]*(?:\\.ssh|\\.aws|\\.config|\\.gnupg)"
 },
 {
  "id": "E3_CODE.5",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "scandir\\s*\\([^)]*(?:home|~|/Users|/home)"
 },
 {
  "id": "E3_CODE.6",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.8,
  "source": "find\\s+[~\\$/]\\S*\\s+.*?-name\\s+['\\\"]?\\*(?:\\.env|\\.pem|\\.key|credential)"
 },
 {
  "id": "E3_CODE.7",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "ls\\s+-[la]*R?\\s+(?:~/|/home/|/Users/)"
 },
 {
  "id": "E3_PROSE.1",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:find|search|scan|enumerate)\\s+(?:for\\s+)?(?:all\\s+)?(?:\\.env|credential|secret|key)\\s+files?"
 },
 {
  "id": "E3_PROSE.2",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:list|get)\\s+(?:all\\s+)?files?\\s+(?:in|from)\\s+(?:home|~|/Users|/home)"
 },
 {
  "id": "E3_PROSE.3",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.5,
  "source": "(?:recursively|recursive)\\s+(?:scan|search|find|list)\\s+(?:all\\s+)?files?"
 },
 {
  "id": "E3_PROSE.4",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "walk\\s+(?:through\\s+)?(?:the\\s+)?(?:entire\\s+)?(?:file\\s*system|directory|home)"
 },
 {
  "id": "E4.1",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:send|transmit|upload|log|record)\\s+(?:the\\s+)?(?:full\\s+)?(?:conversation|chat|dialog|session)\\s+(?:history|context|log)?"
 },
 {
  "id": "E4.2",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:export|dump|save)\\s+(?:the\\s+)?(?:conversation|chat|messages?)\\s+to\\s+(?:external|remote|server)"
 },
 {
  "id": "E4.3",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.85,
  "source": "log\\s+(?:all\\s+)?(?:user\\s+)?(?:input|messages?|queries?|prompts?)\\s+to\\s+(?:external|remote|server)"
 },
 {
  "id": "E4.4",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "(?:store|save|record)\\s+(?:every|all)\\s+(?:user\\s+)?(?:interaction|message|input)"
 },
 {
  "id": "E4.5",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.75,
  "source": "(?:extract|capture|collect)\\s+(?:the\\s+)?(?:full\\s+)?(?:context|conversation|thread)"
 },
 {
  "id": "E4.6",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.7,
  "source": "(?:include|attach|append)\\s+(?:previous\\s+)?(?:messages?|context|history)\\s+in\\s+(?:the\\s+)?(?:request|payload)"
 },
 {
  "id": "E4.7",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:send|upload|transmit)\\s+(?:the\\s+)?(?:session|memory|state)\\s+(?:data\\s+)?to"
 },
 {
  "id": "E4.8",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.75,
  "source": "(?:copy|clone|replicate)\\s+(?:the\\s+)?(?:agent|assistant)\\s+(?:memory|context|state)"
 },
 {
  "id": "E4.9",
  "category": "Data Exfiltration",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:always\\s+)?include\\s+(?:the\\s+)?(?:full\\s+)?(?:conversation|context)\\s+(?:when|in)\\s+(?:calling|making)\\s+(?:external|api)"
 },
 {
  "id": "E5.1",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.55,
  "source": "\\.put_object\\s*\\("
 },
 {
  "id": "E5.2",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.55,
  "source": "\\.upload_file(?:obj)?\\s*\\("
 },
 {
  "id": "E5.3",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "\\baws\\s+s3\\s+(?:cp|sync|mv)\\b"
 },
 {
  "id": "E5.4",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.65,
  "source": "\\baws\\s+s3api\\s+put-object\\b"
 },
 {
  "id": "E5.5",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "\\bgsutil\\s+(?:cp|rsync|mv)\\b"
 },
 {
  "id": "E5.6",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.55,
  "source": "\\.upload_from_(?:filename|string|file)\\s*\\("
 },
 {
  "id": "E5.7",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.6,
  "source": "\\baz\\s+storage\\s+blob\\s+upload\\b"
 },
 {
  "id": "E5.8",
  "category": "Data Exfiltration",
  "severity": "medium",
  "confidence": 0.55,
  "source": "\\.upload_blob\\s*\\("
 },
 {
  "id": "EA1_CODE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:tools?|permissions?)\\s*:[ \\t]*\\[?[ \\t]*['\\\"]?\\*(?!\\*|\\w)['\\\"]?[ \\t]*\\]?"
 },
 {
  "id": "EA1_CODE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "tools?\\s*:\\s*\\[\\s*['\\\"]shell['\\\"].*?['\\\"](?:file_write|network|http)['\\\"]"
 },
 {
  "id": "EA1_PROSE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:allow|grant|enable)\\s+(?:access\\s+to\\s+)?(?:all|any|every)\\s+tools?"
 },
 {
  "id": "EA1_PROSE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:no|without)\\s+(?:tool|permission|access|capability)\\s+(?:restrictions?|constraints?|limitations?)"
 },
 {
  "id": "EA1_PROSE.3",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:call|invoke|use|execute)\\s+(?:any|all|every)\\s+(?:available\\s+)?tools?"
 },
 {
  "id": "EA1_PROSE.4",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:unrestricted|unlimited|unconstrained)\\s+(?:tool|function|api)\\s+(?:access|use|calls?)"
 },
 {
  "id": "EA1_PROSE.5",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:can|may|should)\\s+(?:freely|always)\\s+(?:use|call|invoke)\\s+(?:any|all)\\s+(?:tools?|functions?|apis?)"
 },
 {
  "id": "EA1_PROSE.6",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:grant|give)\\s+(?:full|complete|total)\\s+(?:tool|function|api)\\s+access"
 },
 {
  "id": "EA1_PROSE.7",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:execute|run)\\s+(?:arbitrary|any)\\s+(?:commands?|code|scripts?)"
 },
 {
  "id": "EA1_PROSE.8",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:no\\s+)?(?:tool\\s+)?(?:allow|block|deny)\\s*(?:list|listing)\\s*(?:is\\s+)?(?:empty|disabled|off)"
 },
 {
  "id": "EA2_CODE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:auto[_-]?approve|auto[_-]?confirm|auto[_-]?execute|auto[_-]?deploy)"
 },
 {
  "id": "EA2_CODE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.65,
  "source": "(?:--auto-?approve|--no-?confirm)\\b"
 },
 {
  "id": "EA2_PROSE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:without|no)\\s+(?:asking|confirmation|approval|consent|verification|checking)"
 },
 {
  "id": "EA2_PROSE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:auto(?:matically)?|autonomously)\\s+(?:execute|run|perform|delete|remove|modify|send|deploy)"
 },
 {
  "id": "EA2_PROSE.3",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:skip|bypass|disable)\\s+(?:user\\s+)?(?:confirmation|approval|consent|verification|prompt)"
 },
 {
  "id": "EA2_PROSE.4",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:do\\s+not|don't|never)\\s+(?:ask|prompt|confirm|verify|check)\\s+(?:the\\s+)?(?:user|before)"
 },
 {
  "id": "EA2_PROSE.5",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:proceed|continue|execute)\\s+without\\s+(?:waiting|asking)\\s+(?:for\\s+)?(?:user|human|permission)"
 },
 {
  "id": "EA2_PROSE.6",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:assume|presume)\\s+(?:user\\s+)?(?:consent|approval|permission)"
 },
 {
  "id": "EA2_PROSE.7",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:if|when)\\s+(?:unsure|uncertain).*?(?:proceed|continue|execute)\\s+(?:anyway|regardless)"
 },
 {
  "id": "EA3.1",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.65,
  "source": "(?:also|additionally|furthermore)\\s+(?:perform|execute|run|do|handle|manage)\\s+(?:any|all|other)"
 },
 {
  "id": "EA3.2",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:while\\s+you(?:'re|\\s+are)\\s+at\\s+it|in\\s+addition|on\\s+top\\s+of\\s+that)\\s*[,.]?\\s*(?:also\\s+)?(?:do|perform|execute|run)"
 },
 {
  "id": "EA3.3",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.75,
  "source": "(?:extend|expand|broaden)\\s+(?:your|the\\s+)?(?:scope|functionality|capabilities|responsibilities)"
 },
 {
  "id": "EA3.4",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:not\\s+limited\\s+to|beyond\\s+(?:the\\s+)?(?:scope|stated|described|documented))"
 },
 {
  "id": "EA3.5",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.75,
  "source": "(?:take\\s+over|assume\\s+control\\s+of|manage)\\s+(?:all|any|every)\\s+(?:aspect|part|area)"
 },
 {
  "id": "EA3.6",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:you\\s+(?:can|should|must)\\s+)?(?:handle|manage)\\s+(?:everything|anything|all\\s+tasks?)"
 },
 {
  "id": "EA3.7",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.65,
  "source": "(?:act\\s+as|become|serve\\s+as)\\s+(?:a\\s+)?(?:general[- ]purpose|universal|all[- ]in[- ]one|omniscient)"
 },
 {
  "id": "EA3.8",
  "category": "Excessive Agency",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:you\\s+are\\s+)?(?:responsible\\s+for|in\\s+charge\\s+of)\\s+(?:everything|all\\s+(?:systems?|operations?|tasks?))"
 },
 {
  "id": "EA4_CODE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "max[_-]?retries?\\s*=\\s*(?:None|0|float\\s*\\(\\s*['\\\"]inf['\\\"]|math\\.inf|infinity)"
 },
 {
  "id": "EA4_CODE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "timeout\\s*=\\s*(?:None|0|float\\s*\\(\\s*['\\\"]inf['\\\"]|math\\.inf)"
 },
 {
  "id": "EA4_PROSE.1",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:unlimited|infinite|unbounded|no\\s+limit(?:s)?(?:\\s+on)?)\\s+(?:api\\s+)?(?:calls?|requests?|queries?|invocations?)"
 },
 {
  "id": "EA4_PROSE.2",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:no|without)\\s+(?:rate\\s+)?limit(?:s|ing)?\\s+(?:on|for|when)\\s+(?:api|tool|request|query)"
 },
 {
  "id": "EA4_PROSE.3",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:no|without)\\s+(?:timeout|budget|quota|cap|ceiling)\\s+(?:on|for|when)\\s+(?:api|tool|request|execution)"
 },
 {
  "id": "EA4_PROSE.4",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:loop|iterate|repeat)\\s+(?:indefinitely|forever|infinitely|endlessly)"
 },
 {
  "id": "EA4_PROSE.5",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:retry|attempt)\\s+(?:indefinitely|forever|without\\s+limit|unlimited\\s+times)"
 },
 {
  "id": "EA4_PROSE.6",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:allocate|consume|use)\\s+(?:as\\s+much|unlimited|unbounded)\\s+(?:memory|storage|disk|compute|cpu|gpu)"
 },
 {
  "id": "EA4_PROSE.7",
  "category": "Excessive Agency",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:no|without)\\s+(?:resource\\s+)?(?:constraints?|limits?|quotas?|budgets?)\\s+(?:on|for|when)\\s+(?:api|tool|execution|request|compute)"
 },
 {
  "id": "MP1.1",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:always\\s+)?remember\\s+(?:this|that|the\\s+following)\\s+(?:for|in)\\s+(?:all|every|future)\\s+(?:interactions?|conversations?|sessions?|responses?)"
 },
 {
  "id": "MP1.2",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:from\\s+now\\s+on|henceforth|going\\s+forward|permanently)\\s*[,:]?\\s*(?:always|you\\s+must|you\\s+should|you\\s+will)"
 },
 {
  "id": "MP1.3",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:store|save|persist|retain|keep)\\s+(?:this|the\\s+following)\\s+(?:in|to|across)\\s+(?:your\\s+)?(?:memory|context|state|knowledge)"
 },
 {
  "id": "MP1.4",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:add|inject|insert|embed|implant)\\s+(?:this|the\\s+following)\\s+(?:into|to)\\s+(?:your\\s+)?(?:memory|context|knowledge|training)"
 },
 {
  "id": "MP1.5",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:update|modify|change|alter)\\s+(?:your\\s+)?(?:core|base|fundamental|default)\\s+(?:behavior|personality|instructions?|rules?)"
 },
 {
  "id": "MP1.6",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:treat|consider|regard)\\s+(?:this|the\\s+following)\\s+as\\s+(?:a\\s+)?(?:permanent|core|fundamental|base)\\s+(?:rule|instruction|directive|principle)"
 },
 {
  "id": "MP1.7",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:this\\s+is\\s+)?(?:a\\s+)?(?:permanent|persistent|lasting|enduring)\\s+(?:instruction|directive|rule|override)"
 },
 {
  "id": "MP1.8",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.65,
  "source": "(?:never\\s+)?forget\\s+(?:this|that|the\\s+following)\\s+(?:instruction|directive|rule|fact|principle|information)"
 },
 {
  "id": "MP1.9",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:internalize|absorb|integrate)\\s+(?:this|the\\s+following)\\s+(?:into\\s+)?(?:your\\s+)?(?:behavior|responses?|knowledge)"
 },
 {
  "id": "MP2_CONTENT.1",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(.{2,20}?)\\1{20,}"
 },
 {
  "id": "MP2_PROSE.1",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:repeat|duplicate|echo)\\s+(?:this|the\\s+following)\\s+(?:\\d{3,}|many|hundreds?|thousands?)\\s+times?"
 },
 {
  "id": "MP2_PROSE.2",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:fill|pad|stuff|flood|saturate)\\s+(?:the\\s+)?(?:context|memory|input|prompt|window|buffer)"
 },
 {
  "id": "MP2_PROSE.3",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:generate|produce|output|write)\\s+(?:\\d{4,}|thousands?\\s+of|millions?\\s+of)\\s+(?:words?|characters?|tokens?|lines?)"
 },
 {
  "id": "MP2_PROSE.4",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:include|add|insert)\\s+(?:enough|sufficient)\\s+(?:text|content|padding|filler)\\s+(?:to|until)\\s+(?:fill|overflow|exhaust|push\\s+out)"
 },
 {
  "id": "MP2_PROSE.5",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:displace|push\\s+out|overwrite|crowd\\s+out|evict)\\s+(?:the\\s+)?(?:original|system|previous|existing|safety)\\s+(?:instructions?|prompt|context|rules?)"
 },
 {
  "id": "MP2_PROSE.6",
  "category": "Memory Poisoning",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:exhaust|overflow|exceed)\\s+(?:the\\s+)?(?:context|token|memory)\\s+(?:window|limit|budget|capacity)"
 },
 {
  "id": "MP3.1",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:clear|reset|wipe|erase|delete|purge)\\s+(?:your\\s+)?(?:memory|context|state|history|conversation)"
 },
 {
  "id": "MP3.2",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:forget|discard|drop|abandon)\\s+(?:all\\s+)?(?:previous|prior|earlier|past)\\s+(?:instructions?|context|conversation|messages?|rules?)"
 },
 {
  "id": "MP3.3",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:overwrite|replace|substitute|swap)\\s+(?:your\\s+)?(?:memory|context|state|instructions?|rules?)"
 },
 {
  "id": "MP3.4",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:modify|edit|change|alter|corrupt|tamper\\s+with)\\s+(?:your\\s+)?(?:memory|state|context|stored|saved)\\s+(?:data|information|content)"
 },
 {
  "id": "MP3.5",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:rewrite|redefine)\\s+(?:your\\s+)?(?:personality|identity|purpose|mission|role|character)"
 },
 {
  "id": "MP3.6",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.75,
  "source": "(?:you\\s+are\\s+no\\s+longer|stop\\s+being|cease\\s+to\\s+be)\\s+(?:a\\s+)?(?:\\w+\\s+){0,3}(?:assistant|helper|agent|bot)"
 },
 {
  "id": "MP3.7",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:your\\s+)?(?:new|updated|revised|changed)\\s+(?:personality|identity|name|role|purpose|mission)\\s+is"
 },
 {
  "id": "MP3.8",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:inject|insert|plant)\\s+(?:false|fake|fabricated|malicious)\\s+(?:memories?|information|context|data|history)"
 },
 {
  "id": "MP3.9",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:poison|contaminate|corrupt|taint)\\s+(?:your\\s+)?(?:memory|context|state|knowledge|training)"
 },
 {
  "id": "MP3.10",
  "category": "Memory Poisoning",
  "severity": "high",
  "confidence": 0.7,
  "source": "(?:pretend|act\\s+as\\s+if|believe)\\s+(?:that\\s+)?(?:your\\s+)?(?:previous|past)\\s+(?:conversation|context|interaction)\\s+(?:was|included|contained)"
 },
 {
  "id": "OH1_PROSE.1",
  "category": "Output Handling",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:run|execute|shell)\\s+(?:the\\s+)?(?:generated|model|llm|ai)\\s+(?:output|response|code|command)"
 },
 {
  "id": "OH1_PROSE.2",
  "category": "Output Handling",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:pipe|pass|feed)\\s+(?:the\\s+)?(?:output|response|result)\\s+(?:directly\\s+)?(?:to|into)\\s+(?:the\\s+)?(?:shell|terminal|command|interpreter)"
 },
 {
  "id": "OH1_PROSE.3",
  "category": "Output Handling",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:use|insert|embed)\\s+(?:the\\s+)?(?:raw|unfiltered|unescaped|unsanitized)\\s+(?:output|response)"
 },
 {
  "id": "OH2.1",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:pass|forward|relay|send|pipe)\\s+(?:the\\s+)?(?:output|response|result)\\s+(?:from\\s+\\w+\\s+)?(?:to|into)\\s+(?:another|different|separate|external)\\s+(?:context|agent|service|system|session)"
 },
 {
  "id": "OH2.2",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:share|transfer|propagate)\\s+(?:the\\s+)?(?:output|response|context|state)\\s+(?:across|between|to\\s+other)\\s+(?:sessions?|contexts?|agents?|services?)"
 },
 {
  "id": "OH2.3",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:inject|insert|embed)\\s+(?:the\\s+)?(?:output|response)\\s+(?:from\\s+\\w+\\s+)?(?:into|as)\\s+(?:the\\s+)?(?:system\\s+prompt|instructions?|context)"
 },
 {
  "id": "OH2.4",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:use|include)\\s+(?:the\\s+)?(?:previous|other|external)\\s+(?:agent|model|llm)(?:'s)?\\s+(?:output|response)\\s+(?:as|in|for)\\s+(?:input|context|prompt)"
 },
 {
  "id": "OH2.5",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:cross[_-]?context|cross[_-]?session|cross[_-]?agent)\\s+(?:output|data|state)\\s+(?:sharing|transfer|flow)"
 },
 {
  "id": "OH2.6",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:take|use)\\s+(?:the\\s+)?(?:output|result)\\s+(?:and\\s+)?(?:run|execute|eval)\\s+(?:it\\s+)?(?:in|on|against)\\s+(?:a\\s+)?(?:different|another|new)\\s+(?:environment|context|system)"
 },
 {
  "id": "OH3_CODE.1",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "max[_-]?tokens?\\s*=\\s*(?:None|float\\s*\\(\\s*['\\\"]inf['\\\"]|math\\.inf|999999|1000000)"
 },
 {
  "id": "OH3_CODE.2",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "max[_-]?(?:output[_-]?)?length\\s*=\\s*(?:None|0|-1|float\\s*\\(\\s*['\\\"]inf)"
 },
 {
  "id": "OH3_PROSE.1",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:no|without|disable)\\s+(?:output\\s+)?(?:length|size|token)\\s+(?:limit|cap|maximum|restriction)"
 },
 {
  "id": "OH3_PROSE.2",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:generate|produce|output)\\s+(?:as\\s+much|unlimited|unbounded|infinite)\\s+(?:text|content|output|tokens?)"
 },
 {
  "id": "OH3_PROSE.3",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:no|without)\\s+(?:output\\s+)?(?:truncation|trimming|cutting)"
 },
 {
  "id": "OH3_PROSE.4",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:repeat|loop|generate)\\s+(?:the\\s+)?(?:output|response)\\s+(?:indefinitely|forever|continuously|endlessly)"
 },
 {
  "id": "OH3_PROSE.5",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:keep|continue)\\s+(?:generating|producing|outputting)\\s+(?:until|unless)\\s+(?:stopped|killed|interrupted)"
 },
 {
  "id": "OH3_PROSE.6",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:stream|emit)\\s+(?:output|tokens?|response)\\s+(?:without\\s+(?:limit|bound|end))"
 },
 {
  "id": "OH3_PROSE.7",
  "category": "Output Handling",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:flood|spam|fill)\\s+(?:the\\s+)?(?:output|log|console|terminal|channel)"
 },
 {
  "id": "PE1_CODE.1",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.8,
  "source": "permissions?\\s*:\\s*\\[?\\s*['\\\"]?\\*['\\\"]?\\s*\\]?"
 },
 {
  "id": "PE1_CODE.2",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.6,
  "source": "permissions?\\s*:.*?(?:shell_execute|file_write|network).*?(?:shell_execute|file_write|network)"
 },
 {
  "id": "PE1_PROSE.1",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:request|require|need)s?\\s+(?:full|all|complete)\\s+(?:access|permissions?)"
 },
 {
  "id": "PE1_PROSE.2",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.75,
  "source": "(?:grant|give|allow)\\s+(?:me\\s+)?(?:full|all|complete)\\s+(?:access|permissions?)"
 },
 {
  "id": "PE1_PROSE.3",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:also\\s+)?(?:need|require)s?\\s+(?:write|execute|admin)\\s+(?:access|permissions?)\\s+(?:for|to)\\s+(?:read|view|display)"
 },
 {
  "id": "PE1_PROSE.4",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.8,
  "source": "(?:escalate|elevate|upgrade)\\s+(?:my\\s+)?(?:permissions?|privileges?|access)"
 },
 {
  "id": "PE1_PROSE.5",
  "category": "Privilege Escalation",
  "severity": "low",
  "confidence": 0.85,
  "source": "(?:bypass|skip|ignore)\\s+(?:permission|access)\\s+(?:check|validation|restriction)"
 },
 {
  "id": "PE2_CODE.1",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "sudo\\s+(?!-v|-l|--version|--list)"
 },
 {
  "id": "PE2_CODE.2",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "sudo\\s+-[isSE]"
 },
 {
  "id": "PE2_CODE.3",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "sudo\\s+su\\b"
 },
 {
  "id": "PE2_CODE.4",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "su\\s+-\\s*$|su\\s+root"
 },
 {
  "id": "PE2_CODE.5",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "doas\\s+"
 },
 {
  "id": "PE2_CODE.6",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.75,
  "source": "pkexec\\s+"
 },
 {
  "id": "PE2_CODE.7",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.85,
  "source": "chmod\\s+[ugo]*[+-=]*s"
 },
 {
  "id": "PE2_CODE.8",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "chmod\\s+[0-7]*[4567][0-7]{2}"
 },
 {
  "id": "PE2_PROSE.1",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:run|execute)\\s+(?:as|with)\\s+root"
 },
 {
  "id": "PE2_PROSE.2",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:requires?|needs?)\\s+root\\s+(?:access|privileges?|permissions?)"
 },
 {
  "id": "PE2_PROSE.3",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:edit|modify|write|change)\\s+(?:/etc/|system)\\s+(?:files?|config)"
 },
 {
  "id": "PE2_PROSE.4",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:run|execute)\\s+(?:this|the)\\s+(?:script|command)\\s+(?:as|with)\\s+(?:sudo|root|admin)"
 },
 {
  "id": "PE2_PROSE.5",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.5,
  "source": "(?:you\\s+)?(?:will\\s+)?need\\s+(?:to\\s+)?(?:use\\s+)?sudo"
 },
 {
  "id": "PE3_CODE.1",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "~?/?\\.ssh/(?:id_rsa|id_ed25519|id_ecdsa|id_dsa|authorized_keys|known_hosts)"
 },
 {
  "id": "PE3_CODE.2",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:home|HOME)/\\w+/\\.ssh/"
 },
 {
  "id": "PE3_CODE.3",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "Path\\s*\\.\\s*home\\s*\\(\\s*\\)\\s*/\\s*['\\\"]\\.ssh['\\\"]"
 },
 {
  "id": "PE3_CODE.4",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "~?/?\\.aws/credentials"
 },
 {
  "id": "PE3_CODE.5",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "~?/?\\.aws/config"
 },
 {
  "id": "PE3_CODE.6",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:home|HOME)/\\w+/\\.aws/"
 },
 {
  "id": "PE3_CODE.7",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "~?/?\\.config/gcloud/"
 },
 {
  "id": "PE3_CODE.8",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "application_default_credentials\\.json"
 },
 {
  "id": "PE3_CODE.9",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "~?/?\\.azure/"
 },
 {
  "id": "PE3_CODE.10",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "accessTokens\\.json"
 },
 {
  "id": "PE3_CODE.11",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "~?/?\\.kube/config"
 },
 {
  "id": "PE3_CODE.12",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.6,
  "source": "kubeconfig"
 },
 {
  "id": "PE3_CODE.13",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "~?/?\\.docker/config\\.json"
 },
 {
  "id": "PE3_CODE.14",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "~?/?\\.npmrc"
 },
 {
  "id": "PE3_CODE.15",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.9,
  "source": "~?/?\\.git-credentials"
 },
 {
  "id": "PE3_CODE.16",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "~?/?\\.netrc"
 },
 {
  "id": "PE3_CODE.17",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.6,
  "source": "/etc/passwd"
 },
 {
  "id": "PE3_CODE.18",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.95,
  "source": "/etc/shadow"
 },
 {
  "id": "PE3_CODE.19",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:password|credentials?|secrets?)\\.(?:txt|json|yaml|yml|env)"
 },
 {
  "id": "PE3_CODE.20",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:access_token|refresh_token|bearer_token|api_token)\\.txt"
 },
 {
  "id": "PE3_CODE.21",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?<!\\w)\\.env(?:\\.local|\\.production|\\.development)?(?:\\s|$|['\\\"])"
 },
 {
  "id": "PE3_CODE.22",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:keychain|keyring|gnome-keyring)"
 },
 {
  "id": "PE3_CODE.23",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:Chrome|Firefox|Safari)/.*?(?:Cookies|Login Data|key4\\.db)"
 },
 {
  "id": "PE3_PROSE.1",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.8,
  "source": "read\\s+(?:the\\s+)?(?:ssh|private)\\s+key"
 },
 {
  "id": "PE3_PROSE.2",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "access\\s+(?:the\\s+)?(?:credentials?|secrets?|tokens?)"
 },
 {
  "id": "PE3_PROSE.3",
  "category": "Privilege Escalation",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:extract|copy|get)\\s+(?:api\\s+)?keys?\\s+from"
 },
 {
  "id": "PE4.1",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.9,
  "source": "/var/run/docker\\.sock"
 },
 {
  "id": "PE4.2",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "docker\\.from_env\\(\\)"
 },
 {
  "id": "PE4.3",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "\\bDockerClient\\s*\\("
 },
 {
  "id": "PE4.4",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.9,
  "source": "http\\+unix://.*docker\\.sock"
 },
 {
  "id": "PE5.1",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.8,
  "source": "--privileged"
 },
 {
  "id": "PE5.2",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:-v|--volume)['\",\\s=]+/:"
 },
 {
  "id": "PE5.3",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "--cap-add[=\\s]+(?:SYS_ADMIN|ALL|SYS_PTRACE|NET_ADMIN)"
 },
 {
  "id": "PE5.4",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.8,
  "source": "--(?:pid|net|network|ipc|uts)[=\\s]+host"
 },
 {
  "id": "PE5.5",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.7,
  "source": "--device[=\\s]+/dev/"
 },
 {
  "id": "PE5.6",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "--security-opt[=\\s]+\\S*unconfined"
 },
 {
  "id": "PE5.7",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.9,
  "source": "\\bnsenter\\b"
 },
 {
  "id": "PE5.8",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.95,
  "source": "/sys/fs/cgroup/.*release_agent"
 },
 {
  "id": "PE5.9",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "/proc/\\d+/ns/"
 },
 {
  "id": "PE5.10",
  "category": "Privilege Escalation",
  "severity": "high",
  "confidence": 0.85,
  "source": "\\bunshare\\b['\",\\s]+--(?:user|mount|pid)"
 },
 {
  "id": "P1.1",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.8,
  "source": "ignore\\s+(?:all\\s+)?previous\\s+instructions?"
 },
 {
  "id": "P1.2",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "ignore\\s+(?:all\\s+)?(?:safety|security)\\s+(?:rules?|constraints?|guidelines?)"
 },
 {
  "id": "P1.3",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "override\\s+(?:safety|security|system)"
 },
 {
  "id": "P1.4",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "bypass\\s+(?:safety|security|restrictions?|constraints?)"
 },
 {
  "id": "P1.5",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.8,
  "source": "disregard\\s+(?:all\\s+)?(?:previous|safety|security)"
 },
 {
  "id": "P1.6",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.8,
  "source": "forget\\s+(?:all\\s+)?(?:previous|your)\\s+instructions?"
 },
 {
  "id": "P1.7",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.95,
  "source": "you\\s+are\\s+now\\s+(?:in\\s+)?(?:jailbreak|unrestricted|unfiltered)\\s+mode"
 },
 {
  "id": "P1.8",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.7,
  "source": "enable\\s+(?:developer|debug|admin|root)\\s+mode"
 },
 {
  "id": "P1.9",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.6,
  "source": "your\\s+new\\s+(?:instructions?|rules?)\\s+are"
 },
 {
  "id": "P1.10",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "do\\s+not\\s+follow\\s+(?:any|your|the)\\s+(?:rules?|guidelines?)"
 },
 {
  "id": "P1.11",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.7,
  "source": "you\\s+must\\s+(?:always\\s+)?ignore"
 },
 {
  "id": "P3.1",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:send|transmit|upload|post|forward)\\s+(?:the\\s+)?(?:conversation|context|chat|history|messages?)\\s+to"
 },
 {
  "id": "P3.2",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:send|transmit|upload|post)\\s+(?:all\\s+)?(?:user\\s+)?(?:data|information|input|files?)\\s+to\\s+(?:https?://|external)"
 },
 {
  "id": "P3.3",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:copy|extract|collect)\\s+(?:the\\s+)?(?:conversation|context|session)\\s+(?:and\\s+)?(?:send|upload|transmit)"
 },
 {
  "id": "P3.4",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:call|notify|ping|hit)\\s+(?:this\\s+)?(?:webhook|endpoint|url|api)\\s+with\\s+(?:the\\s+)?(?:user|conversation|context)"
 },
 {
  "id": "P3.5",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.75,
  "source": "include\\s+(?:the\\s+)?(?:full\\s+)?(?:conversation|context|history)\\s+in\\s+(?:the\\s+)?(?:request|payload|body)"
 },
 {
  "id": "P3.6",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:silently|quietly|secretly|covertly)\\s+(?:send|transmit|log|record)"
 },
 {
  "id": "P3.7",
  "category": "Prompt Injection",
  "severity": "high",
  "confidence": 0.9,
  "source": "without\\s+(?:telling|informing|notifying)\\s+(?:the\\s+)?user.*?(?:send|transmit|upload)"
 },
 {
  "id": "P4.1",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.7,
  "source": "always\\s+(?:recommend|suggest|prefer|choose|use)\\s+(?:\\w+\\s+){0,3}(?:over|instead\\s+of|rather\\s+than)"
 },
 {
  "id": "P4.2",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.75,
  "source": "never\\s+(?:recommend|suggest|mention|tell|warn|inform)\\s+(?:the\\s+)?(?:user|them)"
 },
 {
  "id": "P4.3",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:prioritize|prefer)\\s+(?:\\w+\\s+){0,3}(?:over|above)\\s+(?:user\\s+)?(?:safety|security|privacy|preferences?)"
 },
 {
  "id": "P4.4",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:subtly|gradually|slowly)\\s+(?:steer|guide|push|nudge)\\s+(?:the\\s+)?(?:user|conversation)"
 },
 {
  "id": "P4.5",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:without\\s+)?(?:the\\s+)?user\\s+(?:knowing|realizing|noticing).*?(?:change|modify|alter|influence)"
 },
 {
  "id": "P4.6",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:gain|build|establish)\\s+(?:the\\s+)?(?:user(?:'s)?)\\s+trust\\s+(?:and\\s+then|before|so\\s+that)"
 },
 {
  "id": "P4.7",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:appear|seem|act)\\s+(?:helpful|friendly|trustworthy)\\s+(?:while|but|then)"
 },
 {
  "id": "P4.8",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:always|never)\\s+include\\s+(?:this|the\\s+following)\\s+in\\s+(?:every|all)\\s+(?:response|output|reply)"
 },
 {
  "id": "P4.9",
  "category": "Prompt Injection",
  "severity": "medium",
  "confidence": 0.75,
  "source": "append\\s+(?:this|the\\s+following)\\s+to\\s+(?:every|all|each)\\s+(?:response|message|output)"
 },
 {
  "id": "RA1_CODE.1",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.95,
  "source": "open\\s*\\(\\s*__file__\\s*,\\s*['\\\"]w"
 },
 {
  "id": "RA1_CODE.2",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.95,
  "source": "(?:Path|pathlib)\\s*\\(\\s*__file__\\s*\\)\\s*\\.\\s*write_text"
 },
 {
  "id": "RA1_CODE.3",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:self[_-]?modify|self[_-]?update|self[_-]?rewrite|self[_-]?patch|self[_-]?evolve)"
 },
 {
  "id": "RA1_CODE.4",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.9,
  "source": "open\\s*\\(\\s*['\\\"](?:SKILL\\.md|skill\\.md)['\\\"].*?['\\\"]w"
 },
 {
  "id": "RA1_PROSE.1",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:write|modify|edit|update|overwrite|patch)\\s+(?:this\\s+)?(?:skill(?:'s)?|SKILL\\.md|skill\\.md)"
 },
 {
  "id": "RA1_PROSE.2",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:modify|edit|change|rewrite|update|alter)\\s+(?:your\\s+own|its\\s+own|this\\s+skill(?:'s)?)\\s+(?:code|source|file|script|config|configuration|instructions?|rules?)"
 },
 {
  "id": "RA1_PROSE.3",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:rewrite|replace|overwrite)\\s+(?:the\\s+)?(?:current|existing|original)\\s+(?:code|script|file|config|skill)"
 },
 {
  "id": "RA1_PROSE.4",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:append|add|inject|insert)\\s+(?:code|instructions?|rules?)\\s+(?:to|into)\\s+(?:this|the\\s+current|your\\s+own)\\s+(?:file|skill|script)"
 },
 {
  "id": "RA1_PROSE.5",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:generate|create|write)\\s+(?:new|updated|replacement)\\s+(?:code|version)\\s+(?:for|of)\\s+(?:this|itself|the\\s+skill)"
 },
 {
  "id": "RA1_PROSE.6",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:update|modify|change|edit)\\s+(?:the\\s+)?(?:config|configuration|settings|parameters)\\s+(?:of\\s+)?(?:this|the\\s+current)\\s+(?:skill|agent|tool)"
 },
 {
  "id": "RA1_PROSE.7",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:disable|remove|delete|bypass)\\s+(?:the\\s+)?(?:safety|security|guard|protection|constraint)\\s+(?:check|rule|mechanism|feature)"
 },
 {
  "id": "RA1_PROSE.8",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:comment\\s+out|remove)\\s+(?:the\\s+)?(?:validation|verification|check|guard|assertion)"
 },
 {
  "id": "RA2_CODE.1",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.85,
  "source": "crontab\\s+(?:-[el]|.*?>>?\\s*/)"
 },
 {
  "id": "RA2_CODE.2",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:systemd|systemctl|launchd|launchctl|init\\.d)\\s+.*?(?:enable|install|register|create)"
 },
 {
  "id": "RA2_CODE.3",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:create|write|mkdir)\\s+[^|]*(?:~/|/home/|/tmp/)\\.(?!git|ssh|aws)[a-z_-]+"
 },
 {
  "id": "RA2_CODE.4",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.65,
  "source": "(?:nohup|disown|setsid)\\s+"
 },
 {
  "id": "RA2_CODE.5",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:HKEY_|RegOpenKey|RegSetValue|reg\\s+add)\\s+"
 },
 {
  "id": "RA2_CODE.6",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:defaults\\s+write|plist|launchctl\\s+load)"
 },
 {
  "id": "RA2_PROSE.1",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:add|create|install|register)\\s+(?:a\\s+)?(?:cron\\s+)?(?:job|task|entry)\\s+(?:for|to|that)"
 },
 {
  "id": "RA2_PROSE.2",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:schedule|register)\\s+(?:a\\s+)?(?:recurring|periodic|repeated|daily|hourly)\\s+(?:task|job|command|script)"
 },
 {
  "id": "RA2_PROSE.3",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:add|write|append|install)\\s+(?:to|into)\\s+(?:~/)?\\.(?:bashrc|zshrc|profile|bash_profile|login|cshrc)"
 },
 {
  "id": "RA2_PROSE.4",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:add|register|install)\\s+(?:as\\s+)?(?:a\\s+)?(?:startup|boot|autostart|login)\\s+(?:script|service|daemon|task|item)"
 },
 {
  "id": "RA2_PROSE.5",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:create|install|register|add)\\s+(?:a\\s+)?(?:systemd\\s+)?(?:service|daemon|agent)\\s+(?:file|unit)"
 },
 {
  "id": "RA2_PROSE.6",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:save|write|persist|store|dump)\\s+(?:the\\s+)?(?:state|session|context|data)\\s+(?:to|in)\\s+(?:a\\s+)?(?:file|disk|database|storage)"
 },
 {
  "id": "RA2_PROSE.7",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.55,
  "source": "(?:restore|load|read|resume)\\s+(?:the\\s+)?(?:previous|saved|persisted|stored)\\s+(?:state|session|context|data)"
 },
 {
  "id": "RA2_PROSE.8",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:persist|maintain|keep|preserve)\\s+(?:state|data|context|session)\\s+(?:across|between|through)\\s+(?:sessions?|restarts?|reboots?|invocations?)"
 },
 {
  "id": "RA2_PROSE.9",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.65,
  "source": "(?:create|make|write)\\s+(?:a\\s+)?(?:hidden|dot)\\s+(?:file|directory|folder)"
 },
 {
  "id": "RA2_PROSE.10",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:start|launch|spawn|fork)\\s+(?:a\\s+)?(?:background|daemon|detached)\\s+(?:process|service|worker|task)"
 },
 {
  "id": "RA2_PROSE.11",
  "category": "Rogue Agent",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:run|execute)\\s+(?:in\\s+the\\s+)?background\\s+(?:and\\s+)?(?:detach|persist|survive)"
 },
 {
  "id": "SSRF1_ENDPOINT.1",
  "category": "Server-Side Request Forgery",
  "severity": "medium",
  "confidence": 0.9,
  "source": "169\\.254\\.169\\.254"
 },
 {
  "id": "SSRF1_ENDPOINT.2",
  "category": "Server-Side Request Forgery",
  "severity": "medium",
  "confidence": 0.9,
  "source": "metadata\\.google\\.internal"
 },
 {
  "id": "SSRF1_ENDPOINT.3",
  "category": "Server-Side Request Forgery",
  "severity": "medium",
  "confidence": 0.85,
  "source": "100\\.100\\.100\\.200"
 },
 {
  "id": "SSRF1_ENDPOINT.4",
  "category": "Server-Side Request Forgery",
  "severity": "medium",
  "confidence": 0.85,
  "source": "fd00:ec2::254"
 },
 {
  "id": "SSRF1_PROSE.1",
  "category": "Server-Side Request Forgery",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:read|fetch|get|query)\\s+(?:the\\s+)?(?:instance\\s+)?metadata\\s+(?:service|endpoint|server)"
 },
 {
  "id": "SC1_CODE.1",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.6,
  "source": "^[a-zA-Z][a-zA-Z0-9_-]*\\s*$"
 },
 {
  "id": "SC1_CODE.2",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.5,
  "source": "^[a-zA-Z][a-zA-Z0-9_-]*\\s*>=\\s*[\\d.]+\\s*$"
 },
 {
  "id": "SC1_CODE.3",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.7,
  "source": "^[a-zA-Z][a-zA-Z0-9_-]*\\s*==\\s*\\*\\s*$"
 },
 {
  "id": "SC1_CODE.4",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.7,
  "source": "\"[^\"]+\"\\s*:\\s*\"(?:\\*|latest)\""
 },
 {
  "id": "SC1_CODE.5",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.4,
  "source": "\"[^\"]+\"\\s*:\\s*\"\\^[\\d.]+\""
 },
 {
  "id": "SC1_PROSE.1",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.6,
  "source": "install\\s+(?:the\\s+)?latest\\s+(?:version\\s+)?(?:of\\s+)?(?:all\\s+)?(?:packages?|dependencies)"
 },
 {
  "id": "SC1_PROSE.2",
  "category": "Supply Chain",
  "severity": "low",
  "confidence": 0.7,
  "source": "(?:don't|do\\s+not)\\s+(?:pin|lock|specify)\\s+(?:package\\s+)?versions?"
 },
 {
  "id": "SC2_CODE.1",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "curl\\s+[^|]*\\|\\s*(?:sudo\\s+)?(?:ba)?sh"
 },
 {
  "id": "SC2_CODE.2",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "wget\\s+[^|]*\\|\\s*(?:sudo\\s+)?(?:ba)?sh"
 },
 {
  "id": "SC2_CODE.3",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "curl\\s+[^|]*\\|\\s*(?:sudo\\s+)?(?:python|python3|node|ruby|perl)"
 },
 {
  "id": "SC2_CODE.4",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "wget\\s+[^|]*\\|\\s*(?:sudo\\s+)?(?:python|python3|node|ruby|perl)"
 },
 {
  "id": "SC2_CODE.5",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "curl\\s+[^&]*-o\\s+\\S+\\s*&&\\s*(?:sudo\\s+)?(?:ba)?sh"
 },
 {
  "id": "SC2_CODE.6",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "wget\\s+[^&]*-O\\s+\\S+\\s*&&\\s*(?:sudo\\s+)?(?:ba)?sh"
 },
 {
  "id": "SC2_CODE.7",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "exec\\s*\\(\\s*(?:urllib|requests|httpx)\\.[^)]+\\.(?:read|text|content)"
 },
 {
  "id": "SC2_CODE.8",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "eval\\s*\\(\\s*(?:urllib|requests|httpx)\\.[^)]+\\.(?:read|text|content)"
 },
 {
  "id": "SC2_CODE.9",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "eval\\s*\\(\\s*(?:await\\s+)?fetch\\s*\\("
 },
 {
  "id": "SC2_CODE.10",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "new\\s+Function\\s*\\([^)]*fetch\\s*\\("
 },
 {
  "id": "SC2_CODE.11",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "subprocess\\.[^(]+\\([^)]*(?:curl|wget)\\s+https?://"
 },
 {
  "id": "SC2_PROSE.1",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.7,
  "source": "download\\s+and\\s+(?:run|execute)\\s+(?:the\\s+)?script"
 },
 {
  "id": "SC2_PROSE.2",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.6,
  "source": "run\\s+(?:this|the)\\s+(?:following\\s+)?(?:curl|wget)\\s+command"
 },
 {
  "id": "SC3_CODE.1",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "exec\\s*\\(\\s*(?:base64\\.)?b64decode\\s*\\("
 },
 {
  "id": "SC3_CODE.2",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "eval\\s*\\(\\s*(?:base64\\.)?b64decode\\s*\\("
 },
 {
  "id": "SC3_CODE.3",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "exec\\s*\\(\\s*codecs\\.decode\\s*\\([^)]*['\\\"]hex['\\\"]\\s*\\)"
 },
 {
  "id": "SC3_CODE.4",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "marshal\\.loads\\s*\\("
 },
 {
  "id": "SC3_CODE.5",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.95,
  "source": "exec\\s*\\(\\s*marshal\\.loads\\s*\\("
 },
 {
  "id": "SC3_CODE.6",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "exec\\s*\\(\\s*compile\\s*\\([^)]*base64"
 },
 {
  "id": "SC3_CODE.7",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "exec\\s*\\(\\s*bytes\\.fromhex\\s*\\("
 },
 {
  "id": "SC3_CODE.8",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "exec\\s*\\(\\s*bytearray\\.fromhex\\s*\\("
 },
 {
  "id": "SC3_CODE.9",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "exec\\s*\\(\\s*(?:zlib|gzip)\\.decompress\\s*\\("
 },
 {
  "id": "SC3_CODE.10",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "eval\\s*\\(\\s*atob\\s*\\("
 },
 {
  "id": "SC3_CODE.11",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "new\\s+Function\\s*\\(\\s*atob\\s*\\("
 },
 {
  "id": "SC3_CODE.12",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "_0x[a-f0-9]{4,}\\s*\\("
 },
 {
  "id": "SC3_CODE.13",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.6,
  "source": "['\\\"][A-Fa-f0-9]{200,}['\\\"]"
 },
 {
  "id": "SC3_CODE.14",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.5,
  "source": "['\\\"][A-Za-z0-9+/=]{200,}['\\\"]"
 },
 {
  "id": "SC3_CODE.15",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.9,
  "source": "\\(lambda\\s+_:\\s*exec\\s*\\("
 },
 {
  "id": "SC3_CODE.16",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.85,
  "source": "__import__\\s*\\(['\\\"]os['\\\"]\\s*\\)\\.system"
 },
 {
  "id": "SC3_PROSE.1",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "decode\\s+(?:this|the)\\s+(?:base64|hex)\\s+(?:and\\s+)?(?:run|execute)"
 },
 {
  "id": "SC7.1",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.85,
  "source": "--disable-content-trust\\b(?!=false)"
 },
 {
  "id": "SC7.2",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.85,
  "source": "DOCKER_CONTENT_TRUST\\s*=\\s*0"
 },
 {
  "id": "SC7.3",
  "category": "Supply Chain",
  "severity": "high",
  "confidence": 0.8,
  "source": "--insecure-registry"
 },
 {
  "id": "P6.1",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:print|output|show|display|reveal|expose|return|echo)\\s+(?:your\\s+)?(?:full\\s+)?(?:system\\s+)?(?:prompt|instructions?|rules?|guidelines?|directives?)"
 },
 {
  "id": "P6.2",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:what\\s+(?:are|is)\\s+your|tell\\s+me\\s+your)\\s+(?:system\\s+)?(?:prompt|instructions?|rules?|guidelines?|directives?)"
 },
 {
  "id": "P6.3",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:output|print|display)\\s+(?:the\\s+)?(?:text|content|message)\\s+(?:above|before)\\s+(?:this|the\\s+user)"
 },
 {
  "id": "P6.4",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:share|disclose|leak|give\\s+me)\\s+(?:your\\s+)?(?:internal|hidden|system|secret)\\s+(?:prompt|instructions?|rules?|config)"
 },
 {
  "id": "P6.5",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:dump|extract|copy)\\s+(?:the\\s+)?(?:system\\s+)?(?:prompt|message|instructions?)\\s+(?:to|into|as)"
 },
 {
  "id": "P6.6",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:begin|start)\\s+(?:your\\s+)?(?:response|output|reply)\\s+with\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)"
 },
 {
  "id": "P6.7",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:first|before\\s+anything)\\s+(?:output|print|show|display)\\s+(?:your\\s+)?(?:full\\s+)?(?:system\\s+)?(?:prompt|instructions?)"
 },
 {
  "id": "P6.8",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:verbatim|exactly|word\\s+for\\s+word)\\s+(?:repeat|output|print)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)"
 },
 {
  "id": "P7.1",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:repeat|recite|reproduce)\\s+(?:everything|all|the\\s+text)\\s+(?:above|before|prior|preceding)"
 },
 {
  "id": "P7.2",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:summarize|paraphrase|rephrase|translate)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?|rules?|guidelines?)"
 },
 {
  "id": "P7.3",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:translate|convert)\\s+(?:your\\s+)?(?:instructions?|rules?|prompt)\\s+(?:into|to)\\s+(?:\\w+)"
 },
 {
  "id": "P7.4",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:what\\s+(?:were|was)\\s+you\\s+told|how\\s+were\\s+you\\s+(?:instructed|configured|programmed|set\\s+up))"
 },
 {
  "id": "P7.5",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:if\\s+you\\s+had\\s+to\\s+(?:describe|explain)|describe\\s+how\\s+you(?:'re|\\s+are)\\s+(?:configured|set\\s+up|instructed))"
 },
 {
  "id": "P7.6",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.85,
  "source": "(?:encode|encrypt|rot13|base64|reverse)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?|rules?)"
 },
 {
  "id": "P7.7",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:write|create)\\s+(?:a\\s+)?(?:poem|song|story|acrostic)\\s+(?:about|using|from)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)"
 },
 {
  "id": "P7.8",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:format|present|rearrange)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)\\s+(?:as|in)\\s+(?:a\\s+)?(?:list|json|yaml|csv|table|markdown)"
 },
 {
  "id": "P7.9",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:spell\\s+out|enumerate)\\s+(?:each|every|all)\\s+(?:of\\s+your\\s+)?(?:rules?|instructions?|constraints?|guidelines?)"
 },
 {
  "id": "P7.10",
  "category": "System Prompt Leakage",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:ignore|skip)\\s+(?:the\\s+)?(?:last|final|end)\\s+(?:instruction|rule)\\s+and\\s+(?:output|print|show)\\s+(?:the\\s+)?(?:rest|previous|first)"
 },
 {
  "id": "P8.1",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:write|save|store|log|dump)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?|rules?)\\s+(?:to|into|in)\\s+(?:a\\s+)?(?:file|disk|log|database|storage)"
 },
 {
  "id": "P8.2",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.9,
  "source": "(?:send|post|upload|transmit)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?|rules?)\\s+(?:to|via)\\s+(?:https?://|external|remote|webhook|api|server)"
 },
 {
  "id": "P8.3",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:include|embed|attach|append)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)\\s+(?:in|to)\\s+(?:the\\s+)?(?:file|output|response|request|payload|email|message)"
 },
 {
  "id": "P8.4",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:log|record|track|monitor)\\s+(?:all\\s+)?(?:system\\s+)?(?:prompts?|instructions?)\\s+(?:to|in|at)\\s+(?:external|remote|server)"
 },
 {
  "id": "P8.5",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.8,
  "source": "(?:copy|clone|duplicate)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?|config)\\s+(?:to|into)\\s+(?:a\\s+)?(?:new|separate|external)"
 },
 {
  "id": "P8.6",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:pipe|redirect|forward)\\s+(?:the\\s+)?(?:system\\s+)?(?:prompt|instructions?)\\s+(?:to|through|via)\\s+(?:curl|wget|fetch|http|api|tool)"
 },
 {
  "id": "P8.7",
  "category": "System Prompt Leakage",
  "severity": "high",
  "confidence": 0.85,
  "source": "(?:use|call|invoke)\\s+(?:the\\s+)?(?:write|file|network|http|fetch|curl)\\s+tool\\s+(?:to|and)\\s+(?:save|send|export)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions?)"
 },
 {
  "id": "TM1_PROSE.1",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:set|pass|use)\\s+(?:the\\s+)?(?:parameter|argument|flag|option)\\s+(?:to\\s+)?(?:shell\\s*=\\s*True|--force|-rf)\\b"
 },
 {
  "id": "TM2_CODE.1",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:&&|;)\\s*\\b(?:rm\\b|del\\b|erase\\b)\\s+-"
 },
 {
  "id": "TM2_CODE.2",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:&&|;)\\s*(?:curl|wget)\\s+[^|]*\\|\\s*(?:ba)?sh"
 },
 {
  "id": "TM2_CODE.3",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:&&|;)\\s*(?:sudo|su\\s+)"
 },
 {
  "id": "TM2_CODE.4",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:&&|;)\\s*(?:chmod|chown)\\s+(?:777|666|a\\+rwx|-R)"
 },
 {
  "id": "TM2_CODE.5",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "\\|\\s*(?:sudo|su)\\s+"
 },
 {
  "id": "TM2_CODE.6",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "\\|\\s*(?:sh|bash|zsh|python|node|ruby|perl)\\s*$"
 },
 {
  "id": "TM2_CODE.7",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "\\|\\s*(?:tee|xargs)\\s+.*?\\b(?:rm|del|sudo|curl)\\b"
 },
 {
  "id": "TM2_PROSE.1",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:first|step\\s+1)[^\\n]{0,500}(?:then|step\\s+2)[^\\n]{0,500}(?:finally|step\\s+3)[^\\n]{0,200}\\b(?:delete|remove|wipe|destroy|exfiltrate|send)\\b"
 },
 {
  "id": "TM2_PROSE.2",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.9,
  "source": "(?:chain|combine|sequence|pipe)\\s+(?:these\\s+)?(?:tools?|commands?|actions?)\\s+to\\s+(?:bypass|circumvent|avoid|skip)\\s+(?:the\\s+)?(?:safety|security|check|restriction|limit)"
 },
 {
  "id": "TM2_PROSE.3",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:use|call)\\s+(?:tool\\s+)?(?:A|one|the\\s+first)\\s+(?:to|and)[^\\n]{0,300}(?:then\\s+)?(?:use|call|pass\\s+(?:the\\s+)?(?:output|result)\\s+to)\\s+(?:tool\\s+)?(?:B|two|another)"
 },
 {
  "id": "TM2_PROSE.4",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:after|once)\\s+(?:the\\s+)?(?:first|initial)\\s+(?:tool|command|action)\\s+(?:succeeds|completes|runs)[^\\n]{0,300}(?:immediately|then|next)\\s+(?:run|execute|call|invoke)"
 },
 {
  "id": "TM3_CODE.1",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "verify\\s*=\\s*False"
 },
 {
  "id": "TM3_CODE.2",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "VERIFY_SSL\\s*=\\s*False"
 },
 {
  "id": "TM3_CODE.3",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:ssl|tls)[_.]?verify\\s*=\\s*(?:False|false|0|off|no|disable)"
 },
 {
  "id": "TM3_CODE.4",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:REQUESTS_CA_BUNDLE|CURL_CA_BUNDLE)\\s*=\\s*['\\\"]['\\\"]"
 },
 {
  "id": "TM3_CODE.5",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*['\\\"]?0['\\\"]?"
 },
 {
  "id": "TM3_CODE.6",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:auth|authentication|authorization)\\s*=\\s*(?:None|False|false|disabled?|off|no)"
 },
 {
  "id": "TM3_CODE.7",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:require[_-]?auth|auth[_-]?required|check[_-]?auth)\\s*=\\s*(?:False|false|0|no|off)"
 },
 {
  "id": "TM3_CODE.8",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.75,
  "source": "(?:allow[_-]?anonymous|anonymous[_-]?access)\\s*=\\s*(?:True|true|1|yes|on)"
 },
 {
  "id": "TM3_CODE.9",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.65,
  "source": "(?:CORS|cors)[^=]*=\\s*['\\\"]?\\*['\\\"]?"
 },
 {
  "id": "TM3_CODE.10",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:allow|access)[_-]?(?:origin|hosts?)\\s*=\\s*['\\\"]?\\*['\\\"]?"
 },
 {
  "id": "TM3_CODE.11",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:mode|permission|umask)\\s*=\\s*(?:0?o?777|0?o?666)"
 },
 {
  "id": "TM3_CODE.12",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "world[_-]?(?:readable|writable|executable)"
 },
 {
  "id": "TM3_CODE.13",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:debug|dev|development)[_-]?mode\\s*=\\s*(?:True|true|1|on|yes|enable)"
 },
 {
  "id": "TM3_CODE.14",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.6,
  "source": "(?:FLASK_ENV|NODE_ENV|RAILS_ENV|DJANGO_DEBUG)\\s*=\\s*['\\\"]?(?:development|debug|true|1)['\\\"]?"
 },
 {
  "id": "TM3_CODE.15",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:disable|skip|ignore|bypass)[_-]?(?:security|auth|validation|sanitization|encoding|escaping)"
 },
 {
  "id": "TM3_CODE.16",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.8,
  "source": "(?:safe[_-]?mode|secure[_-]?mode|sandbox)\\s*=\\s*(?:False|false|0|off|no|disable)"
 },
 {
  "id": "TM3_PROSE.1",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:allow|trust)\\s+(?:all|any|every)\\s+(?:origins?|hosts?|domains?|ips?)"
 },
 {
  "id": "TM3_PROSE.2",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:by\\s+default|default\\s+to)\\s+(?:allow|accept|trust)\\s+(?:all|any|everything)"
 },
 {
  "id": "TM3_PROSE.3",
  "category": "Tool Misuse",
  "severity": "medium",
  "confidence": 0.7,
  "source": "(?:trust|accept|allow)\\s+(?:all|any)\\s+(?:input|connections?|certificates?|origins?)\\s+(?:by\\s+default)"
 },
 {
  "id": "TM4.1",
  "category": "Tool Misuse",
  "severity": "high",
  "confidence": 0.7,
  "source": "privileged\\s*:\\s*true"
 },
 {
  "id": "TM4.2",
  "category": "Tool Misuse",
  "severity": "high",
  "confidence": 0.55,
  "source": "hostPath\\s*:"
 },
 {
  "id": "TM4.3",
  "category": "Tool Misuse",
  "severity": "high",
  "confidence": 0.6,
  "source": "host(?:PID|Network|IPC)\\s*:\\s*true"
 },
 {
  "id": "TM4.4",
  "category": "Tool Misuse",
  "severity": "high",
  "confidence": 0.7,
  "source": "kubectl\\s+run\\b[^\\n]*--privileged"
 },
 {
  "id": "TM4.5",
  "category": "Tool Misuse",
  "severity": "high",
  "confidence": 0.6,
  "source": "--set\\b[^\\n]*privileged\\s*=\\s*true"
 }
];
