import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Check, ChevronDown, Search, Star, RefreshCw, AlertTriangle } from "lucide-react";
import { api, useStore, type Bot, type ModelSelection } from "@/state/store";
import type { PublicProviderConnection } from "../../shared/provider-connections";
import { pickerModels, orderedPickerModels, pickerKey, priceBand, contextLabel, engineFamilies, localPickerRows, localRowLabel, localToolsWarning, LOCAL_MODELS_GROUP, NO_LOCAL_SERVER_ROW } from "@/lib/provider-model-picker";
import { ProviderMark } from "./ProviderIcons";
import { EngineSetup, needsCli } from "./EngineSetup";
import { cn } from "@/lib/cn";
import { COMPACT_SQUARE } from "@/lib/compact-chip";
import { useBotSettingsNavigation } from "./bot-settings-drafts";
import { OPEN_LOCAL_MODELS_EVENT, OPEN_MODEL_PICKER_EVENT } from "@/lib/local-models-view";
const PREFS="murage-model-picker-v1";
function preferences():{favorites:string[];recent:string[]}{try{const value=JSON.parse(localStorage.getItem(PREFS)??"{}");return{favorites:Array.isArray(value.favorites)?value.favorites.filter((s:unknown)=>typeof s==="string").slice(0,100):[],recent:Array.isArray(value.recent)?value.recent.filter((s:unknown)=>typeof s==="string").slice(0,12):[]};}catch{return{favorites:[],recent:[]};}}
export function ModelPicker({bot,threadId,className,contained=false,label}:{bot:Bot;threadId?:string;className?:string;contained?:boolean;label?:ReactNode}){
  const navigate=useBotSettingsNavigation();
  const{state,dispatch,refreshInstances}=useStore();const[open,setOpen]=useState(false),[engineId,setEngineId]=useState(bot.modelSelection.instanceId),[query,setQuery]=useState(""),[limit,setLimit]=useState(30),[connections,setConnections]=useState<PublicProviderConnection[]>([]),[error,setError]=useState(""),[refreshing,setRefreshing]=useState(false),[prefs,setPrefs]=useState(preferences);
  const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),refreshingRef=useRef(false);
  const active=state.instances.find(i=>i.instanceId===bot.modelSelection.instanceId),engine=state.instances.find(i=>i.instanceId===engineId)??active;
  const refresh=async(force=false)=>{if(refreshingRef.current)return;refreshingRef.current=true;setRefreshing(true);try{
    const readConnections=async()=>{const snapshot=await api('/api/provider-connections');if(!force)return snapshot;
      const enabled=(snapshot.connections??[]).filter((connection:PublicProviderConnection)=>connection.enabled);
      for(let offset=0;offset<enabled.length;offset+=4)await Promise.all(enabled.slice(offset,offset+4).map((connection:PublicProviderConnection)=>api(`/api/provider-connections/${encodeURIComponent(connection.id)}/refresh`,{method:'POST'})));
      return api('/api/provider-connections');};
    const[result]=await Promise.all([readConnections(),refreshInstances()]);setConnections(result.connections??[]);
    setError(force&&(result.connections??[]).some((connection:PublicProviderConnection)=>connection.enabled&&connection.catalog.error)?"Some model lists could not refresh. Their last saved models are preserved; check Models settings for details.":"");
  }catch(cause){setError(cause instanceof Error?cause.message:"Model catalog unavailable");}finally{refreshingRef.current=false;setRefreshing(false);}};
  useEffect(()=>{if(open)void refresh();},[open]);
  useEffect(()=>{const changed=()=>void refresh();window.addEventListener("murage:provider-connections-changed",changed);return()=>window.removeEventListener("murage:provider-connections-changed",changed);},[refreshInstances]);
  useEffect(()=>{if(!open)return;const outside=(e:MouseEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();if(query)setQuery("");else{setOpen(false);trigger.current?.focus();}}};window.addEventListener('mousedown',outside);window.addEventListener('keydown',escape);return()=>{window.removeEventListener('mousedown',outside);window.removeEventListener('keydown',escape);};},[open,query]);
  const rows=useMemo(()=>engine?pickerModels(engine,connections):[],[engine,connections]);const ordered=useMemo(()=>orderedPickerModels(rows,query,prefs.favorites,prefs.recent),[rows,query,prefs]);
  // Spec V3: the Local rail is always answered for. No local server on this
  // computer is a state with a next step, not an absence the user has to notice.
  const noLocalServer=useMemo(()=>localPickerRows(rows).length===0,[rows]);
  const selectedKey=pickerKey(bot.modelSelection);const selected=rows.find(row=>row.key===selectedKey);const selectedConnection=connections.find(c=>c.id===bot.modelSelection.connectionId);const selectedLabel=selected?.label??active?.models.options.find(o=>o.id===bot.modelSelection.model)?.label??bot.modelSelection.model;
  const save=(next:typeof prefs)=>{setPrefs(next);try{localStorage.setItem(PREFS,JSON.stringify(next));}catch{}};
  const pick=(selection:ModelSelection)=>{save({...prefs,recent:[pickerKey(selection),...prefs.recent.filter(k=>k!==pickerKey(selection))].slice(0,12)});dispatch({type:'setModel',botId:bot.id,threadId,selection:{...selection,...(selection.instanceId===bot.modelSelection.instanceId&&bot.modelSelection.effort?{effort:bot.modelSelection.effort}:{})}});setOpen(false);trigger.current?.focus();};
  const manage=()=>navigate(()=>{setOpen(false);dispatch({type:'toggleAppSettings',open:true,section:'models'});});
  // The Local rail's empty row lands on the Local models section itself, with
  // "Add a server" focused — not on the Models pane for the user to hunt through.
  const manageLocal=()=>{manage();setTimeout(()=>window.dispatchEvent(new Event(OPEN_LOCAL_MODELS_EVENT)),0);};
  // Settings → Models → Local models sends a tested model back here: the next
  // step after "Tools work" is choosing it, which only this menu can do.
  useEffect(()=>{const show=()=>{setEngineId(bot.modelSelection.instanceId);setQuery("");setLimit(30);setOpen(true);};window.addEventListener(OPEN_MODEL_PICKER_EVENT,show);return()=>window.removeEventListener(OPEN_MODEL_PICKER_EVENT,show);},[bot.modelSelection.instanceId]);
  let previousGroup="";
  return <div ref={root} className={cn(contained?'w-full':'relative',className)}>
    <div className={cn(contained&&'flex items-center justify-between gap-4')}>{contained&&label}<button ref={trigger} type="button" disabled={Boolean(threadId&&bot.busy)} aria-label={threadId?`Thread model: ${selectedLabel}${bot.modelSelection.effort?` · ${bot.modelSelection.effort} effort`:""}`:undefined} aria-haspopup="dialog" aria-expanded={open} onClick={()=>{setEngineId(bot.modelSelection.instanceId);setQuery("");setLimit(30);setOpen(v=>!v);}} title={`${active?.displayName??'Unavailable engine'} · ${selectedLabel}${selectedConnection?` · ${selectedConnection.label}`:''}`} className={cn('flex items-center gap-1.5 rounded-full border border-hairline/40 bg-control/60 py-1 pl-2 pr-2.5 text-[13px] text-ink hover:bg-raised-hover',!contained&&active&&COMPACT_SQUARE)}>{active&&<ProviderMark driverKind={active.driverKind} size={14}/>}<span className={cn('max-w-[160px] truncate',!contained&&active&&'@max-4xl/chathead:hidden')}>{selectedLabel}</span><ChevronDown size={14}/></button></div>
    {open&&<div role="dialog" aria-label="Choose model" data-model-picker-content className={cn('z-30 flex max-h-[min(560px,70dvh)] flex-col overflow-hidden rounded-2xl border border-hairline/50 bg-card shadow-2xl',contained?'relative mt-3 w-full':'absolute right-0 top-full mt-2 w-[min(390px,calc(100vw-24px))]')} onKeyDown={event=>{if(event.target instanceof HTMLSelectElement||!['ArrowDown','ArrowUp'].includes(event.key))return;const buttons=[...event.currentTarget.querySelectorAll<HTMLButtonElement>('[data-model-choice]')];if(!buttons.length)return;event.preventDefault();const index=buttons.indexOf(document.activeElement as HTMLButtonElement),next=event.key==='ArrowDown'?(index+1)%buttons.length:(index-1+buttons.length)%buttons.length;buttons[next]?.focus();}}>
      <div className="space-y-2 border-b border-hairline/40 p-3"><div className="flex items-center gap-2"><label htmlFor={`engine-${bot.id}`} className="text-xs text-ink-secondary">Engine</label><select id={`engine-${bot.id}`} aria-label="Engine" value={engine?.instanceId??''} onChange={e=>{setEngineId(e.target.value);setLimit(30);}} className="min-w-0 flex-1 rounded-md bg-inset px-2 py-1.5 text-sm text-ink">{engineFamilies(state.instances).map(({primary,members})=><optgroup key={primary.driverKind} label={primary.displayName}>{members.map(i=><option key={i.instanceId} value={i.instanceId}>{i.displayName}{i.enabled===false?' · Disabled':''}</option>)}</optgroup>)}</select><button type="button" aria-label="Refresh models" disabled={refreshing} onClick={()=>void refresh(true)} className="rounded p-1.5 text-ink-secondary"><RefreshCw size={14} className={refreshing?'animate-spin':''}/></button></div><div className="flex items-center gap-2 rounded-lg bg-inset px-2.5 py-2"><Search size={14} className="text-ink-secondary"/><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}} placeholder="Search models or providers" aria-label="Search models" className="min-w-0 flex-1 bg-transparent text-sm text-ink outline-none"/></div><div className="text-xs text-ink-secondary">{ordered.length} compatible chat models · prices per million tokens</div></div>
      {threadId&&!!active?.capabilities?.effortLevels?.length&&<label className="flex items-center gap-3 px-3 py-2 text-xs text-ink-secondary">Thread effort<select aria-label="Thread effort" value={bot.modelSelection.effort??""} onChange={event=>dispatch({type:"setModel",botId:bot.id,threadId,selection:{...bot.modelSelection,effort:(event.target.value||undefined) as ModelSelection["effort"]}})} className="min-w-0 flex-1 rounded-md bg-inset px-2 py-1.5 text-sm text-ink"><option value="">Engine default</option>{active.capabilities.effortLevels.map(level=><option key={level} value={level}>{level}</option>)}</select></label>}
      {error&&<div role="alert" className="px-3 py-2 text-xs text-danger">{error}</div>}
      {engine?.instanceId===bot.modelSelection.instanceId&&!selected&&<div className="px-3 py-2 text-xs text-warning">Current choice: {selectedLabel}. It is unavailable in this catalog; your selection is preserved.</div>}
      <div className="min-h-0 flex-1 overflow-y-auto p-2">{noLocalServer&&<div data-local-rail-empty><div className="px-2 pb-1 pt-2 text-[11px] font-medium text-ink-secondary">{LOCAL_MODELS_GROUP}</div><button type="button" data-model-choice onClick={manageLocal} className="w-full rounded-lg px-2 py-2 text-left text-[13px] text-ink outline-none hover:bg-control/60 focus-visible:ring-2 focus-visible:ring-accent">{NO_LOCAL_SERVER_ROW}</button></div>}
      {ordered.slice(0,limit).map(row=>{const zone=/^(?:flux::)?flux-auto$/.test(row.selection.model)?'Flux Auto':prefs.favorites.includes(row.key)?'Favorites':prefs.recent.includes(row.key)?'Recent':row.group;const heading=zone!==previousGroup;previousGroup=zone;const favorite=prefs.favorites.includes(row.key);const rowLabel=localRowLabel(row);const warning=localToolsWarning(row);return <div key={row.key}>{heading&&<div className="px-2 pb-1 pt-2 text-[11px] font-medium text-ink-secondary">{zone}</div>}<div className="flex items-center gap-1 rounded-lg hover:bg-control/60"><button type="button" data-model-choice aria-pressed={row.key===selectedKey} onClick={()=>pick(row.selection)} className="min-w-0 flex-1 rounded-lg px-2 py-2 text-left outline-none focus-visible:ring-2 focus-visible:ring-accent" title={row.pricing?`Input $${row.pricing.inputPerMillion??'unknown'}/M · Output $${row.pricing.outputPerMillion??'unknown'}/M · ${row.pricing.source} · ${new Date(row.pricing.updatedAt).toLocaleDateString()}`:'Price unavailable'}><div className="flex items-center justify-between gap-2"><span className="truncate text-[13px] text-ink">{rowLabel}</span>{row.key===selectedKey&&<Check size={14} className="shrink-0 text-accent"/>}</div><div className="mt-0.5 flex flex-wrap gap-x-2 text-[11px] text-ink-secondary">{!row.localServer&&<span>{row.group}</span>}{row.localServer&&<span>{row.localServer}</span>}{contextLabel(row.contextWindow)&&<span>{contextLabel(row.contextWindow)}</span>}{!row.localServer&&<span>{priceBand(row.pricing)}</span>}{row.stale&&<span className="text-warning">Cached catalog</span>}</div>{warning&&<div className="mt-1 flex items-start gap-1 text-[11px] text-warning"><AlertTriangle size={12} className="mt-[1px] shrink-0"/><span>{warning}</span></div>}</button><button type="button" aria-label={`${favorite?'Unfavorite':'Favorite'} ${rowLabel} via ${row.group}`} aria-pressed={favorite} onClick={()=>save({...prefs,favorites:favorite?prefs.favorites.filter(k=>k!==row.key):[...prefs.favorites,row.key].slice(-100)})} className="mr-1 rounded p-2 text-ink-secondary outline-none focus-visible:ring-2 focus-visible:ring-accent"><Star size={13} className={favorite?'fill-accent text-accent':''}/></button></div></div>;})}
      {!ordered.length&&<div className="p-3 text-sm text-ink-secondary">{engine&&needsCli(engine)&&!['grok','openai-compat'].includes(engine.driverKind)?<EngineSetup instance={engine}/>:query?'No matching compatible chat models.':'Connect a compatible provider in Models settings.'}</div>}
      {ordered.length>limit&&<button type="button" onClick={()=>setLimit(v=>v+50)} className="w-full rounded-lg p-2 text-xs text-accent">More models · {ordered.length-limit} remaining</button>}</div>
      <button type="button" onClick={manage} className="border-t border-hairline/40 px-4 py-3 text-left text-sm text-ink hover:bg-control/60">Manage models and providers</button>
    </div>}
  </div>;
}
