// SPDX-License-Identifier: AGPL-3.0-or-later
// One protected-site list for the extension and the server. A site on it needs the owner
// to use it directly: neither side will share, read or act on it for a bot.
//
// The first block is Murage's own list. The second block is copied as data from Sean's
// earlier extension, FoundryInChrome (src/lib/privacy/domain-lists.ts: CRITICAL_DOMAIN_SUFFIXES,
// CRITICAL_TLDS and GOV_SLD_PATTERNS). Only the list is ported here; its classifier layers
// (heuristics, CRITICAL/HIGH/STANDARD) are for 0.1.63. Entries are never removed by an owner setting.
export const PROTECTED_DOMAINS_VERSION = 3;
const MURAGE_DOMAINS = [
  "1password.com", "bitwarden.com", "lastpass.com", "dashlane.com", "keepersecurity.com", "proton.me",
  "paypal.com", "stripe.com", "wise.com", "revolut.com",
  "chase.com", "bankofamerica.com", "wellsfargo.com", "citi.com", "citibank.com", "hsbc.com", "capitalone.com",
  "chromewebstore.google.com", "chrome.google.com", "microsoftedge.microsoft.com",
] as const;
// From FoundryInChrome CRITICAL_DOMAIN_SUFFIXES (banking, brokerage, crypto, health, government,
// password managers, tax, insurance, payroll, e-signing, SSO, aggregators, payment processors).
const FOUNDRY_DOMAINS = [
  // US Banking (Top 50+ banks & credit unions)
  "chase.com",
  "bankofamerica.com",
  "wellsfargo.com",
  "citi.com",
  "citibank.com",
  "capitalone.com",
  "usbank.com",
  "tdbank.com",
  "pnc.com",
  "regions.com",
  "ally.com",
  "discover.com",
  "synchrony.com",
  "citizensbank.com",
  "fifththird.com",
  "53.com",
  "keybank.com",
  "huntington.com",
  "mandt.com",
  "truist.com",
  "navyfederal.org",
  "usaa.com",
  "nfcu.org",
  "becu.org",
  "schwab.com",
  "penfed.org",
  "alliantcreditunion.org",
  "sofi.com",
  "marcus.com",
  "chime.com",
  "varo.com",
  "current.com",
  "americanexpress.com",
  "amex.com",
  // International Banking
  "hsbc.com",
  "hsbc.co.uk",
  "barclays.co.uk",
  "barclays.com",
  "lloydsbank.com",
  "natwest.com",
  "rbs.co.uk",
  "santander.co.uk",
  "deutschebank.com",
  "db.com",
  "bnpparibas.com",
  "ing.com",
  "ing.nl",
  "ubs.com",
  "revolut.com",
  "monzo.com",
  "starling.com",
  "commerzbank.de",
  "societegenerale.com",
  "unicredit.it",
  "dbs.com",
  "icbc.com.cn",
  "boc.cn",
  "ccb.com",
  "mufg.jp",
  "smbc.co.jp",
  "mizuhobank.com",
  "anz.com.au",
  "commbank.com.au",
  "nab.com.au",
  "westpac.com.au",
  "rbc.com",
  "td.com",
  "scotiabank.com",
  "bmo.com",
  "cibc.com",
  // Investment & Brokerage
  "fidelity.com",
  "vanguard.com",
  "etrade.com",
  "tdameritrade.com",
  "thinkorswim.com",
  "interactivebrokers.com",
  "merrilledge.com",
  "ml.com",
  "morganstanley.com",
  "edwardjones.com",
  "wealthfront.com",
  "betterment.com",
  "robinhood.com",
  "webull.com",
  "tastytrade.com",
  "tradestation.com",
  "tiaa.org",
  "tiaa-cref.org",
  // Crypto Exchanges & Wallets
  "coinbase.com",
  "binance.com",
  "binance.us",
  "kraken.com",
  "gemini.com",
  "crypto.com",
  "kucoin.com",
  "bybit.com",
  "okx.com",
  "bitfinex.com",
  "bitstamp.com",
  "gate.io",
  "huobi.com",
  "htx.com",
  "bitget.com",
  "mexc.com",
  "phantom.app",
  "metamask.io",
  "ledger.com",
  "trezor.io",
  "uniswap.org",
  "curve.fi",
  "aave.com",
  "opensea.io",
  // Healthcare & Patient Portals
  "mychart.com",
  "mycharthealth.com",
  "epic.com",
  "athenahealth.com",
  "cerner.com",
  "cernerhealth.com",
  "allscripts.com",
  "eclinicalworks.com",
  "nextgen.com",
  "kareo.com",
  "drchrono.com",
  "myuhc.com",
  "anthem.com",
  "aetna.com",
  "cigna.com",
  "humana.com",
  "centene.com",
  "molina.com",
  "kaiserpermanente.org",
  "kp.org",
  "bluecrossblueshield.com",
  "bcbs.com",
  "uhc.com",
  "unitedhealthcare.com",
  // Government (US)
  "irs.gov",
  "ssa.gov",
  "healthcare.gov",
  "medicare.gov",
  "medicaid.gov",
  "va.gov",
  "benefits.gov",
  "usa.gov",
  "usajobs.gov",
  "login.gov",
  "id.me",
  "treasury.gov",
  "sec.gov",
  "fdic.gov",
  "opm.gov",
  "dol.gov",
  "uscis.gov",
  "state.gov",
  // Password Managers
  "1password.com",
  "bitwarden.com",
  "lastpass.com",
  "dashlane.com",
  "keepersecurity.com",
  "nordpass.com",
  "roboform.com",
  "enpass.io",
  // Tax & Accounting
  "hrblock.com",
  "taxact.com",
  "freetaxusa.com",
  "taxslayer.com",
  "freshbooks.com",
  "xero.com",
  // Insurance
  "geico.com",
  "progressive.com",
  "statefarm.com",
  "allstate.com",
  "nationwide.com",
  "libertymutual.com",
  "farmers.com",
  "travelers.com",
  "thehartford.com",
  "erieinsurance.com",
  "metlife.com",
  "prudential.com",
  "newyorklife.com",
  "aflac.com",
  "unum.com",
  "principal.com",
  "lemonade.com",
  "policygenius.com",
  // Payroll / HR (SSN + salary data)
  "adp.com",
  "workday.com",
  "gusto.com",
  "paychex.com",
  "paycom.com",
  "paylocity.com",
  "ceridian.com",
  "bamboohr.com",
  "namely.com",
  "rippling.com",
  "justworks.com",
  "deel.com",
  // Legal / E-Signing
  "docusign.com",
  "hellosign.com",
  "adobesign.com",
  "pandadoc.com",
  "signnow.com",
  "notarize.com",
  "legalzoom.com",
  "rocketlawyer.com",
  // SSO / Auth Providers
  "okta.com",
  "auth0.com",
  "onelogin.com",
  "duo.com",
  "pingidentity.com",
  "forgerock.com",
  // Financial Aggregators (per PITFALLS.md P10)
  "plaid.com",
  "yodlee.com",
  "finicity.com",
  "mx.com",
  "akoya.com",
  // Payment Processors (from old blocklist)
  "paypal.com",
  "venmo.com",
] as const;
/** Every listed registrable domain; a subdomain of one is protected too. */
export const PROTECTED_DOMAINS: readonly string[] = [...new Set<string>([...MURAGE_DOMAINS, ...FOUNDRY_DOMAINS])];
/** Verified-only top-level domains (FoundryInChrome CRITICAL_TLDS). */
export const PROTECTED_TLDS: readonly string[] = [".bank", ".insurance", ".gov", ".mil", ".pharmacy"];
/** Government second-level domains in other countries (FoundryInChrome GOV_SLD_PATTERNS). */
export const PROTECTED_GOV_PATTERNS: readonly RegExp[] = [/\.gov\.[a-z]{2}$/, /\.gc\.ca$/, /\.gob\.[a-z]{2}$/, /\.gouv\.fr$/, /\.governo\.it$/, /\.bund\.de$/, /\.go\.[a-z]{2}$/];
const DOMAIN_SET = new Set<string>(PROTECTED_DOMAINS);
/** True for a listed domain or any subdomain of one, a sensitive TLD, or a foreign government domain.
 * A trailing dot and letter case do not matter. */
export function isProtectedHostname(hostname: string): boolean {
  const host = String(hostname).toLowerCase().replace(/\.$/, "");
  if (!host) return false;
  if (PROTECTED_TLDS.some(tld => host.endsWith(tld))) return true;
  if (PROTECTED_GOV_PATTERNS.some(pattern => pattern.test(host))) return true;
  const labels = host.split(".");
  for (let start = 0; start < labels.length - 1; start++) if (DOMAIN_SET.has(labels.slice(start).join("."))) return true;
  return false;
}
