// GENERATED by scripts/build-capabilities.mjs — do not edit by hand.
// Source: the tool lists, settings sections, locale labels and route families
// named in each entry. Run `node scripts/build-capabilities.mjs` after changing
// them; `--check` in the test suite fails when this file is stale.
export type CapabilityKind = "tool" | "settings-page" | "bot-settings" | "place" | "label" | "route";

/** One thing the product can do, and the word the help must use for it. */
export interface Capability {
  readonly kind: CapabilityKind;
  /** The code-side name (a tool name, a section id, a locale key or a route). */
  readonly name: string;
  /** The words the help index has to contain, as a person would say them. */
  readonly term: string;
  /** Where the code says so. */
  readonly source: string;
}

export const HELP_CAPABILITIES: readonly Capability[] = [
  {
    "kind": "tool",
    "name": "murage_help",
    "term": "murage_help",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "register_artifact",
    "term": "register_artifact",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "send_voice_note",
    "term": "send_voice_note",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "list_image_models",
    "term": "list_image_models",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "resolve_image_reference",
    "term": "resolve_image_reference",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "generate_image",
    "term": "generate_image",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "save_prompt_block",
    "term": "save_prompt_block",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "list_prompt_blocks",
    "term": "list_prompt_blocks",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "get_prompt_block",
    "term": "get_prompt_block",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "save_reference_pack",
    "term": "save_reference_pack",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "list_reference_packs",
    "term": "list_reference_packs",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "web_search",
    "term": "web_search",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "tool_result_read",
    "term": "tool_result_read",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "allow_for_task",
    "term": "allow_for_task",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "list_bots",
    "term": "list_bots",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "ask_bot",
    "term": "ask_bot",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "delegate_bot",
    "term": "delegate_bot",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "check_delegation",
    "term": "check_delegation",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "wait_delegation",
    "term": "wait_delegation",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "get_permission_status",
    "term": "get_permission_status",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "request_bot_access",
    "term": "request_bot_access",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "get_bot",
    "term": "get_bot",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "update_bot",
    "term": "update_bot",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "create_bot",
    "term": "create_bot",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "request_browser_connection",
    "term": "request_browser_connection",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "request_credential",
    "term": "request_credential",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "list_routines",
    "term": "list_routines",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "propose_routine",
    "term": "propose_routine",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "propose_routine_action",
    "term": "propose_routine_action",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "propose_outcome",
    "term": "propose_outcome",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "skills_list",
    "term": "skills_list",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "skill_manage",
    "term": "skill_manage",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "publish_site",
    "term": "publish_site",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "take_down_site",
    "term": "take_down_site",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "project_propose",
    "term": "project_propose",
    "source": "server/drivers/agents-proxy.ts"
  },
  {
    "kind": "tool",
    "name": "project_assign",
    "term": "project_assign",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_accept",
    "term": "project_accept",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_card_manage",
    "term": "project_card_manage",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_review_assign",
    "term": "project_review_assign",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_criteria",
    "term": "project_criteria",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_done",
    "term": "project_done",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_blocked",
    "term": "project_blocked",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_brief_update",
    "term": "project_brief_update",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_card_update",
    "term": "project_card_update",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_review_result",
    "term": "project_review_result",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_read_messages",
    "term": "project_read_messages",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_bring_in",
    "term": "project_bring_in",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_suggest",
    "term": "project_suggest",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "tool",
    "name": "project_summary_update",
    "term": "project_summary_update",
    "source": "server/drivers/project-tool-schemas.ts"
  },
  {
    "kind": "settings-page",
    "name": "general",
    "term": "General",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "aboutMe",
    "term": "About me",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "botDefaults",
    "term": "Bot defaults",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "houseRules",
    "term": "House rules",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "skills",
    "term": "Skills",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "memory",
    "term": "Memory",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "models",
    "term": "Models",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "engines",
    "term": "Engines",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "images",
    "term": "Images",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "webSearch",
    "term": "Web search",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "voice",
    "term": "Voice",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "connections",
    "term": "Connected apps",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "computer",
    "term": "Computer & browser",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "channels",
    "term": "Messaging apps",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "companion",
    "term": "Phone and other devices",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "backups",
    "term": "Backups",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "usage",
    "term": "Usage",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "about",
    "term": "Help & updates",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "settings-page",
    "name": "experimental",
    "term": "Experimental",
    "source": "src/lib/settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "overview",
    "term": "Overview",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "identity",
    "term": "Identity & instructions",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "shapes",
    "term": "What shapes this bot",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "skills",
    "term": "Skills",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "learning",
    "term": "Learning",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "memory",
    "term": "Memory",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "routines",
    "term": "Routines",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "teams",
    "term": "Teams",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "access",
    "term": "Access",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "model",
    "term": "Model",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "permissions",
    "term": "Permissions",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "voice",
    "term": "Voice & alerts",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "history",
    "term": "History",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "bot-settings",
    "name": "usage",
    "term": "Usage",
    "source": "src/components/bot-settings-sections.ts"
  },
  {
    "kind": "place",
    "name": "nav.routines",
    "term": "Routines",
    "source": "src/locales/en.json"
  },
  {
    "kind": "place",
    "name": "nav.files",
    "term": "Files",
    "source": "src/locales/en.json"
  },
  {
    "kind": "place",
    "name": "nav.apps",
    "term": "Apps",
    "source": "src/locales/en.json"
  },
  {
    "kind": "place",
    "name": "nav.mapName",
    "term": "Team map",
    "source": "src/locales/en.json"
  },
  {
    "kind": "label",
    "name": "PEER_CONTACT_LABEL",
    "term": "Ask me before contacting other bots",
    "source": "src/lib/permission-mode.ts"
  },
  {
    "kind": "route",
    "name": "/api/about-me",
    "term": "about me",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/artifacts",
    "term": "files",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/attachments",
    "term": "attachments",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/backup-failure-notice",
    "term": "backups",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/backup-restart",
    "term": "backups",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/backup-waiting",
    "term": "backups",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/bots",
    "term": "bots",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/browser-extension",
    "term": "browser extension",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/calendar-calls",
    "term": "calls",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/cli-candidates",
    "term": "engines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/cli-test",
    "term": "engines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/connectors",
    "term": "connected apps",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/decisions",
    "term": "decisions",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/discord",
    "term": "Discord",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/engine-setup-command",
    "term": "engines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/files",
    "term": "files",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/flux-connection",
    "term": "Flux",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/folder-trust",
    "term": "working folder",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/groups",
    "term": "channels",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/house-rules",
    "term": "house rules",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/images",
    "term": "image generation",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/inbox",
    "term": "inbox",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/library",
    "term": "templates",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/local-computer",
    "term": "local computer",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/mcp",
    "term": "MCP servers",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/mcp-grants",
    "term": "script access",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/memory",
    "term": "memory",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/mobile",
    "term": "phone",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/packages",
    "term": "templates",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/projects",
    "term": "projects",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/provider-connections",
    "term": "engines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/publish",
    "term": "publishing sites",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/routine-runs",
    "term": "routines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/routines",
    "term": "routines",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/search",
    "term": "search",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/section-context",
    "term": "team instructions",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/sidebar-sections",
    "term": "teams",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/skills",
    "term": "skills",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/slack",
    "term": "Slack",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/starter-profiles",
    "term": "templates",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/team-library",
    "term": "templates",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/team-map",
    "term": "team map",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/team-sections",
    "term": "teams",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/teams",
    "term": "teams",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/telegram",
    "term": "Telegram",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/thread-snoozes",
    "term": "snooze",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/tts",
    "term": "voice",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/voice",
    "term": "voice",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/webhooks",
    "term": "webhooks",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/whats-new",
    "term": "what's new",
    "source": "server/index.ts"
  },
  {
    "kind": "route",
    "name": "/api/whatsapp",
    "term": "WhatsApp",
    "source": "server/index.ts"
  }
];
