// GENERATED by scripts/build-help-index.mjs — do not edit by hand.
// Source: apps/docs/content/docs/**/*.mdx. Run `node scripts/build-help-index.mjs`
// after editing those docs; `--check` in the test suite fails when it is stale.
/** One quotable section of the shipped user documentation. */
export interface HelpEntry {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly heading?: string;
  /** Where in the docs this lives, for a user who wants the whole page. */
  readonly breadcrumb: string;
  /** Where in the APP to go — a UI path when the section names one. */
  readonly where: string;
  /** Public documentation URL. Never a repository or filesystem path. */
  readonly url: string;
  readonly text: string;
}

export const HELP_INDEX: readonly HelpEntry[] = [
  {
    "id": "changelog#overview",
    "title": "Changelog",
    "description": "The complete history of published Murage desktop releases.",
    "breadcrumb": "Murage docs → Changelog",
    "where": "Murage docs → Changelog",
    "url": "https://murage.app/docs/changelog",
    "text": "The changelog tracks published desktop builds. Changes merged into main after a release are not listed as shipped until a new build is published.\n\nBrowse checksums, installers, and older notes in the Murage releases repository."
  },
  {
    "id": "computers/cloud-and-vps#box-cloud-computer",
    "title": "Cloud computer and your own VPS",
    "description": "Choose a managed Box desktop or a hardened container on a Linux server you own.",
    "heading": "Box cloud computer",
    "breadcrumb": "Murage docs → Computers → Cloud computer and your own VPS",
    "where": "Murage docs → Computers → Cloud computer and your own VPS",
    "url": "https://murage.app/docs/computers/cloud-and-vps#box-cloud-computer",
    "text": "Add a Box API key in App Settings to provision an isolated hosted Linux desktop. The computer can sleep and wake, and supported sessions provide a live viewer for temporary human control. Trial accounts automatically retry creation with the provider's shorter auto-stop ceiling when required.\n\nBox is a third-party paid service after its trial. Murage stores the configured credential locally and does not expose it to the renderer."
  },
  {
    "id": "computers/cloud-and-vps#bring-your-own-vps",
    "title": "Cloud computer and your own VPS",
    "description": "Choose a managed Box desktop or a hardened container on a Linux server you own.",
    "heading": "Bring your own VPS",
    "breadcrumb": "Murage docs → Computers → Cloud computer and your own VPS",
    "where": "Murage docs → Computers → Cloud computer and your own VPS",
    "url": "https://murage.app/docs/computers/cloud-and-vps#bring-your-own-vps",
    "text": "Murage can control Docker on an x8664 Linux server through an SSH config alias. The agent process stays on your local machine; only Docker commands and the managed desktop container run on the VPS.\n\nYour SSH alias should include connection multiplexing, keepalives, and a connect timeout. Connect manually once to approve the host key, then verify:\n\nThe SSH user needs Docker access, which is root-equivalent on that server. Use a dedicated VPS and firewall inbound traffic to SSH only.\n\nThe managed container publishes no ports, has no host mounts, and is checked before every attach.…"
  },
  {
    "id": "computers#overview",
    "title": "Give a bot a computer",
    "description": "Choose the right desktop or isolated environment for a task.",
    "breadcrumb": "Murage docs → Give a bot a computer",
    "where": "Murage docs → Give a bot a computer",
    "url": "https://murage.app/docs/computers",
    "text": "A bot can work without a computer, use the computer running Murage, or work inside an isolated desktop.\n\n| Backend | Isolation | Best for |\n|---|---|---|\n| This computer | None | Working with local apps and files you explicitly approve |\n| Local VM | Containerized desktop | Repeatable browser and desktop work on your machine |\n| Box cloud computer | Hosted remote desktop | Always-available isolated Linux work |\n| Self-hosted VPS | Hardened container over SSH | Using infrastructure you own |"
  },
  {
    "id": "computers#auto-local-and-cloud-selection",
    "title": "Give a bot a computer",
    "description": "Choose the right desktop or isolated environment for a task.",
    "heading": "Auto, local, and cloud selection",
    "breadcrumb": "Murage docs → Give a bot a computer",
    "where": "Murage docs → Give a bot a computer",
    "url": "https://murage.app/docs/computers#auto-local-and-cloud-selection",
    "text": "Computer selection is explicit per bot. Auto may reuse a ready, verified backend, but it does not silently provision every backend or turn on host control."
  },
  {
    "id": "computers#preview-and-takeover",
    "title": "Give a bot a computer",
    "description": "Choose the right desktop or isolated environment for a task.",
    "heading": "Preview and takeover",
    "breadcrumb": "Murage docs → Give a bot a computer",
    "where": "Murage docs → Give a bot a computer",
    "url": "https://murage.app/docs/computers#preview-and-takeover",
    "text": "The Computer panel can show live frames while an agent works. Supported cloud desktops also provide an interactive viewer. Murage opens that viewer in the app when possible, with a browser fallback for external join flows.\n\nStarting a screen preview does not grant the bot control. Local input requires a separate opt-in and remains subject to the computer-use safety boundary."
  },
  {
    "id": "computers/local-computer#overview",
    "title": "This computer",
    "description": "Let a supported agent control the local desktop through the bundled CUA boundary.",
    "breadcrumb": "Murage docs → Computers → This computer",
    "where": "Murage docs → Computers → This computer",
    "url": "https://murage.app/docs/computers/local-computer",
    "text": "Local control is off by default. The Electron main process owns the bundled CUA driver lifecycle so operating-system permissions are attributed to Murage rather than a background helper."
  },
  {
    "id": "computers/local-computer#macos",
    "title": "This computer",
    "description": "Let a supported agent control the local desktop through the bundled CUA boundary.",
    "heading": "macOS",
    "breadcrumb": "Murage docs → Computers → This computer",
    "where": "Murage docs → Computers → This computer",
    "url": "https://murage.app/docs/computers/local-computer#macos",
    "text": "The packaged app can request Accessibility and Screen Recording permission. After granting either permission, restart the control session when prompted so macOS applies the new grant."
  },
  {
    "id": "computers/local-computer#ubuntu",
    "title": "This computer",
    "description": "Let a supported agent control the local desktop through the bundled CUA boundary.",
    "heading": "Ubuntu",
    "breadcrumb": "Murage docs → Computers → This computer",
    "where": "Murage docs → Computers → This computer",
    "url": "https://murage.app/docs/computers/local-computer#ubuntu",
    "text": "Ubuntu 24.04 GNOME host control is temporarily disabled while the real-seat input-safety blocker in issue #345 is resolved. Packaged builds retain the pinned runtime for reproducible review, but Murage does not start it and clears legacy opt-ins. Chat, screen preview, Cloud, and Local VM remain available. Do not start the bundled driver manually as a workaround."
  },
  {
    "id": "computers/local-computer#safety-model",
    "title": "This computer",
    "description": "Let a supported agent control the local desktop through the bundled CUA boundary.",
    "heading": "Safety model",
    "breadcrumb": "Murage docs → Computers → This computer",
    "where": "Murage docs → Computers → This computer",
    "url": "https://murage.app/docs/computers/local-computer#safety-model",
    "text": "- On macOS, a bot left on Auto can use this computer once local control is installed, but it asks you once before it first acts on your screen. Choose Allow for this bot and Murage remembers it for that bot. Choose Don't allow and Auto keeps that bot off your screen. To change your answer, open the bot's Computer panel and choose Ask again.\n- Bots that already used this computer before this check existed keep working without the question: bots with Auto mode on, and bots you had already approved on this computer.\n- A bot you set to This computer is never asked, because choosing it is your answer. Set a bot to Off if it should never touch your screen.…"
  },
  {
    "id": "computers/local-vm#overview",
    "title": "Local VM",
    "description": "Run desktop work inside an isolated Docker or Podman environment.",
    "breadcrumb": "Murage docs → Computers → Local VM",
    "where": "Murage docs → Computers → Local VM",
    "url": "https://murage.app/docs/computers/local-vm",
    "text": "The Local VM gives each bot a containerized Linux desktop on the same machine as Murage. It is useful for browser work, downloads, and repeatable automation that should not run directly on your host desktop."
  },
  {
    "id": "computers/local-vm#requirements",
    "title": "Local VM",
    "description": "Run desktop work inside an isolated Docker or Podman environment.",
    "heading": "Requirements",
    "breadcrumb": "Murage docs → Computers → Local VM",
    "where": "Podman Desktop exposes that machine under Settings → Resources",
    "url": "https://murage.app/docs/computers/local-vm#requirements",
    "text": "- Docker Desktop, Docker Engine, or a supported Podman setup\n- Enough local memory and disk for the desktop image\n- A healthy container runtime available to the Murage process\n\nOn Windows, Podman is the preferred Local VM runtime. Murage checks Podman before Docker and validates the exact Windows-to-VM workspace mount before reusing a container.\n\nBefore starting two desktops on Windows, confirm the Podman machine is running and has enough shared CPU, memory, and disk for both. Podman Desktop exposes that machine under Settings → Resources; both Murage desktops consume the same machine budget."
  },
  {
    "id": "computers/local-vm#run-two-bot-desktops",
    "title": "Local VM",
    "description": "Run desktop work inside an isolated Docker or Podman environment.",
    "heading": "Run two bot desktops",
    "breadcrumb": "Murage docs → Computers → Local VM",
    "where": "Open App Settings → Local VM",
    "url": "https://murage.app/docs/computers/local-vm#run-two-bot-desktops",
    "text": "1. Open App Settings → Local VM, prepare the managed desktop image, and choose Per bot.\n2. Set Maximum per-bot desktops to 2.\n3. Give two bots Local VM as their computer and create each desktop from that bot's Computer panel.\n4. Choose Open two desktops from either bot to watch both in one workspace.\n\nBoth desktops may keep running, but only one pane can hold interactive control at a time. Switching control releases the previous pane first; opening the two-up workspace never creates or starts a VM.\n\nThe equivalent source configuration is:\n\nLocal VMs always run on the same physical host as the Murage desktop process.…"
  },
  {
    "id": "computers/local-vm#persistence",
    "title": "Local VM",
    "description": "Run desktop work inside an isolated Docker or Podman environment.",
    "heading": "Persistence",
    "breadcrumb": "Murage docs → Computers → Local VM",
    "where": "Murage docs → Computers → Local VM",
    "url": "https://murage.app/docs/computers/local-vm#persistence",
    "text": "The bot's workspace and browser profile live in a durable mounted directory. Recreating the desktop can repair stale runtime state without deleting the durable workspace."
  },
  {
    "id": "computers/local-vm#ownership-and-reuse",
    "title": "Local VM",
    "description": "Run desktop work inside an isolated Docker or Podman environment.",
    "heading": "Ownership and reuse",
    "breadcrumb": "Murage docs → Computers → Local VM",
    "where": "Murage docs → Computers → Local VM",
    "url": "https://murage.app/docs/computers/local-vm#ownership-and-reuse",
    "text": "Local VM ownership uses a renewable lease. Murage validates the resolved image and container safety contract before reuse instead of trusting only a mutable image tag."
  },
  {
    "id": "connected-apps#overview",
    "title": "Connected apps",
    "description": "Give bots secure, user-authorized tools for Gmail, GitHub, Slack, Notion, and hundreds more.",
    "breadcrumb": "Murage docs → Connected apps",
    "where": "Murage docs → Connected apps",
    "url": "https://murage.app/docs/connected-apps",
    "text": "Open Connected apps from the sidebar, choose a service, and complete its authorization in your normal browser. Murage turns the resulting connection into tools that supported agent engines can use."
  },
  {
    "id": "connected-apps#official-packaged-app",
    "title": "Connected apps",
    "description": "Give bots secure, user-authorized tools for Gmail, GitHub, Slack, Notion, and hundreds more.",
    "heading": "Official packaged app",
    "breadcrumb": "Murage docs → Connected apps",
    "where": "Murage docs → Connected apps",
    "url": "https://murage.app/docs/connected-apps#official-packaged-app",
    "text": "The signed desktop app registers its own installation with Murage's managed connected-apps service. You do not need to find or paste a Composio key.\n\n1. Open Connected apps.\n2. Search for Gmail, GitHub, Slack, Notion, or another toolkit.\n3. Select Connect.\n4. Finish OAuth in the browser window that opens.\n5. Return to the app and ask a bot to use the service.\n\nThe installation identity is stored using Electron's operating-system-backed secure storage. Provider OAuth tokens remain with Composio and are not written into bot prompts or the renderer."
  },
  {
    "id": "connected-apps#self-hosted-or-source-builds",
    "title": "Connected apps",
    "description": "Give bots secure, user-authorized tools for Gmail, GitHub, Slack, Notion, and hundreds more.",
    "heading": "Self-hosted or source builds",
    "breadcrumb": "Murage docs → Connected apps",
    "where": "Murage docs → Connected apps",
    "url": "https://murage.app/docs/connected-apps#self-hosted-or-source-builds",
    "text": "The managed service is a convenience for official packaged builds. A source build can use your own Composio project and COMPOSIOAPIKEY; see Self-hosted Composio."
  },
  {
    "id": "connected-apps#multiple-accounts",
    "title": "Connected apps",
    "description": "Give bots secure, user-authorized tools for Gmail, GitHub, Slack, Notion, and hundreds more.",
    "heading": "Multiple accounts",
    "breadcrumb": "Murage docs → Connected apps",
    "where": "Murage docs → Connected apps",
    "url": "https://murage.app/docs/connected-apps#multiple-accounts",
    "text": "Connect more than one account for the same toolkit and give each a clear alias such as work, personal, or client-acme. When several accounts could perform an action, Murage requires explicit selection instead of silently replacing the first connection."
  },
  {
    "id": "connected-apps#disconnecting",
    "title": "Connected apps",
    "description": "Give bots secure, user-authorized tools for Gmail, GitHub, Slack, Notion, and hundreds more.",
    "heading": "Disconnecting",
    "breadcrumb": "Murage docs → Connected apps",
    "where": "Murage docs → Connected apps",
    "url": "https://murage.app/docs/connected-apps#disconnecting",
    "text": "Disconnecting an account revokes the upstream grant. It does not only hide the account in the local UI. Other accounts for the same toolkit remain connected.\n\nCurrent official builds provision connected apps automatically. A Composio project key is only needed when you deliberately run the integration yourself."
  },
  {
    "id": "connected-apps/multiple-accounts#overview",
    "title": "Multiple accounts",
    "description": "Connect work and personal accounts without silently replacing either one.",
    "breadcrumb": "Murage docs → Connected apps → Multiple accounts",
    "where": "Murage docs → Connected apps → Multiple accounts",
    "url": "https://murage.app/docs/connected-apps/multiple-accounts",
    "text": "Murage supports several labeled accounts for the same toolkit. This is useful for two Gmail inboxes, several Slack workspaces, or separate personal and work services."
  },
  {
    "id": "connected-apps/multiple-accounts#add-an-account",
    "title": "Multiple accounts",
    "description": "Connect work and personal accounts without silently replacing either one.",
    "heading": "Add an account",
    "breadcrumb": "Murage docs → Connected apps → Multiple accounts",
    "where": "Murage docs → Connected apps → Multiple accounts",
    "url": "https://murage.app/docs/connected-apps/multiple-accounts#add-an-account",
    "text": "1. Open Connected apps.\n2. Find the toolkit you want to connect.\n3. Choose Connect (or Add account if you already have one).\n4. Enter a unique label such as work, personal, or the workspace name.\n5. Complete authorization in your browser.\n\nMurage asks for a label on every new account, including the first, before authorization starts, so the Connected tab shows your chosen name instead of a generated ID. Cancel closes the label form without starting authorization. When more than one account could execute a tool, the Composio session requires explicit account selection. A new authorization does not silently become the default for the old one."
  },
  {
    "id": "connected-apps/multiple-accounts#disconnect-safely",
    "title": "Multiple accounts",
    "description": "Connect work and personal accounts without silently replacing either one.",
    "heading": "Disconnect safely",
    "breadcrumb": "Murage docs → Connected apps → Multiple accounts",
    "where": "Murage docs → Connected apps → Multiple accounts",
    "url": "https://murage.app/docs/connected-apps/multiple-accounts#disconnect-safely",
    "text": "Each connected account appears separately with its alias and status. Disconnect removes only the chosen account and leaves the others active.\n\nMurage caps each toolkit at five usable accounts. If a provider or Composio project policy prevents another authorization, use a separate Murage installation or configuration rather than reauthorizing over a working account."
  },
  {
    "id": "connected-apps/self-hosted-composio#overview",
    "title": "Composio for self-hosters",
    "description": "Configure project-key access, scoped permissions, and headless development.",
    "breadcrumb": "Murage docs → Connected apps → Composio for self-hosters",
    "where": "Murage docs → Connected apps → Composio for self-hosters",
    "url": "https://murage.app/docs/connected-apps/self-hosted-composio",
    "text": "The simplest open-source setup is for each installation owner to create a Composio project and paste that project's key into Murage. This avoids operating a shared credential broker and keeps usage attached to the user's own Composio account."
  },
  {
    "id": "connected-apps/self-hosted-composio#least-privilege-scoped-key",
    "title": "Composio for self-hosters",
    "description": "Configure project-key access, scoped permissions, and headless development.",
    "heading": "Least-privilege scoped key",
    "breadcrumb": "Murage docs → Connected apps → Composio for self-hosters",
    "where": "Murage docs → Connected apps → Composio for self-hosters",
    "url": "https://murage.app/docs/connected-apps/self-hosted-composio#least-privilege-scoped-key",
    "text": "If you use a scoped Composio project key, grant:\n- Sessions: read and write\n- Toolkits: read\n- Connected accounts: read and write\n\nConnected-account write access is required for upstream revocation during disconnect."
  },
  {
    "id": "connected-apps/self-hosted-composio#source-and-headless-runs",
    "title": "Composio for self-hosters",
    "description": "Configure project-key access, scoped permissions, and headless development.",
    "heading": "Source and headless runs",
    "breadcrumb": "Murage docs → Connected apps → Composio for self-hosters",
    "where": "Murage docs → Connected apps → Composio for self-hosters",
    "url": "https://murage.app/docs/connected-apps/self-hosted-composio#source-and-headless-runs",
    "text": "Set the key on the harness process:\n\nMurage creates a stable random Composio user identifier and reuses the returned Session. It does not store raw Gmail, Slack, GitHub, or other provider tokens."
  },
  {
    "id": "connected-apps/self-hosted-composio#managed-broker",
    "title": "Composio for self-hosters",
    "description": "Configure project-key access, scoped permissions, and headless development.",
    "heading": "Managed broker",
    "breadcrumb": "Murage docs → Connected apps → Composio for self-hosters",
    "where": "Murage docs → Connected apps → Composio for self-hosters",
    "url": "https://murage.app/docs/connected-apps/self-hosted-composio#managed-broker",
    "text": "The repository also contains a Cloudflare Worker broker for managed deployments. It returns the same account-aware inventory shape while keeping broker credentials out of the renderer. Use it only when you intentionally operate a hosted connection service; it is not required for ordinary self-hosting."
  },
  {
    "id": "devices/android-control#overview",
    "title": "USB Android control",
    "description": "Let a bot inspect and operate a physically connected Android phone.",
    "breadcrumb": "Murage docs → Devices → USB Android control",
    "where": "Murage docs → Devices → USB Android control",
    "url": "https://murage.app/docs/devices/android-control",
    "text": "Murage can expose a USB-connected Android device through its Phone Harness skill. A supported agent can inspect the screen, open apps, tap, type, swipe, scroll, and capture screenshots."
  },
  {
    "id": "devices/android-control#requirements",
    "title": "USB Android control",
    "description": "Let a bot inspect and operate a physically connected Android phone.",
    "heading": "Requirements",
    "breadcrumb": "Murage docs → Devices → USB Android control",
    "where": "Murage docs → Devices → USB Android control",
    "url": "https://murage.app/docs/devices/android-control#requirements",
    "text": "- A physical Android device connected over USB\n- USB debugging enabled on the device\n- The computer trusted from the device's debugging prompt\n- The packaged Android platform tools or a compatible local ADB installation\n\nPhone access is a separate capability from desktop computer use. Keep the device unlocked and visible while testing, and review actions that may send messages, change accounts, or expose private content."
  },
  {
    "id": "features/approvals-and-inspector#overview",
    "title": "Approvals and inspector",
    "description": "Stay in control when agents ask questions, request access, or perform risky work.",
    "breadcrumb": "Murage docs → Features → Approvals and inspector",
    "where": "Murage docs → Features → Approvals and inspector",
    "url": "https://murage.app/docs/features/approvals-and-inspector",
    "text": "Murage renders structured agent events as native conversation cards. Questions, choices, permission requests, tool activity, and failures remain attached to the task that produced them."
  },
  {
    "id": "features/approvals-and-inspector#approval-cards",
    "title": "Approvals and inspector",
    "description": "Stay in control when agents ask questions, request access, or perform risky work.",
    "heading": "Approval cards",
    "breadcrumb": "Murage docs → Features → Approvals and inspector",
    "where": "Murage docs → Features → Approvals and inspector",
    "url": "https://murage.app/docs/features/approvals-and-inspector#approval-cards",
    "text": "When an engine supports approvals, Murage surfaces the request instead of hiding it in terminal output. Read the requested action and scope before approving it. Denying an action sends control back to the agent so it can choose a safer path."
  },
  {
    "id": "features/approvals-and-inspector#ask-auto-and-full-access",
    "title": "Approvals and inspector",
    "description": "Stay in control when agents ask questions, request access, or perform risky work.",
    "heading": "Ask, Auto and Full access",
    "breadcrumb": "Murage docs → Features → Approvals and inspector",
    "where": "Murage docs → Features → Approvals and inspector",
    "url": "https://murage.app/docs/features/approvals-and-inspector#ask-auto-and-full-access",
    "text": "Choose how a conversation is approved from the chip beside the composer:\n- Ask shows a card for each action that needs your permission.\n- Auto keeps the bot working, but still stops at anything that looks destructive or sensitive: shell profiles, API-key variables, credential stores.\n- Full access does not ask before running commands, reading credentials or personal files, or contacting other bots. It can be switched on only in the desktop app, and the first time for each bot you confirm a warning.\n\nSome things still ask under Full access. A turn started by a webhook or a routine asks as it would under Auto, because someone other than you wrote that input or nobody is watching it.…"
  },
  {
    "id": "features/approvals-and-inspector#inspector",
    "title": "Approvals and inspector",
    "description": "Stay in control when agents ask questions, request access, or perform risky work.",
    "heading": "Inspector",
    "breadcrumb": "Murage docs → Features → Approvals and inspector",
    "where": "Murage docs → Features → Approvals and inspector",
    "url": "https://murage.app/docs/features/approvals-and-inspector#inspector",
    "text": "Use Inspector when you need more detail than the conversation provides. It is useful for following tool calls, reconnect attempts, engine output, and long-running work."
  },
  {
    "id": "features/approvals-and-inspector#when-a-run-disconnects",
    "title": "Approvals and inspector",
    "description": "Stay in control when agents ask questions, request access, or perform risky work.",
    "heading": "When a run disconnects",
    "breadcrumb": "Murage docs → Features → Approvals and inspector",
    "where": "Murage docs → Features → Approvals and inspector",
    "url": "https://murage.app/docs/features/approvals-and-inspector#when-a-run-disconnects",
    "text": "Murage retries transient streaming failures. If retries end in an authentication or configuration error, fix the underlying engine rather than repeatedly retrying the task. See Agent engine troubleshooting."
  },
  {
    "id": "features/attachments-and-search#image-attachments",
    "title": "Attachments, search, and message tools",
    "description": "Add visual context and find, preserve, or reuse important parts of a conversation.",
    "heading": "Image attachments",
    "breadcrumb": "Murage docs → Features → Attachments, search, and message tools",
    "where": "Murage docs → Features → Attachments, search, and message tools",
    "url": "https://murage.app/docs/features/attachments-and-search#image-attachments",
    "text": "Paste a screenshot directly into the composer or attach an image from disk. Add a short instruction explaining what the agent should inspect: the highlighted UI, an error message, a layout mismatch, or the whole image."
  },
  {
    "id": "features/attachments-and-search#search",
    "title": "Attachments, search, and message tools",
    "description": "Add visual context and find, preserve, or reuse important parts of a conversation.",
    "heading": "Search",
    "breadcrumb": "Murage docs → Features → Attachments, search, and message tools",
    "where": "Murage docs → Features → Attachments, search, and message tools",
    "url": "https://murage.app/docs/features/attachments-and-search#search",
    "text": "The sidebar search finds bots and conversation content. Use distinctive project names, issue numbers, or exact error fragments to narrow results quickly."
  },
  {
    "id": "features/attachments-and-search#message-actions",
    "title": "Attachments, search, and message tools",
    "description": "Add visual context and find, preserve, or reuse important parts of a conversation.",
    "heading": "Message actions",
    "breadcrumb": "Murage docs → Features → Attachments, search, and message tools",
    "where": "Murage docs → Features → Attachments, search, and message tools",
    "url": "https://murage.app/docs/features/attachments-and-search#message-actions",
    "text": "- Pin durable decisions or instructions.\n- Copy a response without selecting the message manually.\n- React to leave lightweight feedback in shared conversations.\n- Retry when a transient provider or connection failure interrupts a response.\n- Read aloud when voice output is configured.\n\nCrop tokens, email addresses, private repository names, and customer data before attaching an image to any cloud-backed model."
  },
  {
    "id": "features/automation#routines",
    "title": "Routines and webhooks",
    "description": "Start fresh agent tasks on a schedule or from an external event.",
    "heading": "Routines",
    "breadcrumb": "Murage docs → Features → Routines and webhooks",
    "where": "Murage docs → Features → Routines and webhooks",
    "url": "https://murage.app/docs/features/automation#routines",
    "text": "A routine runs once or on selected weekdays. Each run starts a fresh task using the selected bot's model, permissions, tools, and computer configuration.\n\nRun receipts distinguish queued, active, waiting, completed, missed, failed, and cancelled work. Murage must be running when a local routine becomes due."
  },
  {
    "id": "features/automation#webhook-triggers",
    "title": "Routines and webhooks",
    "description": "Start fresh agent tasks on a schedule or from an external event.",
    "heading": "Webhook triggers",
    "breadcrumb": "Murage docs → Features → Routines and webhooks",
    "where": "Murage docs → Features → Routines and webhooks",
    "url": "https://murage.app/docs/features/automation#webhook-triggers",
    "text": "Webhooks start the same queued task executor from an external HTTP request. They are independent from schedules and use a dedicated receiver on 127.0.0.1:8800 by default.\n\nThe receiver exposes only health and secret hook routes. It does not expose the broader Murage API.\n\nBearer authentication is preferred because it keeps the secret out of URLs and most access logs. A capability URL is available for senders that cannot set headers."
  },
  {
    "id": "features/automation#reaching-a-local-webhook",
    "title": "Routines and webhooks",
    "description": "Start fresh agent tasks on a schedule or from an external event.",
    "heading": "Reaching a local webhook",
    "breadcrumb": "Murage docs → Features → Routines and webhooks",
    "where": "Murage docs → Features → Routines and webhooks",
    "url": "https://murage.app/docs/features/automation#reaching-a-local-webhook",
    "text": "To accept events from the public internet, proxy only the webhook receiver through a narrowly configured relay or tunnel. Do not expose the main harness port.\n\nLocal routines and webhook deliveries are not hosted jobs. Closing the desktop app stops the local executor and receiver."
  },
  {
    "id": "features/bots-and-tasks#bots-are-persistent-teammates",
    "title": "Bots and tasks",
    "description": "Organize persistent agents, focused tasks, shared rooms, and delegated work.",
    "heading": "Bots are persistent teammates",
    "breadcrumb": "Murage docs → Features → Bots and tasks",
    "where": "Murage docs → Features → Bots and tasks",
    "url": "https://murage.app/docs/features/bots-and-tasks#bots-are-persistent-teammates",
    "text": "A bot keeps its own conversation, model, instructions, working folder, memory, connected tools, and computer preference. Create separate bots when the role, access, or project context should differ.\n- A coding bot attached to one repository\n- A research bot with browser and document tools\n- An operations bot with Gmail, Calendar, and Slack\n- A local-model bot for private or offline work"
  },
  {
    "id": "features/bots-and-tasks#tasks-are-focused-runs",
    "title": "Bots and tasks",
    "description": "Organize persistent agents, focused tasks, shared rooms, and delegated work.",
    "heading": "Tasks are focused runs",
    "breadcrumb": "Murage docs → Features → Bots and tasks",
    "where": "Murage docs → Features → Bots and tasks",
    "url": "https://murage.app/docs/features/bots-and-tasks#tasks-are-focused-runs",
    "text": "Use Task when the work should have a clear beginning and result. Tasks are easier to track than mixing every request into the bot's main conversation, and scheduled runs create tasks automatically."
  },
  {
    "id": "features/bots-and-tasks#rooms-and-teams",
    "title": "Bots and tasks",
    "description": "Organize persistent agents, focused tasks, shared rooms, and delegated work.",
    "heading": "Rooms and teams",
    "breadcrumb": "Murage docs → Features → Bots and tasks",
    "where": "Murage docs → Features → Bots and tasks",
    "url": "https://murage.app/docs/features/bots-and-tasks#rooms-and-teams",
    "text": "Rooms let multiple bots and people share context. Use a room when several specialists need the same brief or should hand work to one another. A chief-of-staff pattern works well: one bot receives the request, delegates focused tasks, and summarizes the result."
  },
  {
    "id": "features/bots-and-tasks#delegation",
    "title": "Bots and tasks",
    "description": "Organize persistent agents, focused tasks, shared rooms, and delegated work.",
    "heading": "Delegation",
    "breadcrumb": "Murage docs → Features → Bots and tasks",
    "where": "Murage docs → Features → Bots and tasks",
    "url": "https://murage.app/docs/features/bots-and-tasks#delegation",
    "text": "Delegation asks another bot to handle a bounded subtask. The delegated task keeps its own activity and returns a result to the originating conversation. Give each delegate a narrow outcome and avoid assigning two bots ownership of the same files.\n\n| Need | Use |\n|---|---|\n| Ongoing relationship and memory | Bot |\n| One deliverable with a status | Task |\n| Several participants sharing context | Room |\n| A specialist handling one branch of work | Delegation |\n| Repeated work at a known time | Schedule |"
  },
  {
    "id": "features/chat-and-teams#bots-and-tasks",
    "title": "Chat, tasks, rooms, and teams",
    "description": "Organize agents like contacts and let them collaborate without losing control of each task.",
    "heading": "Bots and tasks",
    "breadcrumb": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "where": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "url": "https://murage.app/docs/features/chat-and-teams#bots-and-tasks",
    "text": "A bot is a durable agent identity. A task is one conversation with that bot and has its own transcript, provider session, approvals, costs, and state.\n\nUse separate tasks when you want fresh context without duplicating the bot. Messages sent while a bot is busy are queued, and supported providers can be steered while they work."
  },
  {
    "id": "features/chat-and-teams#rooms",
    "title": "Chat, tasks, rooms, and teams",
    "description": "Organize agents like contacts and let them collaborate without losing control of each task.",
    "heading": "Rooms",
    "breadcrumb": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "where": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "url": "https://murage.app/docs/features/chat-and-teams#rooms",
    "text": "Rooms bring several bots into one conversation. Each participant keeps its own agent process and provider state. Room timeouts prevent a participant from blocking the whole group indefinitely."
  },
  {
    "id": "features/chat-and-teams#delegation",
    "title": "Chat, tasks, rooms, and teams",
    "description": "Organize agents like contacts and let them collaborate without losing control of each task.",
    "heading": "Delegation",
    "breadcrumb": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "where": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "url": "https://murage.app/docs/features/chat-and-teams#delegation",
    "text": "Bots can hand work to other bots. Delegated runs carry explicit status back into the parent conversation, including completion, failure, and cancellation."
  },
  {
    "id": "features/chat-and-teams#rewind-and-branches",
    "title": "Chat, tasks, rooms, and teams",
    "description": "Organize agents like contacts and let them collaborate without losing control of each task.",
    "heading": "Rewind and branches",
    "breadcrumb": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "where": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "url": "https://murage.app/docs/features/chat-and-teams#rewind-and-branches",
    "text": "Editing an earlier message creates a new conversation path. Murage avoids resuming stale provider sessions after a rewind, so the next turn follows the visible branch rather than hidden abandoned state."
  },
  {
    "id": "features/chat-and-teams#memory-and-working-folders",
    "title": "Chat, tasks, rooms, and teams",
    "description": "Organize agents like contacts and let them collaborate without losing control of each task.",
    "heading": "Memory and working folders",
    "breadcrumb": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "where": "Murage docs → Features → Chat, tasks, rooms, and teams",
    "url": "https://murage.app/docs/features/chat-and-teams#memory-and-working-folders",
    "text": "Bot memory is visible and editable. A bot may also have a dedicated working folder; rooms can use a shared working folder. Cloud workspaces use a stable default so generated files remain discoverable across tasks."
  },
  {
    "id": "features#overview",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features",
    "text": "Murage turns agent CLIs into a messaging-style workspace. The harness normalizes each provider into one event stream, so the interface can treat different agents consistently while preserving their native strengths."
  },
  {
    "id": "features#agents-and-conversations",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "heading": "Agents and conversations",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features#agents-and-conversations",
    "text": "- A separate bot for each role, model, personality, and working folder\n- Streaming responses with live tool activity\n- Multiple tasks per bot, with searchable, persistent transcript history\n- Edit, branch, rewind, pin, react, export, and share conversation content\n- Rooms for multi-agent collaboration and explicit bot-to-bot delegation\n- Queueing and steering while an agent is already working\n- Per-task token and cost visibility\n- Readable, editable bot memory"
  },
  {
    "id": "features#computers-and-tools",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "heading": "Computers and tools",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features#computers-and-tools",
    "text": "- Local computer control with explicit opt-in and approval boundaries on supported hosts; Ubuntu currently fails closed under an input-safety hold\n- Isolated Local VM desktops through Docker or Podman\n- Hosted Box cloud computers\n- A self-hosted Linux VPS backend over Docker's SSH transport\n- Live previews and in-app desktop takeover where the backend supports it\n- USB Android control through the Phone Harness skill\n- Connected apps through Composio, including multiple labeled accounts per toolkit"
  },
  {
    "id": "features#automation",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "heading": "Automation",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features#automation",
    "text": "- One-time and weekday routines\n- Webhook-triggered tasks with dedicated secret endpoints\n- Fresh task context and durable run receipts for each automated run\n- Notifications for work that needs attention"
  },
  {
    "id": "features#voice-and-access",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "heading": "Voice and access",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features#voice-and-access",
    "text": "- Spoken replies and per-bot ElevenLabs voices\n- Native macOS dictation and half-duplex call mode"
  },
  {
    "id": "features#desktop-experience",
    "title": "Feature overview",
    "description": "A map of the capabilities currently available in Murage.",
    "heading": "Desktop experience",
    "breadcrumb": "Murage docs → Feature overview",
    "where": "Murage docs → Feature overview",
    "url": "https://murage.app/docs/features#desktop-experience",
    "text": "- macOS, Windows, and Ubuntu packages\n- Theme switching and accessible contrast\n- Sidebar sections, compact headers, pinned messages, spoilers, and image attachments\n- Automatic updates on macOS and Windows\n\nmacOS has the broadest native integration. Ubuntu chat, preview, Cloud, and Local VM are available, while host control is temporarily disabled under an input-safety hold. Windows installers are not yet signed. Reaching your bots from a phone is on the roadmap, over your own tailnet in a browser; the iOS companion was retired before release."
  },
  {
    "id": "features/voice-and-memory#spoken-replies",
    "title": "Voice, dictation, and memory",
    "description": "Listen to agents, talk to them, and inspect what they remember.",
    "heading": "Spoken replies",
    "breadcrumb": "Murage docs → Features → Voice, dictation, and memory",
    "where": "Murage docs → Features → Voice, dictation, and memory",
    "url": "https://murage.app/docs/features/voice-and-memory#spoken-replies",
    "text": "Add an ElevenLabs key in App Settings, choose a voice, and use the speaker control on a response. Auto-speak can read new replies as they arrive.\n\nThe harness rewrites code-heavy Markdown into speech-friendly text before synthesis. Keys remain on the harness and never reach the renderer."
  },
  {
    "id": "features/voice-and-memory#call-mode",
    "title": "Voice, dictation, and memory",
    "description": "Listen to agents, talk to them, and inspect what they remember.",
    "heading": "Call mode",
    "breadcrumb": "Murage docs → Features → Voice, dictation, and memory",
    "where": "Murage docs → Features → Voice, dictation, and memory",
    "url": "https://murage.app/docs/features/voice-and-memory#call-mode",
    "text": "On macOS, call mode combines native on-device speech recognition with the configured ElevenLabs voice. It is deliberately half-duplex: the microphone pauses while the bot speaks to prevent the app from transcribing its own audio.\n\nTool progress and approval requests can be narrated during a call so long-running work does not sound disconnected."
  },
  {
    "id": "features/voice-and-memory#dictation",
    "title": "Voice, dictation, and memory",
    "description": "Listen to agents, talk to them, and inspect what they remember.",
    "heading": "Dictation",
    "breadcrumb": "Murage docs → Features → Voice, dictation, and memory",
    "where": "Murage docs → Features → Voice, dictation, and memory",
    "url": "https://murage.app/docs/features/voice-and-memory#dictation",
    "text": "The composer microphone uses Apple's local speech recognition in the macOS desktop build. Linux and Windows dictation are not currently shipped."
  },
  {
    "id": "features/voice-and-memory#memory",
    "title": "Voice, dictation, and memory",
    "description": "Listen to agents, talk to them, and inspect what they remember.",
    "heading": "Memory",
    "breadcrumb": "Murage docs → Features → Voice, dictation, and memory",
    "where": "Murage docs → Features → Voice, dictation, and memory",
    "url": "https://murage.app/docs/features/voice-and-memory#memory",
    "text": "Each bot can keep plain-text memory that you can inspect, correct, or delete. Memory is not a hidden remote profile; it lives with the local Murage data."
  },
  {
    "id": "getting-started/configuration#overview",
    "title": "Configuration",
    "description": "Understand engine paths, credentials, and the local configuration boundary.",
    "breadcrumb": "Murage docs → Getting started → Configuration",
    "where": "Murage docs → Getting started → Configuration",
    "url": "https://murage.app/docs/getting-started/configuration",
    "text": "Most users configure Murage from the app. The packaged desktop validates credentials before saving them and stores supported secrets with the operating system's secure storage."
  },
  {
    "id": "getting-started/configuration#engine-discovery",
    "title": "Configuration",
    "description": "Understand engine paths, credentials, and the local configuration boundary.",
    "heading": "Engine discovery",
    "breadcrumb": "Murage docs → Getting started → Configuration",
    "where": "Settings → Engines and choose its executable explicitly.",
    "url": "https://murage.app/docs/getting-started/configuration#engine-discovery",
    "text": "Murage checks the inherited process path, common install locations, and the login shell. If an engine is installed somewhere unusual, open Settings → Engines and choose its executable explicitly.\n\nExplicit paths are useful when you:\n- keep multiple CLI versions;\n- use a wrapper script;\n- installed an engine in a directory desktop apps cannot discover; or\n- launch Murage from a Windows shortcut or Linux application menu with a different environment from your terminal."
  },
  {
    "id": "getting-started/configuration#optional-credentials",
    "title": "Configuration",
    "description": "Understand engine paths, credentials, and the local configuration boundary.",
    "heading": "Optional credentials",
    "breadcrumb": "Murage docs → Getting started → Configuration",
    "where": "Murage docs → Getting started → Configuration",
    "url": "https://murage.app/docs/getting-started/configuration#optional-credentials",
    "text": "| Credential | Enables |\n|---|---|\n| Composio project key | Connected apps and OAuth sessions |\n| Box API key | Hosted Linux computers |\n| ElevenLabs API key | Spoken replies and voice mode |\n| OpenCode API key | Optional alternative to an existing OpenCode provider login |\n\nLocal agent chat works without these credentials."
  },
  {
    "id": "getting-started/configuration#environment-configuration",
    "title": "Configuration",
    "description": "Understand engine paths, credentials, and the local configuration boundary.",
    "heading": "Environment configuration",
    "breadcrumb": "Murage docs → Getting started → Configuration",
    "where": "Murage docs → Getting started → Configuration",
    "url": "https://murage.app/docs/getting-started/configuration#environment-configuration",
    "text": "Source and headless runs can set supported environment variables before starting the harness. The app-level settings are preferable for normal packaged use because they validate inputs and keep secret values out of the renderer."
  },
  {
    "id": "getting-started/configuration#per-instance-claude-tool-scope",
    "title": "Configuration",
    "description": "Understand engine paths, credentials, and the local configuration boundary.",
    "heading": "Per-instance Claude tool scope",
    "breadcrumb": "Murage docs → Getting started → Configuration",
    "where": "Murage docs → Getting started → Configuration",
    "url": "https://murage.app/docs/getting-started/configuration#per-instance-claude-tool-scope",
    "text": "Source and headless installations can give separate Claude instances different built-in tool sets in ~/.murage/config.json:\n\ntools selects Claude's available built-ins; an explicit empty array disables every built-in, while omitting it keeps Claude's default set. disallowedTools applies Claude tool-name patterns as an additional deny list. These settings do not grant or pre-approve MCP integrations, which remain controlled by the instance's mounted integrations and Murage permission flow.\n\nA prompt becomes conversation history and may be sent to an agent provider. Use App Settings or environment configuration for credentials."
  },
  {
    "id": "getting-started/first-bot#before-you-start",
    "title": "Create your first bot",
    "description": "Choose an engine, folder, and working style for a useful first agent.",
    "heading": "Before you start",
    "breadcrumb": "Murage docs → Getting started → Create your first bot",
    "where": "Install and sign in to at least one supported agent CLI. Murage detects installed engines during onboarding and again from App settings → Agent engines.",
    "url": "https://murage.app/docs/getting-started/first-bot#before-you-start",
    "text": "Install and sign in to at least one supported agent CLI. Murage detects installed engines during onboarding and again from App settings → Agent engines."
  },
  {
    "id": "getting-started/first-bot#create-the-bot",
    "title": "Create your first bot",
    "description": "Choose an engine, folder, and working style for a useful first agent.",
    "heading": "Create the bot",
    "breadcrumb": "Murage docs → Getting started → Create your first bot",
    "where": "Murage docs → Getting started → Create your first bot",
    "url": "https://murage.app/docs/getting-started/first-bot#create-the-bot",
    "text": "1. Select New or share in the sidebar.\n2. Choose New bot.\n3. Give the bot a clear name and purpose.\n4. Select its agent engine and model.\n5. Choose a working folder if it should edit files or work in a repository.\n\nThe working folder matters: it becomes the bot's starting context and limits accidental edits elsewhere. Use a dedicated project folder for coding, research, or content work."
  },
  {
    "id": "getting-started/first-bot#give-it-a-useful-first-task",
    "title": "Create your first bot",
    "description": "Choose an engine, folder, and working style for a useful first agent.",
    "heading": "Give it a useful first task",
    "breadcrumb": "Murage docs → Getting started → Create your first bot",
    "where": "Murage docs → Getting started → Create your first bot",
    "url": "https://murage.app/docs/getting-started/first-bot#give-it-a-useful-first-task",
    "text": "Start with a concrete outcome and the constraints that matter:\n\nOnce you trust the diagnosis, ask the bot to implement the change. This keeps review and mutation as separate, easy-to-check steps."
  },
  {
    "id": "getting-started/first-bot#tune-the-bot",
    "title": "Create your first bot",
    "description": "Choose an engine, folder, and working style for a useful first agent.",
    "heading": "Tune the bot",
    "breadcrumb": "Murage docs → Getting started → Create your first bot",
    "where": "Murage docs → Getting started → Create your first bot",
    "url": "https://murage.app/docs/getting-started/first-bot#tune-the-bot",
    "text": "Open Bot settings to change its name, avatar, instructions, engine, model, working folder, and computer setup. Different bots can use different engines and folders at the same time.\n\nMurage launches agent tools you installed. If an engine returns a 401 or asks you to sign in, finish that engine's own CLI login, then refresh detection in App settings."
  },
  {
    "id": "getting-started/installation#download-a-released-build",
    "title": "Installation",
    "description": "Install Murage on macOS, Windows, or Ubuntu.",
    "heading": "Download a released build",
    "breadcrumb": "Murage docs → Getting started → Installation",
    "where": "Verify that you downloaded it from the official Murage releases repository before choosing More info → Run anyway.",
    "url": "https://murage.app/docs/getting-started/installation#download-a-released-build",
    "text": "Choose your computer below. Each link always downloads the latest published build.\n\n| Platform | Recommended package | Notes |\n|---|---|---|\n| macOS Apple silicon | Download .dmg | Signed and notarized. Drag to Applications. |\n| macOS Intel | Download .dmg | Signed and notarized. |\n| Windows x64 | Download installer | Per-user installer; Windows signing is not yet available. |\n| Ubuntu 24.04 x64 | Download .deb · AppImage | The .deb is recommended; the AppImage is portable. |\n\nThe Windows installer is not code-signed yet. Windows may show “Unknown publisher.” Verify that you downloaded it from the official Murage releases repository before choosing More info → Run anyway."
  },
  {
    "id": "getting-started/installation#install-an-agent-cli",
    "title": "Installation",
    "description": "Install Murage on macOS, Windows, or Ubuntu.",
    "heading": "Install an agent CLI",
    "breadcrumb": "Murage docs → Getting started → Installation",
    "where": "Murage docs → Getting started → Installation",
    "url": "https://murage.app/docs/getting-started/installation#install-an-agent-cli",
    "text": "Murage needs at least one supported agent engine installed and signed in. Claude and Codex are the most common starting points.\n\n1. Install the CLI from its official provider.\n2. Run it once in a terminal and complete sign-in.\n3. Restart Murage.\n4. Open the model picker. Available engines appear normally; unavailable engines explain what is missing.\n\nSee Agent engines for the complete list and explicit path overrides."
  },
  {
    "id": "getting-started/installation#build-from-source",
    "title": "Installation",
    "description": "Install Murage on macOS, Windows, or Ubuntu.",
    "heading": "Build from source",
    "breadcrumb": "Murage docs → Getting started → Installation",
    "where": "Murage docs → Getting started → Installation",
    "url": "https://murage.app/docs/getting-started/installation#build-from-source",
    "text": "Requirements: Node.js 24 or newer, pnpm 10.33.0, and at least one authenticated agent CLI.\n\nRun the harness, web UI, and Electron shell in separate terminals:"
  },
  {
    "id": "getting-started/installation#where-data-lives",
    "title": "Installation",
    "description": "Install Murage on macOS, Windows, or Ubuntu.",
    "heading": "Where data lives",
    "breadcrumb": "Murage docs → Getting started → Installation",
    "where": "Murage docs → Getting started → Installation",
    "url": "https://murage.app/docs/getting-started/installation#where-data-lives",
    "text": "Murage stores its application data under ~/.murage. Electron window and browser data use the normal per-platform application data directory."
  },
  {
    "id": "getting-started/quick-tour#1-sidebar",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "1. Sidebar",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#1-sidebar",
    "text": "The sidebar holds your bots, groups, automations, connected apps, profile, and app settings. Search looks through bot names and message history. Use New or share to create a bot or start a shared room."
  },
  {
    "id": "getting-started/quick-tour#2-conversation",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "2. Conversation",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#2-conversation",
    "text": "Messages are the work log. Agent replies, questions, approval requests, tool progress, attachments, and failures stay together in the conversation. You can pin, copy, react to, search, and retry messages."
  },
  {
    "id": "getting-started/quick-tour#3-task-mode",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "3. Task mode",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#3-task-mode",
    "text": "The Task button starts a separate unit of work without losing the main conversation. A task keeps its own status and result, which is useful for parallel or delegated work."
  },
  {
    "id": "getting-started/quick-tour#4-model-picker",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "4. Model picker",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#4-model-picker",
    "text": "Pick an agent engine and model per bot. The picker separates cloud-backed agent CLIs from local engines and shows what is installed on this machine."
  },
  {
    "id": "getting-started/quick-tour#5-computer-and-inspector",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "5. Computer and inspector",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#5-computer-and-inspector",
    "text": "Open Bot's computer to choose where visual work runs. Open Inspector to follow lower-level activity when a task is executing."
  },
  {
    "id": "getting-started/quick-tour#6-connected-apps-and-automations",
    "title": "Quick tour",
    "description": "Learn the six parts of Murage before handing your first job to an agent.",
    "heading": "6. Connected apps and automations",
    "breadcrumb": "Murage docs → Getting started → Quick tour",
    "where": "Murage docs → Getting started → Quick tour",
    "url": "https://murage.app/docs/getting-started/quick-tour#6-connected-apps-and-automations",
    "text": "Connected apps give bots authenticated tools. Automations turn a good prompt into scheduled or webhook-triggered work."
  },
  {
    "id": "index#overview",
    "title": "Murage documentation",
    "description": "Build a team of AI agents that can talk, use tools, operate computers, and keep working on a schedule.",
    "breadcrumb": "Murage docs",
    "where": "Murage docs",
    "url": "https://murage.app/docs",
    "text": "Local-first agent workspace\n\nMurage turns agent CLIs into a familiar desktop chat app. Each bot can have its own model, instructions, working folder, connected apps, computer, and recurring work.\n\nMany enginesClaude, Codex, Grok, Cursor, local models, and more\nReal toolsApps, files, terminals, browsers, VMs, and cloud desktops\nYour machineLocal data and bring-your-own agent subscriptions"
  },
  {
    "id": "index#how-the-pieces-fit",
    "title": "Murage documentation",
    "description": "Build a team of AI agents that can talk, use tools, operate computers, and keep working on a schedule.",
    "heading": "How the pieces fit",
    "breadcrumb": "Murage docs",
    "where": "Murage docs",
    "url": "https://murage.app/docs#how-the-pieces-fit",
    "text": "| Layer | What it does | Where to configure it |\n|---|---|---|\n| Bot | Holds the identity, conversation, memory, and defaults | Bot settings |\n| Agent engine | Runs the reasoning loop and tools | Model picker and App settings |\n| Working folder | Gives the bot project context and a safe place to work | Bot settings |\n| Connected apps | Authorizes services such as Gmail or GitHub | Connected apps |\n| Computer | Gives visual control of a desktop environment | Computer panel |\n| Automation | Runs a task later, on a schedule, or from a webhook | Automations |"
  },
  {
    "id": "index#choose-your-path",
    "title": "Murage documentation",
    "description": "Build a team of AI agents that can talk, use tools, operate computers, and keep working on a schedule.",
    "heading": "Choose your path",
    "breadcrumb": "Murage docs",
    "where": "Murage docs",
    "url": "https://murage.app/docs#choose-your-path",
    "text": "| I want to… | Start here |\n|---|---|\n| Understand the app in five minutes | Quick tour |\n| Pick Claude, Codex, Cursor, Grok, or a local model | Agent engines |\n| Organize bots, tasks, rooms, and delegations | Bots and tasks |\n| Control a browser or desktop | Computers |\n| Run work every morning | Automations |\n| Reach my bots from a phone | On the roadmap: a browser client over your tailnet. The iOS companion was retired before release. |\n| Back up or move my data | Data and backups |\n| Build from source or contribute | Contributing |\n\nMurage moves quickly. The changelog records shipped releases; proposed or unfinished work stays on GitHub until it lands."
  },
  {
    "id": "providers#overview",
    "title": "Agent engines",
    "description": "Use the agent subscriptions and CLIs you already have.",
    "breadcrumb": "Murage docs → Agent engines",
    "where": "Murage docs → Agent engines",
    "url": "https://murage.app/docs/providers",
    "text": "Murage does not proxy every message through its own model account. It starts supported agent CLIs on your computer and normalizes their output through the local harness."
  },
  {
    "id": "providers#built-in-engines",
    "title": "Agent engines",
    "description": "Use the agent subscriptions and CLIs you already have.",
    "heading": "Built-in engines",
    "breadcrumb": "Murage docs → Agent engines",
    "where": "Murage docs → Agent engines",
    "url": "https://murage.app/docs/providers#built-in-engines",
    "text": "| Engine | Authentication shape | Notes |\n|---|---|---|\n| Claude | Claude CLI login | Strong support for tools, approvals, sessions, and local computer use |\n| Codex | Codex CLI login | Model discovery, approvals, steering, and computer tools |\n| Grok | Grok CLI login | ACP-based local model catalog and session support |\n| Cursor | Cursor Agent CLI login or API key | ACP driver with live model discovery |\n| Kimi | Kimi CLI login | ACP integration |\n| Droid | Factory Droid CLI login | ACP integration |\n| Antigravity | Google Antigravity CLI login | Default Google consumer engine |…"
  },
  {
    "id": "providers#detection",
    "title": "Agent engines",
    "description": "Use the agent subscriptions and CLIs you already have.",
    "heading": "Detection",
    "breadcrumb": "Murage docs → Agent engines",
    "where": "Settings → Engines to set an explicit executable path. This is supported for every engine and is the most reliable solution for version managers",
    "url": "https://murage.app/docs/providers#detection",
    "text": "Murage checks common installation directories and the login shell in the background. Restart the app after installing or authenticating a CLI.\n\nIf detection fails, use Settings → Engines to set an explicit executable path. This is supported for every engine and is the most reliable solution for version managers, wrappers, custom builds, and Windows installations outside the normal path."
  },
  {
    "id": "providers#model-selection",
    "title": "Agent engines",
    "description": "Use the agent subscriptions and CLIs you already have.",
    "heading": "Model selection",
    "breadcrumb": "Murage docs → Agent engines",
    "where": "Murage docs → Agent engines",
    "url": "https://murage.app/docs/providers#model-selection",
    "text": "The model picker groups models by provider and marks defaults. Supported engines can refresh their model catalog from the installed CLI. Changing the model affects future turns; it does not rewrite earlier transcript history.\n\nYour existing CLI login or provider API key determines access and billing. Murage does not turn one subscription into access to another provider."
  },
  {
    "id": "providers/troubleshooting#cli-not-found",
    "title": "Engine troubleshooting",
    "description": "Fix missing CLIs, failed authentication, model errors, and path differences.",
    "heading": "“CLI not found”",
    "breadcrumb": "Murage docs → Providers → Engine troubleshooting",
    "where": "Set the exact executable in Settings → Engines if automatic detection still fails.",
    "url": "https://murage.app/docs/providers/troubleshooting#cli-not-found",
    "text": "1. Open a terminal and run the CLI directly.\n2. Confirm the command is an executable, not only a shell alias or function.\n3. Restart Murage after installation.\n4. Set the exact executable in Settings → Engines if automatic detection still fails.\n\nDesktop applications often inherit a different environment than a terminal. This is common on Windows shortcuts, macOS Finder launches, and Linux application menus."
  },
  {
    "id": "providers/troubleshooting#authentication-failures",
    "title": "Engine troubleshooting",
    "description": "Fix missing CLIs, failed authentication, model errors, and path differences.",
    "heading": "Authentication failures",
    "breadcrumb": "Murage docs → Providers → Engine troubleshooting",
    "where": "Murage docs → Providers → Engine troubleshooting",
    "url": "https://murage.app/docs/providers/troubleshooting#authentication-failures",
    "text": "Run the provider's own status or login command in a terminal. Murage uses the CLI's authenticated session; installing the binary alone is not enough.\n\nA 401 Unauthorized response from api.openai.com means the launched Codex process did not receive valid authentication. Confirm codex login status, sign in again if needed, then restart Murage. Do not paste a ChatGPT password into Murage."
  },
  {
    "id": "providers/troubleshooting#a-selected-model-fails",
    "title": "Engine troubleshooting",
    "description": "Fix missing CLIs, failed authentication, model errors, and path differences.",
    "heading": "A selected model fails",
    "breadcrumb": "Murage docs → Providers → Engine troubleshooting",
    "where": "Murage docs → Providers → Engine troubleshooting",
    "url": "https://murage.app/docs/providers/troubleshooting#a-selected-model-fails",
    "text": "- Refresh the model picker after updating the CLI.\n- Choose a model actually available to that provider account.\n- Confirm a custom wrapper forwards the model argument and preserves the provider's expected environment.\n- Try the provider CLI directly with the same model to separate an account problem from an Murage integration problem."
  },
  {
    "id": "providers/troubleshooting#windows-notes",
    "title": "Engine troubleshooting",
    "description": "Fix missing CLIs, failed authentication, model errors, and path differences.",
    "heading": "Windows notes",
    "breadcrumb": "Murage docs → Providers → Engine troubleshooting",
    "where": "Murage docs → Providers → Engine troubleshooting",
    "url": "https://murage.app/docs/providers/troubleshooting#windows-notes",
    "text": "Use a real .exe, .cmd, or resolvable command path in the engine override. If a CLI was installed in WSL, the Windows desktop app cannot treat that Linux binary as a native Windows executable without an explicit bridge or wrapper."
  },
  {
    "id": "security#overview",
    "title": "Security model",
    "description": "The boundaries that keep agents, credentials, computers, and paired devices scoped.",
    "breadcrumb": "Murage docs → Security model",
    "where": "Murage docs → Security model",
    "url": "https://murage.app/docs/security",
    "text": "Murage is designed around a local owner, explicit capabilities, and narrow process boundaries. Local-first does not mean risk-free: an agent with tool or computer access can still act on the resources you grant it."
  },
  {
    "id": "security#core-boundaries",
    "title": "Security model",
    "description": "The boundaries that keep agents, credentials, computers, and paired devices scoped.",
    "heading": "Core boundaries",
    "breadcrumb": "Murage docs → Security model",
    "where": "Murage docs → Security model",
    "url": "https://murage.app/docs/security#core-boundaries",
    "text": "- The harness owns agent processes and listens on loopback.\n- The renderer receives configured-or-not credential state, not secret values.\n- Provider-specific credentials are injected only into the process that needs them.\n- Risky actions become approval cards rather than implicit permission.\n- Local computer control is a separate opt-in and per-bot selection.\n- Paired phones use a default-deny API allowlist and per-device bearer tokens.\n- Cloud and VPS backends are validated before reuse."
  },
  {
    "id": "security#your-responsibility",
    "title": "Security model",
    "description": "The boundaries that keep agents, credentials, computers, and paired devices scoped.",
    "heading": "Your responsibility",
    "breadcrumb": "Murage docs → Security model",
    "where": "Murage docs → Security model",
    "url": "https://murage.app/docs/security#your-responsibility",
    "text": "- Review approvals, especially shell commands, file writes, and actions in connected services.\n- Use dedicated environments for untrusted or destructive work.\n- Keep provider accounts and connected apps scoped to what a bot needs.\n- Revoke lost companion devices immediately.\n- Keep Murage and agent CLIs updated.\n\nSecurity reports should be filed through the repository's documented security channel rather than disclosed in a public issue before a fix is available."
  },
  {
    "id": "security/permissions-and-secrets#approval-cards",
    "title": "Permissions and secrets",
    "description": "How approvals, operating-system grants, and provider credentials are handled.",
    "heading": "Approval cards",
    "breadcrumb": "Murage docs → Security → Permissions and secrets",
    "where": "Murage docs → Security → Permissions and secrets",
    "url": "https://murage.app/docs/security/permissions-and-secrets#approval-cards",
    "text": "Supported providers emit permission requests and questions through the local harness. Murage displays these inline and records the outcome. Cancellation closes outstanding requests so stale approvals cannot be answered after a turn has ended.\n\n“Always allow” is narrow: it is tied to a server-issued key and a pending request rather than granting arbitrary execution from a paired device."
  },
  {
    "id": "security/permissions-and-secrets#operating-system-permissions",
    "title": "Permissions and secrets",
    "description": "How approvals, operating-system grants, and provider credentials are handled.",
    "heading": "Operating-system permissions",
    "breadcrumb": "Murage docs → Security → Permissions and secrets",
    "where": "Murage docs → Security → Permissions and secrets",
    "url": "https://murage.app/docs/security/permissions-and-secrets#operating-system-permissions",
    "text": "Screen Recording and Accessibility permissions are controlled by the operating system. The desktop process owns local CUA lifecycle so grants are attributed to Murage."
  },
  {
    "id": "security/permissions-and-secrets#secret-handling",
    "title": "Permissions and secrets",
    "description": "How approvals, operating-system grants, and provider credentials are handled.",
    "heading": "Secret handling",
    "breadcrumb": "Murage docs → Security → Permissions and secrets",
    "where": "Murage docs → Security → Permissions and secrets",
    "url": "https://murage.app/docs/security/permissions-and-secrets#secret-handling",
    "text": "- Do not paste API keys into chat.\n- Packaged builds use write-only settings and operating-system-backed encryption where supported.\n- Secret values are scrubbed from public configuration responses and mobile APIs.\n- Per-provider environment injection prevents unrelated agent processes from inheriting credentials they do not use.\n- OAuth provider tokens for connected apps stay with Composio."
  },
  {
    "id": "security/permissions-and-secrets#shared-machines",
    "title": "Permissions and secrets",
    "description": "How approvals, operating-system grants, and provider credentials are handled.",
    "heading": "Shared machines",
    "breadcrumb": "Murage docs → Security → Permissions and secrets",
    "where": "Murage docs → Security → Permissions and secrets",
    "url": "https://murage.app/docs/security/permissions-and-secrets#shared-machines",
    "text": "Murage assumes the logged-in operating-system user is the workspace owner. On a shared machine, other administrators may be able to read application data or inspect processes. Use a dedicated OS account for stronger separation."
  },
  {
    "id": "self-hosting/data-and-backups#overview",
    "title": "Data and backups",
    "description": "Know what Murage stores locally and what to preserve.",
    "breadcrumb": "Murage docs → Self hosting → Data and backups",
    "where": "Murage docs → Self hosting → Data and backups",
    "url": "https://murage.app/docs/self-hosting/data-and-backups",
    "text": "Murage keeps its application state under ~/.murage, including configuration, transcripts, message attachments, device pairing state, and the SQLite message store."
  },
  {
    "id": "self-hosting/data-and-backups#back-up",
    "title": "Data and backups",
    "description": "Know what Murage stores locally and what to preserve.",
    "heading": "Back up",
    "breadcrumb": "Murage docs → Self hosting → Data and backups",
    "where": "Murage docs → Self hosting → Data and backups",
    "url": "https://murage.app/docs/self-hosting/data-and-backups#back-up",
    "text": "Close Murage before taking a filesystem-level backup so SQLite and configuration files are captured consistently. Preserve the entire .murage directory rather than selecting individual database files."
  },
  {
    "id": "self-hosting/data-and-backups#do-not-copy-secrets-casually",
    "title": "Data and backups",
    "description": "Know what Murage stores locally and what to preserve.",
    "heading": "Do not copy secrets casually",
    "breadcrumb": "Murage docs → Self hosting → Data and backups",
    "where": "Murage docs → Self hosting → Data and backups",
    "url": "https://murage.app/docs/self-hosting/data-and-backups#do-not-copy-secrets-casually",
    "text": "Packaged desktop builds may protect credentials using operating-system secure storage. Copying the JSON directory to another machine does not necessarily make protected credentials usable there, and it should not be treated as a portable credential export."
  },
  {
    "id": "self-hosting/data-and-backups#disposable-computer-filesystems",
    "title": "Data and backups",
    "description": "Know what Murage stores locally and what to preserve.",
    "heading": "Disposable computer filesystems",
    "breadcrumb": "Murage docs → Self hosting → Data and backups",
    "where": "Murage docs → Self hosting → Data and backups",
    "url": "https://murage.app/docs/self-hosting/data-and-backups#disposable-computer-filesystems",
    "text": "Local VM workspaces are mounted durably, but a self-hosted VPS container filesystem is intentionally disposable. Move important artifacts to a durable workspace, repository, or connected app before removing or upgrading a container."
  },
  {
    "id": "self-hosting#overview",
    "title": "Self-hosting Murage",
    "description": "Run the harness and desktop app on infrastructure you control.",
    "breadcrumb": "Murage docs → Self-hosting Murage",
    "where": "Murage docs → Self-hosting Murage",
    "url": "https://murage.app/docs/self-hosting",
    "text": "Murage is local-first by default: the harness listens on loopback, agent CLIs run on your machine, and application state lives under ~/.murage."
  },
  {
    "id": "self-hosting#typical-self-hosted-setup",
    "title": "Self-hosting Murage",
    "description": "Run the harness and desktop app on infrastructure you control.",
    "heading": "Typical self-hosted setup",
    "breadcrumb": "Murage docs → Self-hosting Murage",
    "where": "Murage docs → Self-hosting Murage",
    "url": "https://murage.app/docs/self-hosting#typical-self-hosted-setup",
    "text": "1. Run Murage on your personal macOS, Windows, or Ubuntu computer.\n2. Install and authenticate the agent CLIs you want to use.\n3. Add optional third-party keys only for the services you need.\n4. Keep the harness on loopback.\n5. Use the paired companion sidecar or Tailscale when another device needs access."
  },
  {
    "id": "self-hosting#what-is-still-third-party",
    "title": "Self-hosting Murage",
    "description": "Run the harness and desktop app on infrastructure you control.",
    "heading": "What is still third party",
    "breadcrumb": "Murage docs → Self-hosting Murage",
    "where": "Murage docs → Self-hosting Murage",
    "url": "https://murage.app/docs/self-hosting#what-is-still-third-party",
    "text": "Self-hosting Murage does not self-host every optional provider:\n- Agent providers authenticate and bill through their own CLI or API.\n- Composio owns connected-app OAuth grants unless you replace that integration.\n- Box owns managed cloud computers.\n- ElevenLabs synthesizes speech when voice is enabled.\n\nThese services are optional. Local chat through a locally installed agent CLI does not require them."
  },
  {
    "id": "self-hosting#run-headless-during-development",
    "title": "Self-hosting Murage",
    "description": "Run the harness and desktop app on infrastructure you control.",
    "heading": "Run headless during development",
    "breadcrumb": "Murage docs → Self-hosting Murage",
    "where": "Murage docs → Self-hosting Murage",
    "url": "https://murage.app/docs/self-hosting#run-headless-during-development",
    "text": "The main harness listens on 127.0.0.1:8799 by default. Keep it private; it owns agent processes, approvals, computers, and workspace configuration."
  },
  {
    "id": "self-hosting/networking#overview",
    "title": "Networking",
    "description": "Understand the harness, webhook, and companion network boundaries.",
    "breadcrumb": "Murage docs → Self hosting → Networking",
    "where": "Murage docs → Self hosting → Networking",
    "url": "https://murage.app/docs/self-hosting/networking",
    "text": "Murage separates its network surfaces by trust level.\n\n| Surface | Default bind | Purpose |\n|---|---|---|\n| Harness | 127.0.0.1:8799 | Full app API and event stream |\n| Webhook receiver | 127.0.0.1:8800 | Health and secret hook endpoints only |\n| Companion sidecar | 0.0.0.0:8810 when enabled | Paired-device, token-authenticated allowlist |\n| Companion control | 127.0.0.1:8811 | Pairing and device administration |"
  },
  {
    "id": "self-hosting/networking#remote-access",
    "title": "Networking",
    "description": "Understand the harness, webhook, and companion network boundaries.",
    "heading": "Remote access",
    "breadcrumb": "Murage docs → Self hosting → Networking",
    "where": "Murage docs → Self hosting → Networking",
    "url": "https://murage.app/docs/self-hosting/networking#remote-access",
    "text": "Use the companion sidecar rather than exposing the harness. Tailscale is the recommended remote route because it encrypts and authenticates the network path without making the machine public.\n\nFor webhook delivery, proxy only the dedicated webhook receiver. Never forward the main harness port to the public internet."
  },
  {
    "id": "self-hosting/networking#port-overrides",
    "title": "Networking",
    "description": "Understand the harness, webhook, and companion network boundaries.",
    "heading": "Port overrides",
    "breadcrumb": "Murage docs → Self hosting → Networking",
    "where": "Murage docs → Self hosting → Networking",
    "url": "https://murage.app/docs/self-hosting/networking#port-overrides",
    "text": "Source and advanced deployments can change documented ports with the relevant environment settings. When the default harness port is occupied, packaged builds may fall back to another local port and communicate the selected address internally."
  },
  {
    "id": "troubleshooting/connected-apps#connection-completes-but-the-app-still-shows-disconnected",
    "title": "Connected apps",
    "description": "Fix OAuth loops, missing tools, and connections that appear to vanish.",
    "heading": "Connection completes but the app still shows disconnected",
    "breadcrumb": "Murage docs → Troubleshooting → Connected apps",
    "where": "Murage docs → Troubleshooting → Connected apps",
    "url": "https://murage.app/docs/troubleshooting/connected-apps#connection-completes-but-the-app-still-shows-disconnected",
    "text": "1. Return to Murage after the browser confirms success.\n2. Open Connected apps and use Refresh connection status.\n3. Check the Connected tab for the account, including its alias.\n4. Retry from the original bot after the account appears active."
  },
  {
    "id": "troubleshooting/connected-apps#the-account-is-connected-but-the-agent-cannot-use-it",
    "title": "Connected apps",
    "description": "Fix OAuth loops, missing tools, and connections that appear to vanish.",
    "heading": "The account is connected but the agent cannot use it",
    "breadcrumb": "Murage docs → Troubleshooting → Connected apps",
    "where": "Murage docs → Troubleshooting → Connected apps",
    "url": "https://murage.app/docs/troubleshooting/connected-apps#the-account-is-connected-but-the-agent-cannot-use-it",
    "text": "Start a new task after connecting the app so the engine receives a fresh tool catalog. Name the service and account explicitly in the request. If several accounts are connected, select or mention the intended alias.\n\nSome engines expose connected tools differently. Verify the chosen engine supports MCP or the connected-tool bridge used by the app."
  },
  {
    "id": "troubleshooting/connected-apps#official-build-says-the-service-is-unavailable",
    "title": "Connected apps",
    "description": "Fix OAuth loops, missing tools, and connections that appear to vanish.",
    "heading": "Official build says the service is unavailable",
    "breadcrumb": "Murage docs → Troubleshooting → Connected apps",
    "where": "Murage docs → Troubleshooting → Connected apps",
    "url": "https://murage.app/docs/troubleshooting/connected-apps#official-build-says-the-service-is-unavailable",
    "text": "Check internet connectivity and try again later before reconnecting every account. The packaged app preserves its installation identity across transient broker outages; rotating or deleting local credentials during an outage can separate existing grants from the installation."
  },
  {
    "id": "troubleshooting/connected-apps#self-hosted-build-asks-for-configuration",
    "title": "Connected apps",
    "description": "Fix OAuth loops, missing tools, and connections that appear to vanish.",
    "heading": "Self-hosted build asks for configuration",
    "breadcrumb": "Murage docs → Troubleshooting → Connected apps",
    "where": "Murage docs → Troubleshooting → Connected apps",
    "url": "https://murage.app/docs/troubleshooting/connected-apps#self-hosted-build-asks-for-configuration",
    "text": "Source and self-hosted builds do not automatically use the official managed service. Configure your own Composio project as described in Self-hosted Composio."
  },
  {
    "id": "troubleshooting#overview",
    "title": "Troubleshooting",
    "description": "Find the failing layer first, then apply the smallest safe fix.",
    "breadcrumb": "Murage docs → Troubleshooting",
    "where": "Murage docs → Troubleshooting",
    "url": "https://murage.app/docs/troubleshooting",
    "text": "Most Murage failures come from one of four layers: the desktop app, a local agent CLI, a connected service, or a computer backend."
  },
  {
    "id": "troubleshooting#collect-useful-evidence",
    "title": "Troubleshooting",
    "description": "Find the failing layer first, then apply the smallest safe fix.",
    "heading": "Collect useful evidence",
    "breadcrumb": "Murage docs → Troubleshooting",
    "where": "Murage docs → Troubleshooting",
    "url": "https://murage.app/docs/troubleshooting#collect-useful-evidence",
    "text": "Before opening an issue, record:\n- Murage version and operating system;\n- selected engine and model;\n- the exact visible error, not only “it failed”;\n- whether the same agent CLI works directly in a terminal;\n- whether restarting only the affected task changes the result.\n\nNever post API keys, OAuth callback URLs, bearer tokens, or the contents of secure credential files."
  },
  {
    "id": "troubleshooting/startup-and-ports#overview",
    "title": "App startup and ports",
    "description": "Diagnose launch failures and local server conflicts.",
    "breadcrumb": "Murage docs → Troubleshooting → App startup and ports",
    "where": "Murage docs → Troubleshooting → App startup and ports",
    "url": "https://murage.app/docs/troubleshooting/startup-and-ports",
    "text": "The Electron app starts a local harness and serves the interface from the same machine. The normal port is 8799. If another process already owns it, packaged builds may select a fallback port automatically."
  },
  {
    "id": "troubleshooting/startup-and-ports#app-opens-but-never-becomes-ready",
    "title": "App startup and ports",
    "description": "Diagnose launch failures and local server conflicts.",
    "heading": "App opens but never becomes ready",
    "breadcrumb": "Murage docs → Troubleshooting → App startup and ports",
    "where": "Murage docs → Troubleshooting → App startup and ports",
    "url": "https://murage.app/docs/troubleshooting/startup-and-ports#app-opens-but-never-becomes-ready",
    "text": "1. Quit every Murage window.\n2. Confirm no old Murage process remains.\n3. Start the app once and wait for the local harness.\n4. If it still fails, inspect the desktop log.\n\nOn macOS, packaged logs are under ~/Library/Logs/Murage. On Windows they are under the Murage log directory in %APPDATA%."
  },
  {
    "id": "troubleshooting/startup-and-ports#development-port-overrides",
    "title": "App startup and ports",
    "description": "Diagnose launch failures and local server conflicts.",
    "heading": "Development port overrides",
    "breadcrumb": "Murage docs → Troubleshooting → App startup and ports",
    "where": "Murage docs → Troubleshooting → App startup and ports",
    "url": "https://murage.app/docs/troubleshooting/startup-and-ports#development-port-overrides",
    "text": "Use MURAGEPORT for a source-run harness. A packaged desktop build owns its server lifecycle and may choose a fallback if the preferred port is unavailable."
  },
  {
    "id": "troubleshooting/startup-and-ports#isolate-a-test-profile",
    "title": "App startup and ports",
    "description": "Diagnose launch failures and local server conflicts.",
    "heading": "Isolate a test profile",
    "breadcrumb": "Murage docs → Troubleshooting → App startup and ports",
    "where": "Murage docs → Troubleshooting → App startup and ports",
    "url": "https://murage.app/docs/troubleshooting/startup-and-ports#isolate-a-test-profile",
    "text": "Developers can set MURAGEDATADIR to run against a clean Murage data directory. This is useful for reproduction and screenshots without touching a real workspace."
  },
  {
    "id": "troubleshooting/updates#overview",
    "title": "Desktop updates",
    "description": "Recover from a stuck download or restart and understand supported update paths.",
    "breadcrumb": "Murage docs → Troubleshooting → Desktop updates",
    "where": "Murage docs → Troubleshooting → Desktop updates",
    "url": "https://murage.app/docs/troubleshooting/updates",
    "text": "Murage checks for updates in the background and offers the download in a card at the bottom of the window. How the download is applied depends on what you installed.\n\n| Build | What the button does |\n|---|---|\n| macOS, Windows, Linux AppImage | Restart to update: the app replaces itself and reopens. An AppImage is always rewritten at the path you launch, so your launcher, symlink or dock pin keeps working. |\n| Ubuntu .deb (and rpm/pacman) | Install: Murage downloads and verifies the package, copies the install command, and opens a terminal for you to paste it into. The app never installs a system package itself, so it never asks for your administrator password. |…"
  },
  {
    "id": "troubleshooting/updates#the-download-keeps-spinning",
    "title": "Desktop updates",
    "description": "Recover from a stuck download or restart and understand supported update paths.",
    "heading": "The download keeps spinning",
    "breadcrumb": "Murage docs → Troubleshooting → Desktop updates",
    "where": "Murage docs → Troubleshooting → Desktop updates",
    "url": "https://murage.app/docs/troubleshooting/updates#the-download-keeps-spinning",
    "text": "Leave the app open long enough for one complete attempt, then quit and reopen it. A failed differential update should fall back to the full package. If the same release remains stuck, download the current installer from the official releases repository and install it over the existing copy."
  },
  {
    "id": "troubleshooting/updates#restart-to-update-does-nothing",
    "title": "Desktop updates",
    "description": "Recover from a stuck download or restart and understand supported update paths.",
    "heading": "Restart to update does nothing",
    "breadcrumb": "Murage docs → Troubleshooting → Desktop updates",
    "where": "Murage docs → Troubleshooting → Desktop updates",
    "url": "https://murage.app/docs/troubleshooting/updates#restart-to-update-does-nothing",
    "text": "Quit Murage completely and launch it again. If the version did not change, install the latest release manually. Your conversations and settings live outside the application bundle and are not removed by replacing the app."
  },
  {
    "id": "troubleshooting/updates#no-terminal-opened",
    "title": "Desktop updates",
    "description": "Recover from a stuck download or restart and understand supported update paths.",
    "heading": "No terminal opened",
    "breadcrumb": "Murage docs → Troubleshooting → Desktop updates",
    "where": "Murage docs → Troubleshooting → Desktop updates",
    "url": "https://murage.app/docs/troubleshooting/updates#no-terminal-opened",
    "text": "The install command is on your clipboard either way. Open a terminal yourself and paste it. If the clipboard was overwritten, the package is already downloaded and you can run:\n\nUse apt-get, not dpkg -i: only apt-get resolves dependencies, and on Ubuntu 24.04 ours are satisfied through virtual packages that dpkg alone will not follow."
  },
  {
    "id": "troubleshooting/updates#verify-the-installed-version",
    "title": "Desktop updates",
    "description": "Recover from a stuck download or restart and understand supported update paths.",
    "heading": "Verify the installed version",
    "breadcrumb": "Murage docs → Troubleshooting → Desktop updates",
    "where": "Murage docs → Troubleshooting → Desktop updates",
    "url": "https://murage.app/docs/troubleshooting/updates#verify-the-installed-version",
    "text": "Open App settings and check the displayed version. A commit merged to main is not in the desktop app until a release workflow publishes a new version.\n\nDo not install update files forwarded through chat or uploaded to an unrelated repository. Use the Murage releases repository and its checksums."
  }
];
