#!/usr/bin/env node
// Fake of the codex CLI's `app-server` JSON-RPC surface, for driver
// tests. Speaks newline-delimited JSON-RPC on stdio: answers the
// initialize/thread/turn handshake, then plays a scripted turn. Like the
// real app-server, it never exits on its own — the driver kills it.
//
//   FAKE_CODEX_MODE   happy (default) | approval | resume | stream | windows-command |
//                     mcp-elicitation | form-elicitation | user-input | image |
//                     logged-in-stdout | logged-out | unauthorized
//   FAKE_CODEX_DUMP   path to write {argv, env, calls, decision} as JSON
//   FAKE_CODEX_LAUNCH_CRASHES  N: die at thread/start (before turn/start is ever sent)
//                     with transient stderr, exit 1, for the first N launches
//   FAKE_CODEX_LAUNCH_KILLS    N: same phase, transient stderr then SIGKILL (a signal
//                     exit; POSIX-shaped — win32 reports exit 1, signal null)
//   FAKE_CODEX_LAUNCH_SILENT   N: same phase, exit 1 with no new stderr. With
//                     FAKE_CODEX_STALE_STDERR_GATE (a gate path) it first writes
//                     transient-looking stderr and answers initialize only once
//                     the test saw that stderr, so the stale line is read before
//                     a later protocol message
//   FAKE_CODEX_PREACK_CRASH    plain | buffered: after turn/start was received and
//                     before its ACK, (buffered: one turn notification, then)
//                     transient stderr and exit 1
//   FAKE_CODEX_ACK_CRASH       gate path: ACK turn/start, then once the test saw the
//                     driver read that ACK, transient stderr and exit 1
//   FAKE_CODEX_EXIT_MID_TURN   gate path: stale websocket-426 stderr; once the test saw
//                     it, ACK plus one reasoning delta; then SIGKILL once
//                     FAKE_CODEX_EXIT_MID_TURN_KILL (gate path) appears
//                     Launch counts for these knobs go to FAKE_CODEX_STATE.
//   FAKE_CODEX_STOP_RACE  marker file path: hold turn/start, append one line to
//                     the marker (the launch count, and proof this phase was
//                     reached), and answer the held request with a transient
//                     503 error only from the SIGTERM handler — so the failure
//                     is strictly caused by, and observed after, the driver's
//                     Stop. POSIX-shaped: win32 has no SIGTERM handler.
//
// Keep this file dependency-free — it runs as a bare `node` subprocess.
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { writeFileAtomic } from "../atomic.ts";

const mode = process.env.FAKE_CODEX_MODE ?? "happy";

// stdout and stderr are separate pipes, so the writer cannot order them for
// the reader, and a fixed sleep only pretends to. A gated write waits until
// the test, watching the driver consume the earlier stream, creates the gate
// file. It gives up after a long bound so a broken gate fails the test rather
// than hanging it.
const waitForGate = (path: string | undefined, timeoutMs = 15_000): Promise<void> =>
  new Promise((resolve) => {
    const startedAt = Date.now();
    const timer = setInterval(() => {
      if ((path !== undefined && existsSync(path)) || Date.now() - startedAt > timeoutMs) {
        clearInterval(timer);
        resolve();
      }
    }, 2);
  });

/** Records one turn launch in FAKE_CODEX_STATE; returns the prior count. */
const countLaunch = (): number => {
  const stateFile = process.env.FAKE_CODEX_STATE;
  if (!stateFile) return 0;
  let launched = 0;
  try {
    launched = Number(readFileSync(stateFile, "utf8")) || 0;
  } catch {}
  writeFileSync(stateFile, String(launched + 1));
  return launched;
};
const TRANSIENT_STDERR = "Error: connection reset by peer\n";

if (process.argv[2] === "--version") {
  process.stdout.write("codex-cli 0.147.0\n");
  process.exit(0);
}
if (process.argv[2] === "login" && process.argv[3] === "status") {
  if (mode === "logged-out") {
    process.stderr.write("Not logged in\n");
    process.exit(1);
  }
  // Codex 0.147.0 reports a successful login on stderr; retain a mode for
  // older versions that wrote the same status on stdout.
  const statusStream = mode === "logged-in-stdout" ? process.stdout : process.stderr;
  statusStream.write("Logged in using ChatGPT\n");
  process.exit(0);
}
const calls: Array<{ method: string; params: unknown }> = [];
let decision: unknown = null;

const out = (obj: unknown) => process.stdout.write(JSON.stringify(obj) + "\n");
let nativeThreadId = "codex-thread-1";
const nativeTurnId = "turn-1";
// v2 schema generated by codex-cli 0.144.4: items/usage/errors carry
// threadId+turnId; turn lifecycle carries threadId+turn.id.
const notification = (method: string, params: Record<string, any>) => ({
  jsonrpc: "2.0", method,
  params: method.startsWith("turn/")
    ? { threadId: nativeThreadId, ...params, turn: { id: nativeTurnId, items: [], error: null, ...params.turn } }
    : { threadId: nativeThreadId, turnId: nativeTurnId, ...params },
});
const notify = (method: string, params: Record<string, any>) => out(notification(method, params));
const turnResult = () => ({ turn: { id: nativeTurnId, status: "inProgress", items: [], error: null } });
// Mirrors ENGINE_FRAME_MAX_BYTES in server/drivers/bounded-lines.ts. "é" is
// two UTF-8 bytes: the text alone is one KiB over the limit.
const FIXTURE_FRAME_LIMIT = 32 * 1024 * 1024;
const fixtureOversizeText = () => "é".repeat(FIXTURE_FRAME_LIMIT / 2 + 512);
const fixtureLargeImageBase64 = () => Buffer.alloc(10 * 1024 * 1024, 7).toString("base64");
// Markers count only on the prompt's last line (the current request): the
// harness replays earlier messages into a fresh process's prompt, and an old
// marker there must not re-trigger a fixture on a later, ordinary turn.
const fixtureRequested = (text: string, marker: string) => (text.trimEnd().split("\n").pop() ?? "").includes(marker);

const dump = () => {
  if (process.env.FAKE_CODEX_DUMP) {
    writeFileAtomic(
      process.env.FAKE_CODEX_DUMP,
      JSON.stringify({ pid: process.pid, argv: process.argv.slice(2), env: process.env, calls, decision }, null, 2),
    );
  }
};

if (mode === "late-output") {
  process.on("SIGTERM", () => {
    setTimeout(() => {
      notify("item/agentMessage/delta", { itemId: "late-chunk", delta: "late chunk must be ignored" });
    }, 20);
    setTimeout(() => process.exit(0), Number(process.env.FAKE_CODEX_SHUTDOWN_DELAY_MS ?? 150));
  });
}

const finishTurn = () => {
  notify("item/completed", { item: { id: "i1", type: "commandExecution", status: "completed" } });
  notify("item/completed", { item: { id: "w1", type: "webSearch", status: "completed" } });
  if (mode === "stream") {
    // token deltas, then the whole message — the driver must not double-emit
    notify("item/agentMessage/delta", { itemId: "m1", delta: "done from " });
    notify("item/agentMessage/delta", { itemId: "m1", delta: "fake codex" });
  }
  if (mode === "image") {
    notify("item/completed", {
      item: {
        id: "img1",
        type: "imageGeneration",
        status: "completed",
        result: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
        revisedPrompt: "a tiny green mouse",
        savedPath: "/tmp/provider-owned-path-must-not-be-read.png",
      },
    });
  }
  // Publish PID/state before the observable message used by lifecycle tests.
  dump();
  notify("item/completed", { item: { id: "m1", type: "agentMessage", text: "done from fake codex" } });
  notify("thread/tokenUsage/updated", { tokenUsage: { total: { inputTokens: 7, cachedInputTokens: 4, outputTokens: 3 } } });
  dump();
  if (mode === "late-output") {
    // One write ensures the completion and late frame share the parser buffer.
    process.stdout.write([
      notification("turn/completed", { turn: { status: "completed" } }),
      notification("item/agentMessage/delta", { itemId: "late-buffer", delta: "late buffered text must be ignored" }),
    ].map((message) => JSON.stringify(message)).join("\n") + "\n");
  } else notify("turn/completed", { turn: { status: "completed" } });
};

let buf = "";
process.stdin.on("data", (chunk) => {
  buf += chunk;
  let nl;
  while ((nl = buf.indexOf("\n")) !== -1) {
    const line = buf.slice(0, nl);
    buf = buf.slice(nl + 1);
    if (!line.trim()) continue;
    let msg: any;
    try {
      msg = JSON.parse(line);
    } catch {
      continue;
    }

    // response to our own server->client request (approval decision)
    if ((msg.id === 100 || msg.id === 101) && (msg.result !== undefined || msg.error !== undefined)) {
      decision = msg.result ?? { error: msg.error };
      finishTurn();
      continue;
    }

    if (msg.method) calls.push({ method: msg.method, params: msg.params ?? null });

    switch (msg.method) {
      case "initialize":
        if (process.env.FAKE_CODEX_LAUNCH_SILENT && process.env.FAKE_CODEX_STALE_STDERR_GATE) {
          const initializeId = msg.id;
          process.stderr.write(TRANSIENT_STDERR);
          void waitForGate(process.env.FAKE_CODEX_STALE_STDERR_GATE).then(() => {
            out({ jsonrpc: "2.0", id: initializeId, result: { ok: true } });
          });
          break;
        }
        out({ jsonrpc: "2.0", id: msg.id, result: { ok: true } });
        break;
      case "model/list":
        if (msg.params?.cursor === "page-2") {
          out({
            jsonrpc: "2.0",
            id: msg.id,
            result: {
              data: [
                { id: "gpt-hidden", displayName: "Hidden", hidden: true, isDefault: false },
                { id: "gpt-page-two", displayName: "GPT Page Two", hidden: false, isDefault: false },
              ],
              nextCursor: null,
            },
          });
        } else {
          out({
            jsonrpc: "2.0",
            id: msg.id,
            result: {
              data: [
                { id: "gpt-fake-default", displayName: "GPT Fake Default", hidden: false, isDefault: true },
              ],
              nextCursor: "page-2",
            },
          });
        }
        break;
      case "thread/resume":
        if (mode === "resume") {
          out({ jsonrpc: "2.0", id: msg.id, result: { thread: { id: msg.params?.threadId } } });
        } else {
          out({ jsonrpc: "2.0", id: msg.id, error: { code: -1, message: "no such thread" } });
        }
        break;
      case "thread/start":
        if (process.env.FAKE_CODEX_LAUNCH_CRASHES || process.env.FAKE_CODEX_LAUNCH_KILLS || process.env.FAKE_CODEX_LAUNCH_SILENT) {
          const launched = countLaunch();
          if (launched < (Number(process.env.FAKE_CODEX_LAUNCH_CRASHES) || 0)) {
            process.stderr.write(TRANSIENT_STDERR, () => process.exit(1));
            break;
          }
          if (launched < (Number(process.env.FAKE_CODEX_LAUNCH_KILLS) || 0)) {
            process.stderr.write(TRANSIENT_STDERR, () => process.kill(process.pid, "SIGKILL"));
            break;
          }
          if (launched < (Number(process.env.FAKE_CODEX_LAUNCH_SILENT) || 0)) {
            process.exit(1);
          }
        }
        out({ jsonrpc: "2.0", id: msg.id, result: { thread: { id: "codex-thread-1" }, model: "fake-codex-model" } });
        break;
      case "turn/start": {
        nativeThreadId = msg.params.threadId;
        if (process.env.FAKE_CODEX_STOP_RACE) {
          const heldId = msg.id;
          process.once("SIGTERM", () => {
            process.stdout.write(
              JSON.stringify({ jsonrpc: "2.0", id: heldId, error: { code: -32603, message: "provider returned 503: upstream capacity exceeded" } }) + "\n",
              () => process.exit(0),
            );
          });
          appendFileSync(process.env.FAKE_CODEX_STOP_RACE, "turn/start\n");
          break;
        }
        if (process.env.FAKE_CODEX_PREACK_CRASH) {
          countLaunch();
          const crash = () => process.stderr.write(TRANSIENT_STDERR, () => process.exit(1));
          if (process.env.FAKE_CODEX_PREACK_CRASH === "buffered") {
            process.stdout.write(JSON.stringify(notification("item/agentMessage/delta", { itemId: "early", delta: "early" })) + "\n", crash);
          } else crash();
          break;
        }
        if (process.env.FAKE_CODEX_ACK_CRASH) {
          countLaunch();
          process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: msg.id, result: turnResult() }) + "\n");
          void waitForGate(process.env.FAKE_CODEX_ACK_CRASH).then(() => {
            process.stderr.write(TRANSIENT_STDERR, () => process.exit(1));
          });
          break;
        }
        if (process.env.FAKE_CODEX_EXIT_MID_TURN) {
          countLaunch();
          const ackId = msg.id;
          process.stderr.write("2026-09-14T20:24:19Z ERROR codex_api::endpoint::responses_websocket: failed to connect to websocket: HTTP error: 426 Upgrade Required\n");
          void waitForGate(process.env.FAKE_CODEX_EXIT_MID_TURN).then(() => {
            out({ jsonrpc: "2.0", id: ackId, result: turnResult() });
            notify("item/reasoning/textDelta", { itemId: "m1", delta: "still thinking" });
            void waitForGate(process.env.FAKE_CODEX_EXIT_MID_TURN_KILL).then(() => process.kill(process.pid, "SIGKILL"));
          });
          break;
        }
        if (mode.startsWith("parent-")) {
          const ack = { jsonrpc: "2.0", id: msg.id, result: mode === "parent-invalid-ack" ? { ok: true } : turnResult() };
          const foreign = (threadId: string, turnId: string) => [
            notification("item/agentMessage/delta", { threadId, turnId, itemId: "foreign", delta: "FOREIGN" }),
            notification("item/reasoning/textDelta", { threadId, turnId, delta: "FOREIGN" }),
            notification("item/started", { threadId, turnId, item: { id: "foreign", type: "commandExecution", command: "FOREIGN" } }),
            notification("item/completed", { threadId, turnId, item: { id: "foreign", type: "agentMessage", text: "FOREIGN" } }),
            notification("item/completed", { threadId, turnId, item: { id: "foreign", type: "imageGeneration", result: "FOREIGN" } }),
            notification("thread/tokenUsage/updated", { threadId, turnId, tokenUsage: { last: { inputTokens: 999, outputTokens: 999 }, total: { inputTokens: 999, outputTokens: 999 } } }),
            notification("error", { threadId, turnId, error: { message: "FOREIGN" } }),
            notification("turn/completed", { threadId, turn: { id: turnId, status: "completed" } }),
          ];
          const parent = [
            notification("item/completed", { item: { id: "parent", type: "agentMessage", text: "parent reply" } }),
            notification("thread/tokenUsage/updated", { tokenUsage: { last: { inputTokens: 11, outputTokens: 2 }, total: { inputTokens: 20, outputTokens: 5 } } }),
            notification("turn/completed", { turn: { status: "completed" } }),
          ];
          let frames: unknown[];
          if (mode === "parent-early") frames = [...parent, ack];
          else if (mode === "parent-overflow") frames = [...Array.from({ length: 257 }, () => parent[0]), ack];
          else if (mode === "parent-invalid-ack") frames = [ack, ...parent];
          else {
            frames = [
              ...foreign("helper-thread", "helper-turn"),
              ...foreign(nativeThreadId, "old-turn"),
              ack,
              ...foreign("helper-thread", nativeTurnId),
              ...foreign(nativeThreadId, "helper-turn"),
              { method: "item/agentMessage/delta", params: { delta: "UNIDENTIFIED" } },
              { method: "turn/completed", params: { turn: { status: "completed" } } },
              { method: "error", params: { message: "connection diagnostic" } },
            ];
            if (mode === "parent-approval") {
              frames.push({ id: 100, method: "item/commandExecution/requestApproval", params: { threadId: "helper-thread", turnId: "helper-turn", itemId: "helper-command", command: "helper command" } });
            } else frames.push(...parent);
          }
          dump();
          // Deliberately one write: Promise continuation cannot be used to
          // bind identity before the parser consumes the following frame.
          process.stdout.write(frames.map((frame) => JSON.stringify(frame)).join("\n") + "\n");
          break;
        }
        if (mode === "safety-rejection") {
          dump();
          out({ jsonrpc: "2.0", id: msg.id, error: { code: -32603, message: "429 request blocked by our safety systems" } });
          break;
        }
        if (mode === "unauthorized") {
          out({
            jsonrpc: "2.0",
            id: msg.id,
            error: {
              code: -32603,
              message: "unexpected status 401 Unauthorized: Missing bearer or basic authentication in header",
            },
          });
          break;
        }
        if (mode === "terminal-error" || mode === "terminal-error-duplicate") {
          out({ jsonrpc: "2.0", id: msg.id, result: turnResult() });
          const message = "Provider rejected the request";
          if (mode === "terminal-error-duplicate") notify("error", { message });
          notify("turn/completed", { turn: { status: "failed", error: { message } } });
          break;
        }
        // transient-failure script for retry tests. FAKE_CODEX_TRANSIENTS is
        // how many launches fail transiently; the launch count lives in a
        // state FILE because child processes cannot mutate the parent's env.
        // FAKE_CODEX_PARTIAL_FAILS makes the FIRST failing turn stream a text
        // delta first, so the partial-output guard has something to see.
        if (process.env.FAKE_CODEX_TRANSIENTS && process.env.FAKE_CODEX_STATE) {
          let launched = 0;
          try {
            launched = Number(readFileSync(process.env.FAKE_CODEX_STATE, "utf8")) || 0;
          } catch {}
          const quota = Number(process.env.FAKE_CODEX_TRANSIENTS) || 0;
          writeFileSync(process.env.FAKE_CODEX_STATE, String(launched + 1));
          if (launched < quota) {
            if (process.env.FAKE_CODEX_PARTIAL_FAILS) {
              out({ jsonrpc: "2.0", id: msg.id, result: turnResult() });
              notify("item/agentMessage/delta", { itemId: "m1", delta: "half an answer" });
              notify("turn/completed", { turn: { status: "failed", error: { message: "provider overloaded, try again" } } });
              break;
            }
            out({
              jsonrpc: "2.0",
              id: msg.id,
              error: { code: -32603, message: "provider returned 503: upstream capacity exceeded" },
            });
            break;
          }
        }
        out({ jsonrpc: "2.0", id: msg.id, result: turnResult() });
        // Bounded-ingress fixtures (A4), keyed on the prompt text.
        const promptText = String(msg.params?.input?.[0]?.text ?? "");
        if (fixtureRequested(promptText, "__fixture_oversize_frame__")) {
          // a VALID frame one KiB over the limit, then a clean completion
          notify("item/agentMessage/delta", { itemId: "big", delta: fixtureOversizeText() });
          finishTurn();
          break;
        }
        if (fixtureRequested(promptText, "__fixture_oversize_open_frame__")) {
          process.stdout.write(`{"jsonrpc":"2.0","method":"item/agentMessage/delta","params":{"itemId":"big","delta":"${fixtureOversizeText()}`);
          break;
        }
        if (fixtureRequested(promptText, "__fixture_large_frame__")) {
          notify("item/completed", {
            item: { id: "img-large", type: "imageGeneration", status: "completed", result: fixtureLargeImageBase64(), revisedPrompt: "large" },
          });
          finishTurn();
          break;
        }
        const command = mode === "windows-command"
          ? [
              "\"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\"",
              "-Command",
              `\"Get-Content -Raw -LiteralPath 'C:\\Users\\Ada\\workspaces\\${"very-long-folder\\".repeat(8)}NOTES.md'\"`,
            ].join(" ")
          : "ls -la";
        notify("item/started", { item: { id: "i1", type: "commandExecution", command } });
        notify("item/started", { item: { id: "w1", type: "webSearch", query: "Murage" } });
        if (mode === "mcp-elicitation") {
          out({
            jsonrpc: "2.0",
            id: 101,
            method: "mcpServer/elicitation/request",
            params: {
              serverName: "agents",
              mode: "form",
              _meta: { codex_approval_kind: "mcp_tool_call", tool_params: {} },
              message: 'Allow the agents MCP server to run tool "list_bots"?',
              requestedSchema: { type: "object", properties: {} },
            },
          });
        } else if (mode === "form-elicitation") {
          // A plain MCP form elicitation: the server asks the OWNER for input
          // (no codex_approval_kind), which is a question, not a tool approval.
          out({
            jsonrpc: "2.0",
            id: 101,
            method: "mcpServer/elicitation/request",
            params: {
              serverName: "deployer",
              mode: "form",
              message: "Which environment should I deploy to?",
              requestedSchema: {
                type: "object",
                properties: { environment: { type: "string", enum: ["staging", "production"] } },
                required: ["environment"],
              },
            },
          });
        } else if (mode === "user-input") {
          // EXPERIMENTAL item/tool/requestUserInput exactly as codex-rs
          // v2/item.rs shapes it: several questions, each with its own id,
          // header and options; one secret, one free-text-only, one that
          // also takes the owner's own words.
          out({
            jsonrpc: "2.0",
            id: 101,
            method: "item/tool/requestUserInput",
            params: {
              threadId: "codex-thread-1",
              turnId: "turn-1",
              itemId: "call-rui-1",
              isBlocking: true,
              questions: [
                {
                  id: "db",
                  header: "Database",
                  question: "Which database should the service use?",
                  isOther: false,
                  isSecret: false,
                  options: [
                    { label: "Postgres", description: "Relational, durable" },
                    { label: "Redis", description: "In-memory, fast" },
                  ],
                },
                {
                  id: "token",
                  header: "Token",
                  question: "Paste the deploy token",
                  isOther: false,
                  isSecret: true,
                  options: null,
                },
                {
                  id: "region",
                  header: "Region",
                  question: "Which region?",
                  isOther: true,
                  isSecret: false,
                  options: [{ label: "eu-west", description: "Ireland" }],
                },
              ],
            },
          });
        } else if (mode === "approval" || mode === "windows-command") {
          const approvalCommand = mode === "windows-command" ? command : "rm -rf scratch";
          out({ jsonrpc: "2.0", id: 100, method: "execCommandApproval", params: { command: approvalCommand } });
          // turn continues from the approval response handler above
        } else {
          finishTurn();
        }
        break;
      }
      default:
        if (msg.id !== undefined) out({ jsonrpc: "2.0", id: msg.id, result: {} });
    }
  }
});

// match the real app-server: stay alive until killed
setInterval(() => {}, 1_000);
